#! /bin/bash

# uncomment for dry run
#ECHO=echo

BUILDDIR=$1
test -e "$BUILDDIR" || { echo "Arguments: BUILD_DIR"; exit 1; }

D=$BUILDDIR/test/iterplans

for src_file in `cd $D; find . -name *.spec`
do
  dst_file=${src_file%.spec}.iter
  $ECHO cp $D/$src_file $dst_file
done

# vim:set et sw=2 ts=2:
