#!/bin/sh

if test "$#" != "2"; then
    echo Args: dir1/LastTestsFailed.log dir2/LastTestsFailed.log
    exit 1
fi

TMP1=`mktemp /tmp/XXXXXX`
cat $2 | cut -f2 -d: | sort >$TMP1

cat $1 | cut -f2 -d: | sort | diff -U0 $TMP1 - | tail -n +3 | egrep -v '^@'

rm -f $TMP1
