
# SOURCES 	= \
# 	atomic_items.cpp \
# 	ft_options.cpp \
# 	ft_values.cpp \
# 	update_values.cpp \
# 	item.cpp

SOURCES 	= \
	item.cpp \
	atomic_items.cpp \
	basic_item_factory.cpp

primitive_values_test =	\
	primitive_values.cpp \
	primitive_values_test.cpp


BINARIES	= primitive_values_test


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
