
SOURCES 	= \
	primitive_values.cpp \
	ft_options.cpp \
	ft_values.cpp \
	update_values.cpp


primitive_values_test =	\
	primitive_values.cpp \
	primitive_values_test.cpp


EXECUTABLES = primitive_values_test


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
