(
xs:float("0") != xs:float("-0"),
xs:float("-0") != xs:float("0"),
xs:float("0") != xs:float("0"),
xs:float("1") != xs:float("1"),
xs:float("1") != xs:float("2"),
xs:float("2") != xs:float("1"),
xs:float("1") != xs:float("INF"),
xs:float("1") != xs:float("-INF"),
xs:float("1") != xs:float("NaN"),
xs:float("INF") != xs:float("1"),
xs:float("INF") != xs:float("INF"),
xs:float("INF") != xs:float("-INF"),
xs:float("INF") != xs:float("NaN"),
xs:float("-INF") != xs:float("1"),
xs:float("-INF") != xs:float("INF"),
xs:float("-INF") != xs:float("-INF"),
xs:float("-INF") != xs:float("NaN"),
xs:float("NaN") != xs:float("1"),
xs:float("NaN") != xs:float("INF"),
xs:float("NaN") != xs:float("-INF"),
xs:float("NaN") != xs:float("NaN")
)
