# Adds source files from a subfolder to a list of sources. Works 
# recursively. It will also create source groups with files and headers
# for use with MSVC.
#
# Syntax:
#
#  ADD_SRC_SUBFOLDER(DESTINATION_SRCS SUBFOLDER SOURCES_LIST1 SOURCES_LIST2 ...)
#
#    DESTINATION_SRCS - the list to which the sources in the subfolder will be added to
#    SUBFOLDER - the name of the subfolder
#    SOURCES_LISTx - the name of the list that contains the sources in the subfolder
#

MACRO (ADD_SRC_SUBFOLDER DESTINATION_SRCS SUBFOLDER ...)

	FILE(RELATIVE_PATH REL_PATH ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_LIST_FILE})
	GET_FILENAME_COMPONENT(REL_PATH ${REL_PATH} PATH)

	IF (REL_PATH STREQUAL "")
		SET(REL_PATH ${SUBFOLDER})
	ELSE (REL_PATH STREQUAL "")
		SET(REL_PATH ${REL_PATH}/${SUBFOLDER})
	ENDIF (REL_PATH STREQUAL "")
	
	INCLUDE (${REL_PATH}/CMakeLists.txt)
	FILE (GLOB HEADER_FILES ${REL_PATH}/*.h)
	SOURCE_GROUP (${REL_PATH} FILES ${REL_PATH}/${HEADER_FILES})


	SET(SUB_SRCS_LIST ${ARGV2} ${ARGN})

	FOREACH (SUB_SRCS ${SUB_SRCS_LIST})
		FOREACH (SRCS ${${SUB_SRCS}})
			SOURCE_GROUP (${SUBFOLDER} FILES ${SUBFOLDER} /${SRCS})
			LIST(APPEND ${DESTINATION_SRCS} ${SUBFOLDER}/${SRCS})
		ENDFOREACH (SRCS ${${SUB_SRCS}})
	ENDFOREACH (SUB_SRCS ${SUB_SRCS_LIST})

ENDMACRO (ADD_SRC_SUBFOLDER DESTINATION_SRCS SUBFOLDER ...)


# Prints out a CMake list
MACRO(PRINT_LIST LIST)
	FOREACH (ITEM ${${LIST}})
		MESSAGE(${LIST} ": " ${ITEM})
	ENDFOREACH (ITEM ${${LIST}})
ENDMACRO(PRINT_LIST LIST)

# Adds header files from the given subfolder to a SOURCE_GROUP, for use with MSVC
MACRO (HEADER_GROUP_SUBFOLDER SUBFOLDER)
	FILE(RELATIVE_PATH REL_PATH ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_LIST_FILE})
	GET_FILENAME_COMPONENT(REL_PATH ${REL_PATH} PATH)

	IF (REL_PATH STREQUAL "")
		SET(REL_PATH ${SUBFOLDER})
	ELSE (REL_PATH STREQUAL "")
		SET(REL_PATH ${REL_PATH}/${SUBFOLDER})
	ENDIF (REL_PATH STREQUAL "")
	
	FILE (GLOB HEADER_FILES ${REL_PATH}/*.h)
	SOURCE_GROUP (${REL_PATH} FILES ${REL_PATH}/${HEADER_FILES})
ENDMACRO (HEADER_GROUP_SUBFOLDER SUBFOLDER)
