
SOURCES 		= signature.cpp function.cpp library.cpp Sequences.cpp SequencesImpl.cpp Numerics.cpp NumericsImpl.cpp 

Sequences_test	= Sequences_test.cpp

EXECUTABLES 	= Sequences_test


# Include global Makefile rules
ROOT_PATH		= ..
include $(ROOT_PATH)/Makefile.rules
