
SOURCES 		= signature.cpp function.cpp library.cpp Sequences.cpp SequencesImpl.cpp Numerics.cpp NumericsImpl.cpp 


function_test 	= \
		../types/sequence_type.cpp \
		../store/itemstore.cpp \
		../util/file.cpp \
		../util/mmfile.cpp \
		../util/fxcharheap.cpp \
		../util/xqp_exception.cpp \
		../values/qname_value.cpp \
		../values/xs_primitive_values.cpp \
		signature.cpp \
		function.cpp


Sequences_test 	= \
		../dom/dom_qname.cpp \
		../dom/dom_namepool.cpp \
		../dom/dom_nodes.cpp \
		../dom/dom_xml_handler.cpp \
		../runtime/errors.cpp \
		../runtime/item_iterator.cpp \
		../runtime/zorba.cpp \
		../store/itemstore.cpp \
		../store/scan_handler.cpp \
		../store/xml_scanner.cpp \
		../store/uri_resolver.cpp \
		../store/zorba_uri_resolver.cpp \
		../types/sequence_type.cpp \
		../util/file.cpp \
		../util/mmfile.cpp \
		../util/fxcharheap.cpp \
		../util/tokenbuf.cpp \
		../util/URI.cpp \
		../util/xqp_exception.cpp \
		../values/primitive_values.cpp \
		../zorba/qnamerep.cpp \
		../zorba/valuereps.cpp \
		../zorba/zorba_qname.cpp \
		../zorba/zorba_value_factory.cpp \
		library.cpp \
		signature.cpp \
		Numerics.cpp \
		Sequences.cpp \
		SequencesImpl.cpp \
		Sequences_test.cpp


Numerics_test	= \
		../dom/dom_qname.cpp \
		../dom/dom_namepool.cpp \
		../dom/dom_nodes.cpp \
		../dom/dom_xml_handler.cpp \
		../runtime/errors.cpp \
		../runtime/item_iterator.cpp \
		../runtime/zorba.cpp \
		../store/itemstore.cpp \
		../store/scan_handler.cpp \
		../store/uri_resolver.cpp \
		../store/zorba_uri_resolver.cpp \
		../store/xml_scanner.cpp \
		../types/sequence_type.cpp \
		../util/file.cpp \
		../util/mmfile.cpp \
		../util/fxcharheap.cpp \
		../util/tokenbuf.cpp \
		../util/URI.cpp \
		../util/xqp_exception.cpp \
		../values/primitive_values.cpp \
		../zorba/qnamerep.cpp \
		../zorba/valuereps.cpp \
		../zorba/zorba_qname.cpp \
		../zorba/zorba_value_factory.cpp \
		signature.cpp \
		library.cpp \
		Sequences.cpp \
		SequencesImpl.cpp \
		Numerics.cpp \
		Numerics_test.cpp


library_test	= \
		library_test.cpp


BINARIES		= function_test Sequences_test Numerics_test library_test 


# Include global Makefile rules
ROOT_PATH		= ..
include $(ROOT_PATH)/Makefile.rules
