SET (CTEST_DROP_METHOD xmlrpc) 
SET (CTEST_PROJECT_NAME "zorba") 
SET (CTEST_NIGHTLY_START_TIME "23:00:00 GMT") 
SET (CTEST_DROP_SITE "http://fifthelement.inf.ethz.ch:8082") 
SET (CTEST_DROP_LOCATION "zorba") 
SET (CTEST_COMPRESS_SUBMISSION ON)

