
CXXFLAGS		= -Wall -Wno-uninitialized -g -I${ROOT_PATH}

OPT 			= -Wall -Wno-uninitialized -g -I${ROOT_PATH}

LARGEFILES		= -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE

LEX				= flex 
LFLAGS			= -i -t -v

YACC			= bison
YFLAGS			= -v -t -d 


# Output 

SUFX			= do

BUILD_FOLDER	= Build



