
include $(ROOT_PATH)/Makefile.conf

##############################################################################
# Functions
##############################################################################

DF				= $(BUILD_FOLDER)/$(*F)

EXES			= $(patsubst %,$(BUILD_FOLDER)/%,$(notdir $(BINARIES)))

MAKE_OBJS 		= $(foreach target,$(1),$(dir $(target))$(BUILD_FOLDER)/$(notdir $(basename $(target))).$(SUFX))

PARENT_FOLDER 	= $(notdir $(subst /$(BUILD_FOLDER)/,,$(dir $(abspath $(DF)))))


define MAKEDEP	
	@if test -f $(*F).d; then mv $(*F).d $(BUILD_FOLDER)/; fi
	@sed -e "s/ \([^/ \n\t\\]\+\) / ..\/$(call PARENT_FOLDER,$(DF))\/\1 /g" \
		 -e "s/ \([^/ \n\t\\]\+\) / ..\/$(call PARENT_FOLDER,$(DF))\/\1 /g" \
		 -e "s/ \([^/ \n\t\\]\+\)$$/ ..\/$(call PARENT_FOLDER,$(DF))\/\1 /g" \
		 -e "s/\($(BUILD_FOLDER)\/[^/ \n\t\\]\+\):/\1 ..\/$(call PARENT_FOLDER,$(DF))\/\1:/g" < $(DF).d > $(DF).dd
	@cp $(DF).dd $(DF).P
	@sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		 -e '/^$$/ d' -e 's/$$/ :/' < $(DF).dd >> $(DF).P
	@rm -f $(DF).d $(DF).dd 
endef


define MAKE_DEPENDENCY

ifneq ($(dir $(1)),)
ifneq ($(dir $(1)),./)

$(call MAKE_OBJS,$(1)):
	$(MAKE) -C $$(subst /$(BUILD_FOLDER)/,,$$(dir $$@)) -f Makefile.a SOURCES=$(notdir $(1))

-include $(patsubst %.$(SUFX),%.P,$(call MAKE_OBJS,$(1))) 

endif
endif

endef


define MAKE_TARGET

$(foreach dependency,$(2),$(call MAKE_DEPENDENCY,$(dependency)))

$$(BUILD_FOLDER)/$(1): $(call MAKE_OBJS,$(2))
	$(CXX) $(CXXFLAGS) -o $$@ $$^

endef



##############################################################################
# Targets
##############################################################################

all build: build_objs

build_objs: $(BUILD_FOLDER) $(call MAKE_OBJS,$(SOURCES))

test: $(BUILD_FOLDER) $(EXES)

clean:
	rm -rf $(BUILD_FOLDER)


.PHONY: all build build_objs test clean


##############################################################################
# Rules
##############################################################################


$(foreach target,$(BINARIES),$(eval $(call MAKE_TARGET,$(target),$($(target)))))


$(BUILD_FOLDER):
	mkdir -p $(BUILD_FOLDER)

$(BUILD_FOLDER)/%.$(SUFX) : %.cpp
	$(CXX) -c $(CXXFLAGS) -MMD -o $@ $<
	$(MAKEDEP)

%.cpp: %.l
	@$(RM) $@ 
	$(LEX.l) $< > $@

%.cpp: %.y
	$(YACC.y) $< 
	mv -f $*.tab.c $@

-include $(patsubst %.$(SUFX),%.P,$(call MAKE_OBJS,$(SOURCES))) $(ROOT_PATH)/Makefile.conf
