
SUBDIRS		= \
				context \
				dom \
				exprtree \
				functions \
				listeners \
				parser \
				runtime \
				store \
				types \
				util \
				values \
				zorba


all: 
	$(MAKE) subdirs TARGET=all_all -f Makefile.a

test:
	$(MAKE) subdirs TARGET=test -f Makefile.a

clean: 
	$(MAKE) subdirs TARGET=clean_all -f Makefile.a


.PHONY: subdirs $(SUBDIRS)

subdirs: $(SUBDIRS)

$(SUBDIRS):
	$(MAKE) $(TARGET) -C $@ -f Makefile.a 


# Include global Makefile rules
ROOT_PATH	= .
include $(ROOT_PATH)/Makefile.rules
