#!/bin/bash -f

# Generate a file aclocal.m4 that contains macros for automake 

aclocal

# Automake now reads configure.ac and the top-level Makefile.am, 
# interprets them (e.g. see further work has to be done in some 
# subdirectories) and, for each Makefile.am produces a Makefile.in. The 
# argument --add-missing tells automake to provide default scripts for 
# reporting errors, installing etc, so it can be omitted in the next 
# runs. 

automake --add-missing

# Finally, let autoconf build the configure script:
# This produces the final, full-featured configure shell script.

autoconf

