#!/usr/bin/env perl
# Strips pointers inside CtxVariableIterator.
# Call with no arguments.

use strict;
use warnings;

my $ctx = 0;

while (my $s = <>) {
    if ($s =~ m@[<]CtxVariable@) { $ctx = 1 }
    elsif ($s =~ m@[<]/CtxVariable@) { $ctx = 0 }

    if ($ctx) { $s =~ s/0x[0-9a-z]+:// }

    print $s;
}
