zorba::SmartPtr
T* zorba::SmartPtr< T >::p
Referenced by zorba::SmartPtr< T >::assign, zorba::SmartPtr< T >::get, zorba::SmartPtr< T >::init, zorba::SmartPtr< T >::isNull, zorba::SmartPtr< T >::operator!=, zorba::SmartPtr< T >::operator*, zorba::SmartPtr< T >::operator->, zorba::SmartPtr< T >::operator<, zorba::SmartPtr< T >::operator==, zorba::SmartPtr< T >::~SmartPtr.
SmartPtr& zorba::SmartPtr< T >::assign(const SmartPtr< otherT > &rhs)
References zorba::SmartPtr< T >::get, zorba::SmartPtr< T >::init, zorba::SmartPtr< T >::p.
Referenced by zorba::SmartPtr< T >::operator=.
void zorba::SmartPtr< T >::init()
References zorba::SmartPtr< T >::p.
Referenced by zorba::SmartPtr< T >::assign, zorba::SmartPtr< T >::SmartPtr.
T* zorba::SmartPtr< T >::get() const
References zorba::SmartPtr< T >::p.
Referenced by zorba::SmartPtr< T >::assign.
bool zorba::SmartPtr< T >::isNull() const
References zorba::SmartPtr< T >::p.
zorba::SmartPtr< T >::operator const T *() const
zorba::SmartPtr< T >::operator T *()
bool zorba::SmartPtr< T >::operator!=(SmartPtr const &h) const
References zorba::SmartPtr< T >::p.
bool zorba::SmartPtr< T >::operator!=(T const *pp) const
References zorba::SmartPtr< T >::p.
T& zorba::SmartPtr< T >::operator*() const
References zorba::SmartPtr< T >::p.
T* zorba::SmartPtr< T >::operator->() const
References zorba::SmartPtr< T >::p.
bool zorba::SmartPtr< T >::operator<(const SmartPtr &h) const
References zorba::SmartPtr< T >::p.
SmartPtr& zorba::SmartPtr< T >::operator=(SmartPtr const &rhs)
References zorba::SmartPtr< T >::assign.
SmartPtr& zorba::SmartPtr< T >::operator=(SmartPtr< otherT > const &rhs)
References zorba::SmartPtr< T >::assign.
bool zorba::SmartPtr< T >::operator==(SmartPtr const &h) const
References zorba::SmartPtr< T >::p.
bool zorba::SmartPtr< T >::operator==(T const *pp) const
References zorba::SmartPtr< T >::p.
zorba::SmartPtr< T >::SmartPtr(T *realPtr=0)
References zorba::SmartPtr< T >::init.
zorba::SmartPtr< T >::SmartPtr(SmartPtr const &rhs)
References zorba::SmartPtr< T >::init.
zorba::SmartPtr< T >::~SmartPtr()
References zorba::SmartPtr< T >::p.