zorba::internal::ztd::explicit_bool
typedef int pointer_conversion::* zorba::internal::ztd::explicit_bool::type
static type zorba::internal::ztd::explicit_bool::false_value()
Gets the explicit bool value for false.
Returns said value.
Referenced by value_of.
static type zorba::internal::ztd::explicit_bool::true_value()
Gets the explicit bool value for true.
Returns said value.
Referenced by value_of.
static std::enable_if<ZORBA_TR1_NS::is_convertible<T,bool>::value, type>::type zorba::internal::ztd::explicit_bool::value_of(T const &value)
Converts the given value to an explicit bool value.
T The type of the value to convert. value The value to convert. Return said value.
References false_value, true_value.
Referenced by std::unique_ptr< iterator >::operator explicit_bool::type, std::unique_ptr< T[], D >::operator explicit_bool::type.