std::unique_ptr
typedef ZORBA_TR1_NS::add_reference<D const>::type std::unique_ptr< T, D >::deleter_const_reference
typedef ZORBA_TR1_NS::add_reference<D>::type std::unique_ptr< T, D >::deleter_reference
typedef zorba::internal::ztd::explicit_bool std::unique_ptr< T, D >::explicit_bool
typedef D std::unique_ptr< T, D >::deleter_type
typedef T std::unique_ptr< T, D >::element_type
typedef T* std::unique_ptr< T, D >::pointer
unique_ptr_storage<T,D> std::unique_ptr< T, D >::storage_
pointer std::unique_ptr< T, D >::get() const
Gets the pointer.
Returns said pointer.
deleter_reference std::unique_ptr< T, D >::get_deleter()
Gets the deleter in use.
Returns said deleter.
deleter_const_reference std::unique_ptr< T, D >::get_deleter() const
Gets the deleter in use.
Returns said deleter.
std::unique_ptr< T, D >::operator explicit_bool::type() const
Conversion to bool.
Returns true only if the pointer is not null; false only if the pointer is null.
element_type& std::unique_ptr< T, D >::operator*() const
Dereferences the pointer.
Returns a reference to the pointed-to object.
pointer std::unique_ptr< T, D >::operator->() const
Gets the pointer.
Returns said pointer.
std::unique_ptr< T, D >::operator::zorba::internal::rv()
std::unique_ptr< T, D >::operator::zorba::internal::rv() const
unique_ptr& std::unique_ptr< T, D >::operator=(zorba::internal::rv< unique_ptr > &p)
Destructive assignment: moves ownership of the object pointed-to by p to this unique_ptr.
The object pointed-to by this unique_ptr, if any, is deleted. p The unique_ptr to move from. Returns *this.
unique_ptr& std::unique_ptr< T, D >::operator=(zorba::internal::rv< unique_ptr< U, E > > &p)
Destructive assignment: moves ownership of the object pointed-to by p to this unique_ptr.
The object pointed-to by this unique_ptr, if any, is deleted. U The pointed-to type such that U* is convertible to T*. E The deleter of p. p The unique_ptr to move from. Returns *this.
unique_ptr& std::unique_ptr< T, D >::operator=(int)
Assignment from null: equivalent to reset().
Returns *this.
pointer std::unique_ptr< T, D >::release()
Releases ownership of the pointed-to object.
Said object will now be the responsibility of the caller.Returns a pointer to the object.
void std::unique_ptr< T, D >::reset(pointer p=nullptr)
Sets the pointer to the given value or null if none.
The previosly pointed-to object, if any, is deleted. However, if p equals the current pointer value, then this function does nothing. p The new pointer value, if any.
Referenced by std::unique_ptr< iterator >::operator=, std::unique_ptr< T[], D >::operator=.
void std::unique_ptr< T, D >::swap(unique_ptr &p)
Swaps the pointer and deleter with that of another unique_ptr.
p The unique_ptr to swap with.
Referenced by std::unique_ptr< iterator >::swap, std::unique_ptr< T[], D >::swap, std::swap.
std::unique_ptr< T, D >::unique_ptr(pointer p=nullptr)
Default constructor.
p A pointer to the object to point to, if any.
std::unique_ptr< T, D >::unique_ptr(pointer p, deleter_reference d)
Constructs a unique_ptr using a specific deleter.
This unique_ptr now has ownership of the pointed-to object. p A pointer to the object to own. d The deleter to use.
std::unique_ptr< T, D >::unique_ptr(zorba::internal::rv< unique_ptr > &p)
Constructs a unique_ptr from an existing unique_ptr.
Note that: unique_ptr<int>a(newint(1)); unique_ptr<int>b(a);//compile-timeerror Instead, you must use the move() function: unique_ptr<int>a(newint(1)); unique_ptr<int>b(move(a));//oknow p The unique_ptr to move from.
std::unique_ptr< T, D >::unique_ptr(zorba::internal::rv< unique_ptr< U, E > > &p, typename enable_if< ZORBA_TR1_NS::is_convertible< typename unique_ptr< U >::pointer, pointer >::value &&ZORBA_TR1_NS::is_convertible< E, D >::value &&(!ZORBA_TR1_NS::is_reference< D >::value||ZORBA_TR1_NS::is_same< D, E >::value) >::type *=nullptr)
Constructs a unique_ptr from an existing unique_ptr.
U The pointed-to type such that U* is convertible to T*. E The deleter such that E is convertible to D. p The unique_ptr to move from.
std::unique_ptr< T, D >::~unique_ptr()
Destroys the pointed-to object by calling the deleter (if the pointer is not null).
void std::unique_ptr< T, D >::call_deleter()
unique_ptr& std::unique_ptr< T, D >::operator=(unique_ptr &)
unique_ptr& std::unique_ptr< T, D >::operator=(unique_ptr< U, E > &)
std::unique_ptr< T, D >::unique_ptr(unique_ptr &)
std::unique_ptr< T, D >::unique_ptr(unique_ptr< U, E > &)