zorba::time::Timer
walltime zorba::time::Timer::theStart
double zorba::time::Timer::elapsed() const
References zorba::time::get_current_walltime, zorba::time::get_walltime_elapsed.
Referenced by zorba::audit::AuditorTraits< zorba::time::Timer >::end, zorba::audit::AuditorTraits< zorba::time::Timer, 0x2 >::end.
time::msec_type zorba::time::Timer::getStart() const
References zorba::time::get_walltime_in_millis.
Referenced by zorba::audit::AuditorTraits< zorba::time::Timer, 0x1 >::end.
void zorba::time::Timer::start()
References zorba::time::get_current_walltime.
Referenced by zorba::audit::AuditorTraits< zorba::time::Timer >::start, zorba::audit::AuditorTraits< zorba::time::Timer, 0x1 >::start, zorba::audit::AuditorTraits< zorba::time::Timer, 0x2 >::start.