std::unique_ptr_storage
typedef ZORBA_TR1_NS::add_reference<D>::type std::unique_ptr_storage< T, D, bool >::deleter_reference
typedef zorba::internal::rv<unique_ptr_storage> std::unique_ptr_storage< T, D, bool >::rvalue_type
T* std::unique_ptr_storage< T, D, bool >::ptr_
Referenced by std::unique_ptr< iterator >::get, std::unique_ptr< T[], D >::get, std::unique_ptr< iterator >::release, std::unique_ptr< T[], D >::release, std::unique_ptr< iterator >::reset, std::unique_ptr< T[], D >::reset, std::swap.
D std::unique_ptr_storage< T, D, bool >::deleter_
deleter_reference std::unique_ptr_storage< T, D, bool >::deleter()
Referenced by std::unique_ptr< iterator >::get_deleter, std::unique_ptr< T[], D >::get_deleter, std::unique_ptr< iterator >::operator=, std::unique_ptr< T[], D >::operator=, std::swap.
std::unique_ptr_storage< T, D, bool >::operator rvalue_type()
std::unique_ptr_storage< T, D, bool >::unique_ptr_storage(T *p)
std::unique_ptr_storage< T, D, bool >::unique_ptr_storage(T *p, deleter_reference d)
unique_ptr_storage& std::unique_ptr_storage< T, D, bool >::operator=(unique_ptr_storage const &)
std::unique_ptr_storage< T, D, bool >::unique_ptr_storage(unique_ptr_storage const &)