zorba::UserException
typedef internal::diagnostic::location::column_type zorba::XQueryException::column_type
typedef internal::error_object_type zorba::UserException::error_object_type
typedef internal::diagnostic::location::line_type zorba::ZorbaException::line_type
print_format
plain text
print_trace
error_object_type zorba::UserException::error_object_
column_type zorba::XQueryException::applied_column() const
Gets the XQuery source-code "applied at" column number containing the error.
Returns said column number or 0 if unset.
column_type zorba::XQueryException::applied_column_end() const
Gets the XQuery source-code "applied at" end column number containing the error.
Returns said column number or 0 if unset.
line_type zorba::XQueryException::applied_line() const
Gets the XQuery source-code "applied at" line number containing the error.
Returns said line number or 0 if unset.
line_type zorba::XQueryException::applied_line_end() const
Gets the XQuery source-code "applied at" end line number containing the error.
Returns said line number or 0 if unset.
char const* zorba::XQueryException::applied_uri() const
Gets the XQuery source-code "applied at" URI containing the error.
Returns said URI or the empty string if unset.
column_type zorba::XQueryException::data_column() const
Gets the data column number containing the error.
Returns said column number or 0 if unset.
column_type zorba::XQueryException::data_column_end() const
Gets the data end column number containing the error.
Returns said column number or 0 if unset.
line_type zorba::XQueryException::data_line() const
Gets the data line number containing the error.
Returns said line number or 0 if unset.
line_type zorba::XQueryException::data_line_end() const
Gets the data end line number containing the error.
Returns said line number or 0 if unset.
char const* zorba::XQueryException::data_uri() const
Gets the data URI containing the error.
Returns said URI or the empty string if unset.
Diagnostic const& zorba::ZorbaException::diagnostic() const
Gets the diagnostic carried by this exception.
Returns said diagnostic.
error_object_type const& zorba::UserException::error_object() const
Gets the error object associated with this exception.
Returns said error object.
bool zorba::XQueryException::has_applied() const
Checks whether the XQuery "applied at" location has been set.
Returns true only if the "applied at" location has been set.
bool zorba::XQueryException::has_data() const
Checks whether the XQuery data location has been set.
Returns true only if the data location has been set.
bool zorba::XQueryException::has_source() const
Checks whether the XQuery source-code location has been set.
Returns true only if said has been set.
UserException& zorba::UserException::operator=(UserException const &from)
Assigns this UserException from another.
from The UserException to assign from. Returns *this.
void zorba::UserException::polymorphic_throw() const
Throws itself polymorphically; see http://www.parashift.com/c++-faq-lite/exceptions.html#faq-17.16.
XQueryStackTrace& zorba::XQueryException::query_trace()
Gets the XQuery stack trace, if any.
Returns said stack trace.
XQueryStackTrace const& zorba::XQueryException::query_trace() const
Gets the XQuery stack trace, if any.
Returns said stack trace.
char const* zorba::ZorbaException::raise_file() const
Gets the C++ source-code file name whence this exception was raised.
Returns said file name.
line_type zorba::ZorbaException::raise_line() const
Gets the C++ source-code line number whence this exception was raised.
Returns said line number.
void zorba::XQueryException::set_applied(char const *uri, line_type line, column_type column=0, line_type line_end=0, column_type column_end=0)
Sets the XQuery source-code "applied at" URI name, line, and column numbers.
uri The source-code "applied at" URI name. If either the null pointer or the empty string, source_uri() is used. line The source-code "applied at" URI line number. column The source-code "applied at" URI column number. line_end The source-code "applied at" URI end line number. column_end The source-code "applied at" URI end column number.
void zorba::XQueryException::set_data(char const *uri, line_type line, column_type column=0, line_type line_end=0, column_type column_end=0)
Sets the XQuery source-code data URI name, line, and column numbers.
uri The source-code data URI name. Must not be null. line The source-code data URI line number. column The source-code data URI column number. line_end The source-code data URI end line number. column_end The source-code data URI end column number.
void zorba::ZorbaException::set_diagnostic(Diagnostic const &diagnostic)
Sets the diagnostic.
diagnostic The diagnostic.
void zorba::XQueryException::set_source(char const *uri, line_type line, column_type column=0, line_type line_end=0, column_type column_end=0)
Sets the XQuery source-code URI name, line, and column numbers.
uri The source-code URI name. line The source-code URI line number. column The source-code URI column number. line_end The source-code URI end line number. column_end The source-code URI end column number.
column_type zorba::XQueryException::source_column() const
Gets the XQuery source-code column number containing the error.
Returns said column number or 0 if unset.
column_type zorba::XQueryException::source_column_end() const
Gets the XQuery source-code end column number containing the error.
Returns said column number or 0 if unset.
line_type zorba::XQueryException::source_line() const
Gets the XQuery source-code line number containing the error.
Returns said line number or 0 if unset.
line_type zorba::XQueryException::source_line_end() const
Gets the XQuery source-code end line number containing the error.
Returns said line number or 0 if unset.
char const* zorba::XQueryException::source_uri() const
Gets the XQuery source-code URI containing the error.
Returns said URI or the empty string if unset.
zorba::UserException::UserException(UserException const &from)
Copy-constructs a UserException.
from The UserException to copy from.
char const* zorba::ZorbaException::what() const
zorba::UserException::~UserException()
Destroys this UserException.
std::unique_ptr<ZorbaException> zorba::UserException::clone() const
Clones this exception object.
Returns a clone of this exception.
std::ostream& zorba::ZorbaException::print(std::ostream &) const
Prints the exception to the given ostream.
o The ostream to print to. Returns o.
Referenced by zorba::operator<<.
std::ostream& zorba::XQueryException::print_impl(std::ostream &) const
std::ostream& zorba::XQueryException::print_stack_trace(std::ostream &) const
zorba::UserException::UserException(char const *ns, char const *prefix, char const *localname, char const *raise_file, line_type raise_line, char const *description, error_object_type *error_object)
Constructs a UserException.
ns The namespace of the error. prefix The prefix of the error. locaname The local-name of the error. raise_file The source-code file name whence the exception was raised. raise_line The source-code line number whence the exception was raised. description The error description. error_object The error object.
zorba::UserException::UserException(Error const &error, char const *raise_file, line_type raise_line, char const *description, error_object_type *error_object)
Constructs a UserException.
error The error. raise_file The source-code file name whence the exception was raised. raise_line The source-code line number whence the exception was raised. description The error description. error_object The error object.
zorba::UserException::UserException(serialization::Archiver &)
UserException internal::make_user_exception(char const *, line_type, char const *, char const *, char const *, char const *, internal::diagnostic::location const &, error_object_type *)
UserException internal::make_user_exception(char const *, line_type, Error const &, char const *, internal::diagnostic::location const &, error_object_type *)
void serialization::operator&(serialization::Archiver &, ZorbaException *&)
static print_format zorba::ZorbaException::get_print_format(std::ostream &o)
Gets the current print_format associated with the given ostream.
o The ostream to get the print_format of. Returns said print_format.
static bool zorba::XQueryException::get_print_trace(std::ostream &o)
Gets whether XQuery stack traces will be included when XQueryExceptions are printed to the given ostream.
o The ostream. Returns true only if stack traces will be included.
static void zorba::ZorbaException::set_print_format(std::ostream &o, print_format f)
Sets the print_format of the given ostream.
o The ostream to set the print_format of. f The print_format value.
Referenced by zorba::operator<<.
static void zorba::XQueryException::set_print_trace(std::ostream &o, bool print)
Sets whether XQuery stack traces will be included when XQueryExceptions are printed to the given ostream.
o The ostream to affect. print If true, stack traces will be included.
Referenced by zorba::operator<<.
static bool zorba::XQueryException::print_uri(std::ostream &, char const *uri)