zorba::time
typedef clock_t zorba::time::cputime
typedef long long zorba::time::msec_type
typedef struct timeval zorba::time::walltime
double zorba::time::get_cputime_elapsed(const cputime &t0, const cputime &t1)
void zorba::time::get_current_cputime(cputime &t)
void zorba::time::get_current_walltime(walltime &t)
Referenced by zorba::time::Timer::elapsed, zorba::time::Timer::start.
double zorba::time::get_walltime_elapsed(const walltime &t0, const walltime &t1)
Referenced by zorba::time::Timer::elapsed.
msec_type zorba::time::get_walltime_in_millis(const walltime &t)
Referenced by zorba::time::Timer::getStart.