zorba::internal::base64
ZORBA_DLL_PUBLIC std::streambuf* zorba::internal::base64::alloc_streambuf(std::streambuf *orig)
Referenced by zorba::hexbinary::attach, zorba::transcode::attach, zorba::base64::attach.
ZORBA_DLL_PUBLIC int zorba::internal::base64::get_streambuf_index()
Referenced by zorba::hexbinary::attach, zorba::transcode::attach, zorba::base64::attach, zorba::hexbinary::detach, zorba::transcode::detach, zorba::base64::detach, zorba::base64::is_attached.