zorba::fs
type
typedef os_error::exception zorba::fs::exception
typedef off_t zorba::fs::size_type
File size type.
char const zorba::fs::dir_separator
Referenced by append, base_name, dir_name.
char const zorba::fs::newline[][]
char const zorba::fs::path_separator
std::enable_if<ZORBA_IS_STRING(PathStringType1),void>::type zorba::fs::append(PathStringType1 &path1, char const *path2)
Appends a path component onto another path ensuring that exactly one separator is used.
PathStringType1 The path1 string type. path1 The path to append to. path2 The path to append.
References dir_separator.
Referenced by append, zorba::String::operator+=.
std::enable_if<ZORBA_IS_STRING(PathStringType1) && ZORBA_HAS_C_STR(PathStringType2), void>::type zorba::fs::append(PathStringType1 &path1, PathStringType2 const &path2)
Appends a path component onto another path.
PathStringType1 The path1 string type. PathStringType2 The path2 string type. path1 The path to append to. path2 The path to append.
References append.
char const* zorba::fs::base_name(char const *path)
Gets the base name of the given path name, i.e., the file name without the path leading up to it.
path The full path to get the base name of. Returns the base name. Note that if path is just a file name, then returns path.
References dir_separator.
std::enable_if<ZORBA_IS_STRING(PathStringType),PathStringType>::type zorba::fs::base_name(PathStringType const &path)
Gets the base name of the given path name, i.e., the file name without the path leading up to it.
PathStringType The path string type. path The full path to get the base name of. Returns the base name. If path is just a file name, returns path.
References dir_separator.
ZORBA_DLL_PUBLIC std::string zorba::fs::curdir()
Gets the current directory.
Returns said directory. ZorbaException with a diagnostic of zerr::ZOSE0004_IO_ERROR if it fails.
Referenced by make_absolute.
std::string zorba::fs::dir_name(char const *path)
Gets the directory name of the given path name, i.e., the path up to but not including the last path component.
path The path to get the directory name of. Returns the direcory path. If path is just a file name, returns '.'.
References dir_separator.
std::enable_if<ZORBA_IS_STRING(PathStringType),PathStringType>::type zorba::fs::dir_name(PathStringType const &path)
Gets the directory name of the given path name, i.e., the path up to but not including the last path component.
PathStringType The path string type. path The path to get the directory name of. Returns the direcory path. If path is just a file name, returns '.'.
References dir_separator, is_absolute.
bool zorba::fs::is_absolute(char const *path)
Checks whether the given path is an absolute path.
path The full path to check. Returns true only if the path is absolute.
Referenced by dir_name, is_absolute, make_absolute.
std::enable_if<ZORBA_HAS_C_STR(PathStringType),bool>::type zorba::fs::is_absolute(PathStringType const &path)
Checks whether the given path is an absolute path.
PathStringType The path string type. path The full path to check. Returns true only if the path is absolute.
References is_absolute.
std::enable_if<ZORBA_IS_STRING(PathStringType),void>::type zorba::fs::make_absolute(PathStringType *path)
Makes a relative path into an absolute path.
PathStringType The path string type. path A pointer to the path to make absolute.
References zorba::internal::ztd::c_str, curdir, is_absolute.
ZORBA_DLL_PUBLIC std::string zorba::fs::normalize_path(char const *path, char const *base=nullptr)
Gets the normalized path of the given path.
A normalized path is one that: has file:// URIs converted to pathshas directory separators corrected for the host operating systemhas adjacent directory separators combined, e.g., /a//b becomes /a/b has ./ removed, e.g., /a/./b becomes /a/b has ../ removed, e.g., /a/b/../c becomes /a/c path The path to normalize. base The base path. If not empty, is prepended to path. Returns the normalized path. std::invalid_argument for malformed paths.
Referenced by normalize_path.
std::enable_if<ZORBA_HAS_C_STR(PathStringType),std::string>::type zorba::fs::normalize_path(PathStringType const &path)
Gets the normalized path of the given path.
A normalized path is one that: has file:// URIs converted to pathshas directory separators corrected for the host operating systemhas adjacent directory separators combined, e.g., /a//b becomes /a/b has ./ removed, e.g., /a/./b becomes /a/b has ../ removed, e.g., /a/b/../c becomes /a/c PathStringType The path string type. path The path to normalize. Returns the normalized path. std::invalid_argument for malformed paths.
References normalize_path.
std::enable_if<ZORBA_HAS_C_STR(PathStringType) && ZORBA_HAS_C_STR(BaseStringType), std::string>::type zorba::fs::normalize_path(PathStringType const &path, BaseStringType const &base)
Gets the normalized path of the given path.
A normalized path is one that: has file:// URIs converted to pathshas directory separators corrected for the host operating systemhas adjacent directory separators combined, e.g., /a//b becomes /a/b has ./ removed, e.g., /a/./b becomes /a/b has ../ removed, e.g., /a/b/../c becomes /a/c PathStringType The path string type. BaseStringType The base string type. path The path to normalize. base The base path. If not empty, is prepended to path. Returns the normalized path. std::invalid_argument for malformed paths.
References normalize_path.
ZORBA_DLL_PUBLIC std::ostream& zorba::fs::operator<<(std::ostream &o, type t)
Emits the string representation of a file type to the given ostream.
o The ostream to emit to. t The file type to emit. Returns o.