zorba::internal::ztd
std::enable_if<!has_insertion_operator<T >::value &&!ZORBA_HAS_C_STR(T)&&!has_str< T, std::string(T::*)() const >::value &&has_toString< T, std::string(T::*)() const >::value, std::string >::type zorba::internal::ztd::to_string(T const &t)
Referenced by zorba::internal::diagnostic::parameters::operator,, to_string.
StringType::const_pointer zorba::internal::ztd::c_str(StringType const &s)
Referenced by zorba::os_error::get_err_string, zorba::internal::FixedQName< JSONiqErrorQName, char const * >::localname, zorba::internal::VariableQName< std::string >::localname, zorba::fs::make_absolute, zorba::internal::FixedQName< JSONiqErrorQName, char const * >::ns, zorba::internal::VariableQName< std::string >::ns, zorba::internal::FixedQName< JSONiqErrorQName, char const * >::prefix, zorba::internal::VariableQName< std::string >::prefix.
char const* zorba::internal::ztd::c_str(char const *s)
std::enable_if<!ZORBA_TR1_NS::is_array<T>::value && !ZORBA_TR1_NS::is_pointer<T>::value && has_insertion_operator<T>::value, std::string>::type zorba::internal::ztd::to_string(T const &t)
std::enable_if<ZORBA_TR1_NS::is_pointer<T>::value && !is_c_string<T>::value, std::string>::type zorba::internal::ztd::to_string(T p)
References to_string.
std::string zorba::internal::ztd::to_string(char const *s)
std::string zorba::internal::ztd::to_string(unsigned char const *s)
zorba::internal::ztd::ZORBA_DECL_HAS_MEM_FN(c_str)
zorba::internal::ztd::ZORBA_DECL_HAS_MEM_FN(str)
zorba::internal::ztd::ZORBA_DECL_HAS_MEM_FN(toString)