zorba::hexbinary
decode_options
No options.
typedef size_t zorba::hexbinary::size_type
bool zorba::hexbinary::attach(std::basic_ios< charT, Traits > &ios)
Attaches a hexbinary::streambuf to a stream.
Unlike using a hexbinary::streambuf directly, this function will create the streambuf, attach it to the stream, and manage it for the lifetime of the stream automatically. ios The stream to attach the hexbinary::streambuf to. If the stream already has a hexbinary::streambuf attached to it, this function does nothing. true only if a hexbinary::streambuf was attached.
References zorba::internal::base64::alloc_streambuf, zorba::internal::base64::get_streambuf_index, zorba::internal::stream_callback.
Referenced by zorba::hexbinary::auto_attach< StreamType >::attach.
size_type zorba::hexbinary::decode(char const *from, size_type from_len, char *to, int options=dopt_none)
Decodes a hexBinary-encoded buffer.
from A pointer to the hexBinary buffer to be decoded. from_len The number of bytes to decode. to A pointer to the buffer to receive the decoded bytes. The buffer must be large enough to contain them. Note that the buffer is not null terminated. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered. decoded_size()
Referenced by decode, validate.
size_type zorba::hexbinary::decode(char const *from, size_type from_len, std::vector< char > *to, int options=dopt_none)
Decodes a hexBinary-encoded buffer and appends the decoded bytes onto a vector<char>.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the vector to append the encoded bytes appended onto. The vector is made large enough to contain the additional bytes. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
ZORBA_DLL_PUBLIC size_type zorba::hexbinary::decode(char const *from, size_type from_len, std::ostream &to, int options=dopt_none)
Decodes a hexBinary-encoded buffer and writes the decoded bytes to the given stream.
from A pointer to the hexBinary buffer to be decoded. from_len The number of bytes to decode. to The ostream to write the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::hexbinary::decode(char const *from, size_type from_len, ToStringType *to, int options=dopt_none)
Decodes a hexBinary-encoded buffer and appends the decoded bytes onto a string.
ToStringType The string type. from A pointer to the hexBinary buffer to be decoded. from_len The number of bytes to decode. to The string to append the decoded bytes to. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
References decode, decoded_size.
size_type zorba::hexbinary::decode(std::istream &from, std::ostream &to, int options=dopt_none)
Decodes a hexBinary-encoded istream.
from The istream to read from until EOF is reached. to The ostream to write the decoded bytes to. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::hexbinary::decode(std::istream &from, ToStringType *to, int options=dopt_none)
Decodes a hexBinary-encoded istream and appends the decoded bytes to a string.
ToStringType The string type. from The istream to read from until EOF is reached. to The string to append the decoded bytes to. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
References decode, dopt_ignore_ws, zorba::read_without_whitespace.
size_type zorba::hexbinary::decode(std::istream &from, std::vector< char > *to, int options=dopt_none)
Decodes a hexBinary-encoded stream and appends the decoded bytes onto a vector<char;>.
from The istream to read from until EOF is reached. to The string to append the decoded bytes to. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered.
size_type zorba::hexbinary::decoded_size(size_type n)
Calculates the number of bytes required to decode n hexBinary-encoded bytes.
n The number of bytes to decode. Returns the number of bytes needed for hexBinary decoding.
Referenced by decode.
bool zorba::hexbinary::detach(std::basic_ios< charT, Traits > &ios)
Detaches a previously attached hexbinary::streambuf from a stream.
The streambuf is destroyed and the stream's original streambuf is restored. ios The stream to detach the hexbinary::streambuf from. If the stream doesn't have a hexbinary::streambuf attached to it, this function does nothing. true only if a hexbinary::streambuf was detached.
References zorba::internal::dealloc_streambuf, zorba::internal::base64::get_streambuf_index.
size_type zorba::hexbinary::encode(char const *from, size_type from_len, char *to)
HexBinary-encodes a buffer.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the buffer to receive the encoded bytes. The buffer must be large enough to contain them. Note that the buffer is not null terminated. Returns the number of encoded bytes. encoded_size()
Referenced by encode.
size_type zorba::hexbinary::encode(char const *from, size_type from_len, std::vector< char > *to)
HexBinary-encodes a buffer and appends the encoded bytes onto a vector<char>.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the vector to append the encoded bytes appended onto. The vector is made large enough to contain the additional bytes.
ZORBA_DLL_PUBLIC size_type zorba::hexbinary::encode(char const *from, size_type from_len, std::ostream &to)
HexBinary-encodes a buffer and writes the encoded bytes to the given stream.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to The ostream to write the encoded bytes to. Returns the number of encoded bytes.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::hexbinary::encode(char const *from, size_type from_len, ToStringType *to)
HexBinary-encodes a buffer and appends the encoded bytes onto a string.
ToStringType The string type. from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the string to append the encoded bytes onto. Returns the number of encoded bytes.
References encode, encoded_size.
size_type zorba::hexbinary::encode(std::istream &from, std::ostream &to)
HexBinary-encodes one stream and write the encoded bytes to another.
from The istream to read from until EOF is reached. to The ostream to write the encoded bytes to.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::hexbinary::encode(std::istream &from, ToStringType *to)
Encodes a stream to hexBinary and appends the encoded bytes to a string.
ToStringType The string type. from The istream to read from until EOF is reached. to The string to append the encoded bytes to. Returns the number of encoded bytes.
References encode.
size_type zorba::hexbinary::encode(std::istream &from, std::vector< char > *to)
HexBinary-encodes a stream and appends the encoded bytes onto a vector<char;>.
from The istream to read from until EOF is reached. to The vector to append the encoded bytes to. Returns the number of encoded bytes.
size_type zorba::hexbinary::encoded_size(size_type n)
Calculates the number of bytes required to hexBinary-encode n bytes.
n The number of bytes to encode. Returns the number of bytes needed for hexBinary encoding.
Referenced by encode.
bool zorba::hexbinary::is_attached(std::basic_ios< charT, Traits > &ios)
Checks whether the given stream has a hexbinary::streambuf attached.
ios The stream to check. true only if a hexbinary::streambuf is attached.
References zorba::internal::hexbinary::get_streambuf_index.
void zorba::hexbinary::validate(char const *buf, size_type buf_len, int options=dopt_none)
Validates a hexBinary-encoded buffer.
buf A pointer to the hexBinary buffer to be validated. buf_len The number of bytes to validate. options The decoding options to use. invalid_argument if from_len (minus the amount of whitespace if options contains dopt_ignore_ws) is not a multiple of 2. hexbinary::exception if an invalid byte is encountered. decoded_size()
References decode.