zorba::base64
decode_options
No options.
typedef size_t zorba::base64::size_type
bool zorba::base64::attach(std::basic_ios< charT, Traits > &ios)
Attaches a base64::streambuf to a stream.
Unlike using a base64::streambuf directly, this function will create the streambuf, attach it to the stream, and manage it for the lifetime of the stream automatically. ios The stream to attach the base64::streambuf to. If the stream already has a base64::streambuf attached to it, this function does nothing. true only if a base64::streambuf was attached.
References zorba::internal::base64::alloc_streambuf, zorba::internal::base64::get_streambuf_index, zorba::internal::stream_callback.
Referenced by zorba::base64::auto_attach< StreamType >::attach.
ZORBA_DLL_PUBLIC size_type zorba::base64::decode(char const *from, size_type from_len, char *to, int options=dopt_none)
Decodes a Base64-encoded buffer.
Embedded newlines and carriage-returns are skipped. from A pointer to the Base64 buffer to be decoded. from_len The number of bytes to decode. to A pointer to the buffer to receive the decoded bytes. The buffer must be large enough to contain them. Note that the buffer is not null terminated. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dtop_any_len bit set and from_len is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered. decoded_size()
Referenced by decode, validate.
ZORBA_DLL_PUBLIC size_type zorba::base64::decode(char const *from, size_type from_len, std::vector< char > *to, int options=dopt_none)
Decodes a Base64-encoded buffer and appends the decoded bytes onto a vector<char>.
Embedded newlines and carriage-returns are skipped. from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the vector to append the encoded bytes appended onto. The vector is made large enough to contain the additional bytes. options The decoding options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
ZORBA_DLL_PUBLIC size_type zorba::base64::decode(char const *from, size_type from_len, std::ostream &to, int options=dopt_none)
Base64-decodes a buffer and writes the decoded bytes to the given stream.
from A pointer to the Base64 buffer to be decoded. from_len The number of bytes to decode. to The ostream to write the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::base64::decode(char const *from, size_type from_len, ToStringType *to, int options=dopt_none)
Decodes a Base64-encoded buffer and appends the decoded bytes onto a string.
Embedded newlines and carriage-returns are skipped. ToStringType The string type. from A pointer to the Base64 buffer to be decoded. from_len The number of bytes to decode. to The string to append the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
References decode, decoded_size.
std::enable_if<ZORBA_IS_STRING(FromStringType) && ZORBA_IS_STRING(ToStringType), size_type>::type zorba::base64::decode(FromStringType const &from, ToStringType *to)
Decodes a Base64-encoded string and appends the decoded bytes onto another string.
Embedded newlines and carriage-returns are skipped. FromStringType The from string type. ToStringType The to string type. from The Base64-encoded string to be decoded. to The string to append the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
References decode, zorba::locale::iso639_1::to.
ZORBA_DLL_PUBLIC size_type zorba::base64::decode(std::istream &from, std::ostream &to, int options=dopt_none)
Decodes a Base64-encoded istream.
Embedded newlines and carriage-returns are skipped. from The istream to read from until EOF is reached. to The ostream to write the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
std::enable_if<ZORBA_IS_STRING(FromStringType),size_type>::type zorba::base64::decode(FromStringType const &from, std::ostream &to)
Base64-decodes a string and writes the decoded bytes to a stream.
FromStringType The string type. from The string to be decoded. to The ostream to write the decoded bytes to. Returns the number of decoded bytes.
References encode, zorba::locale::iso639_1::to.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::base64::decode(std::istream &from, ToStringType *to, int options=dopt_none)
Decodes a Base64-encoded istream and appends the decoded bytes to a string.
Embedded newlines and carriage-returns are skipped. ToStringType The string type. from The istream to read from until EOF is reached. to The string to append the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
References decode, dopt_ignore_ws, zorba::read_without_whitespace.
ZORBA_DLL_PUBLIC size_type zorba::base64::decode(std::istream &from, std::vector< char > *to, int options=dopt_none)
Decodes a Base64-encoded stream and appends the decoded bytes onto a vector<char;>.
from The istream to read from until EOF is reached. to The string to append the decoded bytes to. options The options to use. Returns the number of decoded bytes. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes decoded is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered.
size_type zorba::base64::decoded_size(size_type n)
Calculates the number of bytes required to decode n Base64-encoded bytes.
n The number of bytes to decode. Returns the number of bytes needed for Base64 decoding.
Referenced by decode.
bool zorba::base64::detach(std::basic_ios< charT, Traits > &ios)
Detaches a previously attached base64::streambuf from a stream.
The streambuf is destroyed and the stream's original streambuf is restored. ios The stream to detach the base64::streambuf from. If the stream doesn't have a base64::streambuf attached to it, this function does nothing. true only if a base64::streambuf was detached.
References zorba::internal::dealloc_streambuf, zorba::internal::base64::get_streambuf_index.
ZORBA_DLL_PUBLIC size_type zorba::base64::encode(char const *from, size_type from_len, char *to)
Base64-encodes a buffer.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the buffer to receive the encoded bytes. The buffer must be large enough to contain them. Note that the buffer is not null terminated. Returns the number of encoded bytes. encoded_size()
Referenced by decode, encode.
ZORBA_DLL_PUBLIC size_type zorba::base64::encode(char const *from, size_type from_len, std::vector< char > *to)
Base64-encodes a buffer and appends the encoded bytes onto a vector<char>.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the vector to append the encoded bytes appended onto. The vector is made large enough to contain the additional bytes.
ZORBA_DLL_PUBLIC size_type zorba::base64::encode(char const *from, size_type from_len, std::ostream &to)
Base64-encodes a buffer and writes the encoded bytes to the given stream.
from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to The ostream to write the encoded bytes to. Returns the number of encoded bytes.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::base64::encode(char const *from, size_type from_len, ToStringType *to)
Base64-encodes a buffer and appends the encoded bytes onto a string.
ToStringType The string type. from A pointer to the buffer to be encoded. from_len The number of bytes to encode. to A pointer to the string to append the encoded bytes onto. Returns the number of encoded bytes.
References encode, encoded_size.
std::enable_if<ZORBA_IS_STRING(FromStringType) && ZORBA_IS_STRING(ToStringType), size_type>::type zorba::base64::encode(FromStringType const &from, ToStringType *to)
Base64-encodes a string and appends the encoded bytes onto another string.
FromStringType The from string type. ToStringType The to string type. from The string to be encoded. to A pointer to the string to append the encoded bytes onto. Returns the number of encoded bytes.
References encode, zorba::locale::iso639_1::to.
ZORBA_DLL_PUBLIC size_type zorba::base64::encode(std::istream &from, std::ostream &to)
Base64-encodes one stream and writes the encoded bytes to another.
from The istream to read from until EOF is reached. to The ostream to write the encoded bytes to. Returns the number of encoded bytes.
std::enable_if<ZORBA_IS_STRING(FromStringType),size_type>::type zorba::base64::encode(FromStringType const &from, std::ostream &to)
Base64-encodes a string and writes the encoded bytes to a stream.
FromStringType The string type. from The string to be encoded. to The ostream to write the encoded bytes to. Returns the number of encoded bytes.
References encode, zorba::locale::iso639_1::to.
std::enable_if<ZORBA_IS_STRING(ToStringType),size_type>::type zorba::base64::encode(std::istream &from, ToStringType *to)
Encodes a stream to Base64 and appends the encoded bytes to a string.
ToStringType The string type. from The istream to read from until EOF is reached. to The string to append the encoded bytes to. Returns the number of encoded bytes.
References encode.
ZORBA_DLL_PUBLIC size_type zorba::base64::encode(std::istream &from, std::vector< char > *to)
Base64-encodes a stream and appends the encoded bytes onto a vector<char;>.
from The istream to read from until EOF is reached. to The vector to append the encoded bytes to. Returns the number of encoded bytes.
size_type zorba::base64::encoded_size(size_type n)
Calculates the number of bytes required to Base64-encode n bytes.
n The number of bytes to encode. Returns the number of bytes needed for Base64 encoding.
Referenced by encode.
bool zorba::base64::is_attached(std::basic_ios< charT, Traits > &ios)
Checks whether the given stream has a base64::streambuf attached.
ios The stream to check. true only if a base64::streambuf is attached.
References zorba::internal::base64::get_streambuf_index.
void zorba::base64::validate(char const *buf, size_type buf_len, int options=dopt_none)
Validates a Base64-encoded buffer.
Embedded newlines and carriage-returns are skipped. buf A pointer to the Base64 buffer to be validated. buf_len The number of bytes to validate. options The options to use. invalid_argument if options does not have the dopt_any_len bit set and the number of Base64 bytes validated is not a multiple of 4. base64::exception if an = is encountered unexpectedly or an invalid byte is encountered. decoded_size()
References decode.