zorba::internal
typedef std::vector<Item> zorba::internal::error_object_type
typedef ztd::proxy<std::streambuf> zorba::internal::proxy_streambuf
class ZORBA_DLL_PUBLIC zorba::internal::VariableQName
ZORBA_DLL_PUBLIC void zorba::internal::dealloc_streambuf(std::streambuf *)
Referenced by zorba::hexbinary::detach, zorba::transcode::detach, zorba::base64::detach.
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, char const *ns, char const *prefix, char const *localname, char const *description, diagnostic::location const &loc, error_object_type *error_object=nullptr)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Error const &error, char const *description, diagnostic::location const &loc, error_object_type *error_object=nullptr)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Item const &error)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Error const &error)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Item const &error, String const &description)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Item const &error, String const &description, ItemSequence_t const &error_object)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Error const &error, String const &description, ItemSequence_t const &error_object)
ZORBA_DLL_PUBLIC UserException zorba::internal::make_user_exception(char const *raise_file, ZorbaException::line_type raise_line, Error const &error, String const &description, error_object_type *error_object=nullptr)
ZORBA_DLL_PUBLIC void zorba::internal::stream_callback(std::ios_base::event, std::ios_base &, int index)
Referenced by zorba::hexbinary::attach, zorba::transcode::attach, zorba::base64::attach.