zorba::uuid
typedef const_pointer zorba::uuid::const_iterator
typedef value_type const* zorba::uuid::const_pointer
typedef value_type const& zorba::uuid::const_reference
typedef std::ptrdiff_t zorba::uuid::difference_type
typedef pointer zorba::uuid::iterator
typedef value_type* zorba::uuid::pointer
typedef value_type& zorba::uuid::reference
typedef std::size_t zorba::uuid::size_type
typedef unsigned char zorba::uuid::value_type
variant
NCS backward compatibility.
version
value_type zorba::uuid::data[16][16]
The raw UUID data.
static void zorba::uuid::create(uuid *result)
Creates a UUID.
The variant and version of the UUID created is platform-dependent. result A pointer to the result.
iterator zorba::uuid::begin()
Creates an iterator to the beginning of the data.
Returns said iterator.
Referenced by zorba::operator<, zorba::operator==, swap.
const_iterator zorba::uuid::begin() const
Creates a const_iterator to the beginning of the data.
Returns said iterator.
iterator zorba::uuid::end()
Creates an iterator to one past the end of the data.
Returns said iterator.
Referenced by zorba::operator<, zorba::operator==.
const_iterator zorba::uuid::end() const
Creates a const_iterator to one past the end of the data.
Returns said iterator.
variant zorba::uuid::get_variant() const
Gets the variant of this UUID.
Returns said variant.
version zorba::uuid::get_version() const
Gets the version of this UUID.
Returns said version.
size_type zorba::uuid::size() const
Gets the size of the UUID data.
Always returns 16.
void zorba::uuid::swap(uuid &that)
Swaps this UUID's data with that of another.
that The other UUID to swap data with.
References begin.
Referenced by zorba::swap.