OPT=-g
SUFX=do
BUILD=Build

var_iterator : var_iterator.h var_iterator.cpp
	g++ -c ${OPT} -o var_iterator.${SUFX} var_iterator.cpp

iterators : iterators.h iterators.cpp
	g++ -c ${OPT} -o iterators.${SUFX} iterators.cpp

