SOURCES			= \
		batching.cpp \
		item_iterator.cpp \
    path_iterators.cpp \
		zorba.cpp \
		plan_visitor.cpp


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
