OPT=-g
SUFX=do
BUILD=Build

var_iterator : var_iterator.h var_iterator.cpp
	g++ -c ${OPT} -o var_iterator.${SUFX} var_iterator.cpp

binary_iterator : binary_iterator.h binary_iterator.cpp
	g++ -c ${OPT} -o binary_iterator.${SUFX} binary_iterator.cpp

