
SOURCES			= \
		item_iterator.cpp \
		zorba.cpp \
		plan_visitor.cpp


plan_visitor_test	= \
		../context/static_context.cpp \
		../context/dynamic_context.cpp \
		../dom/dom_namepool.cpp \
		../dom/dom_nodes.cpp \
		../dom/dom_qname.cpp \
		../dom/dom_xml_handler.cpp \
		../exprtree/expr.cpp \
		../exprtree/normalize_visitor.cpp \
		../functions/library.cpp \
		../functions/Boolean.cpp \
		../functions/BooleanImpl.cpp \
		../functions/Numerics.cpp \
		../functions/NumericsImpl.cpp \
		../functions/Sequences.cpp \
		../functions/SequencesImpl.cpp \
		../functions/Strings.cpp \
		../functions/StringsImpl.cpp \
		../functions/signature.cpp \
		../parser/parsenodes.cpp \
		../parser/xquery_parser.cpp \
		../parser/xquery_scanner.cpp \
		../parser/symbol_table.cpp \
		../parser/xquery_driver.cpp \
		../store/scan_handler.cpp \
		../store/uri_resolver.cpp \
		../store/xml_scanner.cpp \
		../store/zorba_uri_resolver.cpp \
		../types/sequence_type.cpp \
		../util/file.cpp \
		../util/fxcharheap.cpp \
		../util/mmfile.cpp \
		../util/tokenbuf.cpp \
		../util/URI.cpp \
		../values/primitive_values.cpp \
		../zorba/zorba_qname.cpp \
		../zorba/zorba_value_factory.cpp \
		../zorba/qnamerep.cpp \
		zorba.cpp \
		../errors/xqp_exception.cpp \
		../errors/errors.cpp \
		../errors/Error.cpp \
		item_iterator.cpp \
		plan_visitor.cpp \
		plan_visitor_test.cpp


BINARIES 		= plan_visitor_test


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
