<?xml version="1.0" encoding="UTF-8"?>
styles/main.css 
 styles/jquery.treeview.css 
 lib/jquery.js 
 lib/jquery.cookie.js 
 lib/jquery.treeview.js 
 lib/jquery.treeview.pack.js 
 lib/jquery.treeview.min.js 
 lib/shCore.js 
 lib/shBrushXQuery.js 
 lib/shBrushXml.js 
 styles/shCore.css 
 styles/shThemeDefault.css 
 styles/shThemeXQuery.css 
 ../../../../../html/index.html 
 images/zorba_logo.png 
 ../../../../../html/index.html 
 ../../../../../html/index.html 
 ../../../zorba/html/index.html 
 http://try.zorba-xquery.com 
 ../../../../../html/modules.html 
 ../../../../../html/downloads.html 
 ../../../../../html/tools.html 
 ../../../../../html/blog.html 
 ../../../../../html/code.html 
 index.html 
 function_index.html 
 www.w3.org_2005_xpath-functions_math.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.w3.org_2005_xpath-functions.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_datetime.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_math.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_random.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_string.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_schema.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_node.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_node-reference.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_dynamic_collections_ddl.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_dynamic_collections_dml.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_collections_dml.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_collections_ddl.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_dynamic_collections_w3c_ddl.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_dynamic_collections_w3c_dml.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_data-structures_unordered-map.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_dynamic_documents.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_indexes_ddl.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_indexes_dml.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_integrity_constraints_ddl.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_store_static_integrity_constraints_dml.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_introspection_sctx.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_reflection.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 expath.org_ns_file.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_fetch.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_http-client.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_process.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_system.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_xqdoc.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_project_xqdoc.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_xqdoc2xhtml_index.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_xqdoc2xhtml_error.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_data-cleaning_phonetic-string-similarity.html 
 www.zorba-xquery.com_modules_data-cleaning_hybrid-string-similarity.html 
 www.zorba-xquery.com_modules_data-cleaning_set-similarity.html 
 www.zorba-xquery.com_modules_data-cleaning_token-based-string-similarity.html 
 www.zorba-xquery.com_modules_data-cleaning_normalization.html 
 www.zorba-xquery.com_modules_data-cleaning_conversion.html 
 www.zorba-xquery.com_modules_data-cleaning_consolidation.html 
 www.zorba-xquery.com_modules_data-cleaning_character-based-string-similarity.html 
 www.zorba-xquery.com_modules_converters_base64.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_converters_csv.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_converters_html.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_converters_json.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_xml.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_xsl-fo.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_languages_xslt.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_excel_math.html 
 www.zorba-xquery.com_modules_excel_statistical.html 
 www.zorba-xquery.com_modules_excel_math-sumproduct.html 
 www.zorba-xquery.com_modules_excel_statistical-zorba.html 
 www.zorba-xquery.com_modules_excel_text.html 
 www.zorba-xquery.com_modules_excel_logical.html 
 www.zorba-xquery.com_modules_excel_information.html 
 www.zorba-xquery.com_modules_excel_errors.html 
 www.zorba-xquery.com_modules_excel_engineering.html 
 www.zorba-xquery.com_modules_excel_datetime.html 
 www.zorba-xquery.com_modules_excel_lookup.html 
 www.zorba-xquery.com_modules_cryptography_hash.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_cryptography_hmac.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_geoproj.html 
 expath.org_ns_geo.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_image_basic.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_image_graphviz.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_image_manipulation.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_image_paint.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_image_animation.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_oauth_error.html 
 www.zorba-xquery.com_modules_oauth_client.html 
 expath.org_ns_error.html 
 images/ZCsmall.gif 
 expath.org_ns_http-client.html 
 www.functx.com_index.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_modules_email_imap.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.zorba-xquery.com_modules_email_smtp.html 
 http://www.w3.org/TR/xquery-30/#dt-external-function 
 www.w3.org_2005_xqt-errors.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_errors.html 
 images/ZCsmall.gif 
 www.zorba-xquery.com_warnings.html 
 images/ZCsmall.gif 
 images/ZCsmall.gif 
 http://www.expath.org/spec/http-client 
 modules/www.zorba-xquery.com_modules_http-client.html 
 external_functions_impl/www.zorba-xquery.com_modules_http-client 
 expath.org_ns_error.html 
 schemas/expath.org_ns_http-client.html 
 http://curl.haxx.se/ 
 http://www.w3.org/TR/xquery-11/#FunctionDeclns 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #delete-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #get-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #get-binary-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #get-node-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #get-text-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #head-1 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #options-1 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #post-2 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #post-3 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #put-2 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #put-3 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #send-request-3 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 http://www.expath.org/spec/http-client 
 http://expath.org/modules/http-client.html#d2e483 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 http://expath.org/modules/http-client.html#d2e483 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 http://expath.org/modules/http-client.html#d2e483 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 http://expath.org/modules/http-client.html#d2e483 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 ../../html/options_and_annotations.html 
 images/Nondeterministic.gif 
 #function_summary 
 images/up.gif 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 http://xquery-scripting.ethz.ch/spec.html 
 images/Sequential.gif 
 #function_summary 
 images/up.gif 
 http://expath.org/modules/http-client.html#d2e483 
 http://disqus.com/?ref_noscript 
 http://disqus.com 
 http://flworfound.org/ 
 http://www.apache.org/licenses/LICENSE-2.0.html 
