
SOURCES 	= \
	itemstore.cpp \
	uri_resolver.cpp \
	zorba_uri_resolver.cpp \
#	collation_resolver.cpp \
	collection_resolver.cpp \
	module_resolver.cpp \
	schema_resolver.cpp \
	xml_term.cpp \
	scan_handler.cpp \
	xml_scanner.cpp


zorba_uri_resolver_test	= \
    ../runtime/zorba.cpp \
    ../util/xqp_exception.cpp \
    ../util/file.cpp \
    ../util/tokenbuf.cpp \
    ../util/URI.cpp \
    uri_resolver.cpp \
    zorba_uri_resolver.cpp \
	zorba_uri_resolver_test.cpp


collation_resolver_test	= \
    ../util/tokenbuf.cpp \
    ../util/URI.cpp \
    collation_resolver.cpp \
	collation_resolver_test.cpp


collection_resolver_test	= \
    ../util/tokenbuf.cpp \
    ../util/URI.cpp \
    collection_resolver.cpp \
	collection_resolver_test.cpp


module_resolver_test	= \
	../util/tokenbuf.cpp \
	../util/URI.cpp \
	module_resolver.cpp \
	module_resolver_test.cpp


schema_resolver_test	= \
    ../util/tokenbuf.cpp \
    ../util/URI.cpp \
    schema_resolver.cpp \
	schema_resolver_test.cpp


xml_handler_test	= \
	../context/context.cpp \
	../runtime/errors.cpp \
	../runtime/iterator.cpp \
	../types/sequence_type.cpp \
	../util/xqp_exception.cpp \
	../util/file.cpp \
	../util/mmfile.cpp \
	../util/fxcharheap.cpp \
	../util/URI.cpp \
	../util/tokenbuf.cpp \
	../values/values.cpp \
	../values/nodes.cpp \
	../values/xs_primitive_values.cpp \
	scan_handler.cpp \
	xml_scanner.cpp \
	xml_handler.cpp \
	qname_cache.cpp \
	itemstore.cpp \
	xml_handler_test.cpp



EXECUTABLES = zorba_uri_resolver_test collation_resolver_test collection_resolver_test \
	module_resolver_test schema_resolver_test xml_handler_test


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
