(jn:null(), 1, 2, jn:null()) = (4, jn:null(), 1, 6),
(jn:null(), 1, 2, jn:null()) < (4, jn:null(), 1, 6),
(jn:null(), 1, 2, jn:null()) > (4, jn:null(), 1, 6),
(jn:null(), 1, 2, jn:null()) <= (4, jn:null(), 1, 6),
(jn:null(), 1, 2, jn:null()) >= (4, jn:null(), 1, 6),
(jn:null(), 1, 2) = (3, 4, jn:null()),
(jn:null(), 3, 4) < (1, 2, jn:null()),
(jn:null(), 1, 2) > (3, 4, jn:null()),
(jn:null(), 3, 4) <= (1, 2, jn:null()),
(jn:null(), 1, 2) >= (3, 4, jn:null())
