
SOURCES 	= valuereps.cpp \
	qnamerep.cpp \
	nodereps.cpp \
	zorba_qname.cpp \
	zorba_nodes.cpp

EXECUTABLES = 


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
