<tokenizer-properties xmlns="http://www.zorba-xquery.com/modules/full-text" uri="http://www.zorba-xquery.com/full-text/tokenizer/icu">
  <comments-separate-tokens value="true"/>
  <elements-separate-tokens value="true"/>
  <processing-instructions-separate-tokens value="true"/>
  <supported-languages>
    <lang>af</lang>
    <lang>ak</lang>
    <lang>am</lang>
    <lang>ar</lang>
    <lang>as</lang>
    <lang>az</lang>
    <lang>be</lang>
    <lang>bg</lang>
    <lang>bm</lang>
    <lang>bn</lang>
    <lang>bo</lang>
    <lang>br</lang>
    <lang>bs</lang>
    <lang>ca</lang>
    <lang>cs</lang>
    <lang>cy</lang>
    <lang>da</lang>
    <lang>de</lang>
    <lang>ee</lang>
    <lang>el</lang>
    <lang>en</lang>
    <lang>eo</lang>
    <lang>es</lang>
    <lang>et</lang>
    <lang>eu</lang>
    <lang>fa</lang>
    <lang>ff</lang>
    <lang>fi</lang>
    <lang>fo</lang>
    <lang>fr</lang>
    <lang>ga</lang>
    <lang>gl</lang>
    <lang>gu</lang>
    <lang>gv</lang>
    <lang>ha</lang>
    <lang>he</lang>
    <lang>hi</lang>
    <lang>hr</lang>
    <lang>hu</lang>
    <lang>hy</lang>
    <lang>id</lang>
    <lang>ig</lang>
    <lang>ii</lang>
    <lang>is</lang>
    <lang>it</lang>
    <lang>ja</lang>
    <lang>ka</lang>
    <lang>ki</lang>
    <lang>kk</lang>
    <lang>kl</lang>
    <lang>km</lang>
    <lang>kn</lang>
    <lang>ko</lang>
    <lang>kw</lang>
    <lang>lg</lang>
    <lang>ln</lang>
    <lang>lt</lang>
    <lang>lu</lang>
    <lang>lv</lang>
    <lang>mg</lang>
    <lang>mk</lang>
    <lang>ml</lang>
    <lang>mr</lang>
    <lang>ms</lang>
    <lang>mt</lang>
    <lang>my</lang>
    <lang>nb</lang>
    <lang>nd</lang>
    <lang>ne</lang>
    <lang>nl</lang>
    <lang>nn</lang>
    <lang>om</lang>
    <lang>or</lang>
    <lang>pa</lang>
    <lang>pl</lang>
    <lang>ps</lang>
    <lang>pt</lang>
    <lang>rm</lang>
    <lang>rn</lang>
    <lang>ro</lang>
    <lang>ru</lang>
    <lang>rw</lang>
    <lang>sg</lang>
    <lang>si</lang>
    <lang>sk</lang>
    <lang>sl</lang>
    <lang>sn</lang>
    <lang>so</lang>
    <lang>sq</lang>
    <lang>sr</lang>
    <lang>sv</lang>
    <lang>sw</lang>
    <lang>ta</lang>
    <lang>te</lang>
    <lang>th</lang>
    <lang>ti</lang>
    <lang>to</lang>
    <lang>tr</lang>
    <lang>uk</lang>
    <lang>ur</lang>
    <lang>uz</lang>
    <lang>vi</lang>
    <lang>yo</lang>
    <lang>zh</lang>
    <lang>zu</lang>
  </supported-languages>
</tokenizer-properties>
