#!/bin/bash
# Copyright 2006-2008 The FLWOR Foundation.                                                             
#  
# Licensed under the Apache License, Version 2.0 (the "License");                                       
# you may not use this file except in compliance with the License.                                      
# You may obtain a copy of the License at
#  
# http://www.apache.org/licenses/LICENSE-2.0                                                            
#  
# Unless required by applicable law or agreed to in writing, software                                   
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                              
# See the License for the specific language governing permissions and
# limitations under the License.

# Mandatory vars: $ROOT, $SRC, $BUILD, $ZORBA
# Optional vars:  $BUILD_TYPE

test "$BUILD_TYPE" || export BUILD_TYPE="Debug"

rm -f $ZORBA

cd $BUILD

cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -DZORBA_WITH_REST=OFF $SRC
make -j 2

test -f $ZORBA || exit 1
