#!/bin/sh
echo Build failed, see build_log.txt
if test "x$SEND_MAIL" != "x"; then
    echo Sending e-mail
	  # echo "The Zorba build is broken at revision $REV; see attached build log." | mutt -x -s "Zorba build broken" -a build_log.txt `cat $ROOT/error_email.txt`
fi
