#!/usr/bin/perl

sub parse_test_file {
  my ($fname) = @_;
  open (my $fh1, $fname) or die ("$f1 not found");
  my $code=chomp $fh1;
  my $text = do { local ($/); <$fh1>; };

 return ($code, $text);
}

my $expected_dir=shift;
my $test_name=shift;

my $f1="$test_name/result.txt";
my $f2="$expected_dir/test_results/$test_name/result.txt";

my ($code1, $text1) = parse_test_file ($f1);
my ($code2, $text2) = parse_test_file ($f2);

print ("<failure test='$test_name'><code><actual>$code1</actual><expected>$code2</expected></code><text><actual>$text1</actual><expected>$text2</expected></text></failure>\n");
