#!/usr/bin/perl
use strict;
use File::Basename;

sub parse_test_file {
  my ($fname) = @_;
  my $fh1;
  open ($fh1, $fname) or die ("$fname not found");
  my $code=chomp $fh1;
  my $text = do { local ($/); <$fh1>; };

 return ($code, $text);
}

sub report_failure {
    my $expected_dir=shift;
    my $test_name=shift;
    
    my $f1="$test_name/result.txt";
    my $f2="$expected_dir/test_results/$test_name/result.txt";
    
    my ($code1, $text1) = parse_test_file ($f1);
    my ($code2, $text2) = parse_test_file ($f2);
    
    print ("<failure test='$test_name'><code><actual>$code1</actual><expected>$code2</expected></code><text><actual>$text1</actual><expected>$text2</expected></text></failure>\n");
}

my $test_dir = shift;
while (<>) {
    if (/^Files ([^ ]+) /) {
        report_failure ($test_dir, dirname $1);
    }
}
