#!/bin/sh
# Copyright 2006-2008 The FLWOR Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To run from inittab:
#zt:12345:respawn:nice -n -18 /usr/local/src/zorbatest_regressions/run_pending_tests >/var/log/zorbatest 2>&1

cd `dirname $0`
unalias -a
export PATH=/usr/local/bin:$PATH

while true; do
  rs=""
  while test -z "$rs"; do sleep 20; rs=`cd totest; ls`; done
  echo Revisions to test: $rs
  for r in $rs; do
    if test -f totest/$r; then
      /etc/init.d/crond stop >/dev/null 2>&1
      while ps ax | grep [r]un-parts; do sleep 30; done

      ./integrate --no-accept --rev $r --regress --no-clean server
      rm totest/$r

      /etc/init.d/crond start  >/dev/null 2>&1
      sleep 180
    fi
  done
done
