#!/bin/bash
# Copyright 2006-2008 The FLWOR Foundation.                                                             
#  
# Licensed under the Apache License, Version 2.0 (the "License");                                       
# you may not use this file except in compliance with the License.                                      
# You may obtain a copy of the License at
#  
# http://www.apache.org/licenses/LICENSE-2.0                                                            
#  
# Unless required by applicable law or agreed to in writing, software                                   
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.                              
# See the License for the specific language governing permissions and
# limitations under the License.
echo 'Enter saxon location (Cygwin users: use cygwin paths)'
read sax
echo '#!/bin/sh' >xquery
if which cygpath &>/dev/null; then
  JARS=`find $sax/ -name '*.jar'`; echo jars $JARS
  echo 'exec java -cp '"'"`for f in $JARS; do cygpath -w $f; done | tr '\n' ';'`."'"' net.sf.saxon.Query $*' >>xquery
else
  echo 'exec java -cp '`find $sax/ -name *.jar | tr '\n' :`.' net.sf.saxon.Query $*' >>xquery
fi
chmod u+x xquery
