<?xml version="1.0" encoding="UTF-8"?>
<root>
<t1>a<a/>b<a/>c<a/>d<a/>e</t1>
<t2><a/>ab<a/>c<a/>d<a/>e</t2>
<t3>a<a/>b<a/>c<a/>de<a/></t3>
<t4><a/>ab<a/>c<a/>de<a/></t4>
</root>
<text-nodes>16</text-nodes>
<root>
<t1>a<a/>b<a/>c<a/>d<a/>e</t1>
<t2><a/>ab<a/>c<a/>d<a/>e</t2>
<t3>a<a/>b<a/>c<a/>de<a/></t3>
<t4><a/>ab<a/>c<a/>de<a/></t4>
</root>
<text-nodes>16</text-nodes>
<root>
<t1>cde</t1>
<t2>ab</t2>
<t3>a<c/>de</t3>
<t4>ab<c/>e</t4>
</root>
<text-nodes>6</text-nodes>
<root>
<t1>a<a/>b<a/>c<a/>d<a/>e</t1></root>
<text-nodes>5</text-nodes>
