
SOURCES 	= \
	serializer.cpp 

serializer_test = \
	../runtime/batching.cpp \
	../runtime/item_iterator.cpp \
	../runtime/zorba.cpp \
	../functions/BooleanImpl.cpp \
	../types/sequence_type.cpp \
	../types/casting.cpp \
	../errors/Error.cpp \
	../errors/errors.cpp \
	../errors/xqp_exception.cpp \
	../store/api/item.cpp \
	../store/native/atomic_items.cpp \
	../store/native/node_items.cpp \
	../store/native/basic_item_factory.cpp \
	serializer.cpp \
	serializer_test.cpp

BINARIES	=  serializer_test


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules