/**
 * Copyright 2006-2011 The FLWOR Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
 /*
  * THIS FILE IS GENERATED.
  * PLEASE DO NOT EDIT.
  */
 
#ifndef ZORBA_DIAGNOSTIC_LIST_API_H
#define ZORBA_DIAGNOSTIC_LIST_API_H

#include <zorba/config.h>
#include <zorba/error.h>
#include <zorba/xquery_warning.h>

namespace zorba {

namespace err {

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPDY0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPTY0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0008;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0009;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0012;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0013;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0017;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPTY0018;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPTY0019;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPTY0020;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0022;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQTY0024;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0025;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0026;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0027;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQTY0030;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0031;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0032;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0033;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0034;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0035;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0036;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0038;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0039;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0040;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0041;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0044;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0045;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0046;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0047;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0048;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0049;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPDY0050;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0051;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0054;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0055;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0057;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0058;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0059;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0060;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0061;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0064;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0065;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0066;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0067;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0068;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0069;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0070;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0071;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0072;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0074;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0076;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0079;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0080;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0081;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XPST0083;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0084;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0085;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQTY0086;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0087;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0088;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0089;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0090;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0091;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0092;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0093;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQDY0096;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0098;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0106;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XQST0111;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XTDE1310;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XTDE1340;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XTDE1350;

#if !defined(ZORBA_NO_FULL_TEXT)
extern ZORBA_DLL_PUBLIC XQueryErrorCode FTST0008;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTST0009;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTDY0016;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTDY0017;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTST0018;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTST0019;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FTDY0020;
#endif

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOER0000;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOAR0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOAR0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCA0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCA0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCA0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCA0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCA0006;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCH0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCH0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCH0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOCH0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0006;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODC0007;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODF1280;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODF1310;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODT0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODT0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FODT0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOFI0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOFI0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FONS0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FONS0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0006;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0008;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORG0009;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORX0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORX0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORX0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FORX0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOTY0012;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOTY0013;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOTY0014;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOTY0015;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOUT1170;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOUT1190;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUST0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUST0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUST0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0006;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0007;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0008;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0009;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0010;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0011;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0012;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0013;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0014;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0015;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0016;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0017;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0018;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0019;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0021;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUTY0022;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0023;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0024;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0027;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUST0028;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0029;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0030;

extern ZORBA_DLL_PUBLIC XQueryErrorCode XUDY0031;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOUP0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode FOUP0002;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SENR0001;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0003;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SEPM0004;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0005;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0006;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SESU0007;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0008;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SEPM0009;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SEPM0010;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SESU0011;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0012;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SESU0013;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0014;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SERE0015;

extern ZORBA_DLL_PUBLIC XQueryErrorCode SEPM0016;

} // namespace err

namespace zerr {

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0000_NO_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0001_DYNAMIC_RUNTIME_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0002_ASSERT_FAILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0003_INTERNAL_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0004_NOT_IMPLEMENTED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0005_NOT_ENABLED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0006_UNKNOWN_ENCODING;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0007_FUNCTION_SIGNATURE_NOT_EQUAL;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0008_FUNCTION_IMPL_NOT_FOUND;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0009_FUNCTION_LOCALNAME_MISMATCH;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0010_FUNCTION_NOT_SEQUENTIAL;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0013_FXCHARHEAP_EXCEPTION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0016_RESERVED_MODULE_TARGET_NAMESPACE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0017_FILE_ACCESS_DISABLED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0020_INVALID_URI;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0021_USER_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0024_XML_DOES_NOT_MATCH_SCHEMA;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0025_ITEM_CREATION_FAILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0026_INVALID_ENUM_VALUE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0028_TARGET_NAMESPACE_NOT_PROVIDED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0029_URI_ACCESS_DENIED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0030_DEADLOCK;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0031_MALFORMED_XQUERYX_INPUT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0032_ERROR_TRANSFORMING_XQUERYX_TO_XQUERY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0036_BREAKITERATOR_CREATION_FAILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0037_INAPPROPRIATE_MODULE_VERSION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0038_INAPPROPRIATE_ZORBA_VERSION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0039_INVALID_VERSION_SPECIFICATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0040_MISSING_NONDETERMINISTIC_ANNOTATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0050_FEATURE_NOT_AVAILABLE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP0060_OPTION_NOT_KNOWN;

#if !defined(ZORBA_NO_FULL_TEXT)
extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP8401_THESAURUS_VERSION_MISMATCH;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP8402_THESAURUS_ENDIANNESS_MISMATCH;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQP8403_THESAURUS_DATA_ERROR;
#endif

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0001_PREFIX_NOT_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0002_DOCUMENT_NOT_VALID;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0003_INCONSISTENT_PARSE_FRAGMENT_OPTIONS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0004_INVALID_PARAMETER;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0005_INVALID_KEY_FOR_MAP;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZXQD0006_INVALID_UTF8_BYTE_SEQUENCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0002_XQUERY_COMPILATION_FAILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0003_XQUERY_NOT_COMPILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0004_XQUERY_ALREADY_COMPILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0005_XQUERY_ALREADY_EXECUTING;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0006_XQUERY_ALREADY_CLOSED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0007_CANNOT_SERIALIZE_PUL;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0008_NOT_AN_UPDATE_XQUERY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0009_XQUERY_NOT_COMPILED_IN_DEBUG_MODE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0011_ELEMENT_NOT_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0014_INVALID_ARGUMENT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0015_CREATEMODULE_NOT_FOUND;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0019_MODULE_ALREADY_REGISTERED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0020_DOCUMENT_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0021_ITEM_TO_LOAD_IS_NOT_NODE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0027_CANNOT_UPDATE_DCTX_WITH_ITERATORS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0028_INVALID_NODE_URI;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0029_REFERENCE_ALREADY_PRESENT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0030_NO_CURRENT_REFERENCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0039_XQUERY_HAS_ITERATOR_ALREADY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0040_ITERATOR_NOT_OPEN;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0041_ITERATOR_ALREADY_OPEN;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0042_ITERATOR_CLOSED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0070_INVALID_SERIALIZATION_METHOD_FOR_SAX;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0080_CANNOT_RETRIEVE_NODE_REFERENCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZAPI0090_CANNOT_VALIDATE_NON_ROOT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0001_NONEXISTENT_INPUT_FIELD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0002_INCOMPATIBLE_INPUT_FIELD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0003_UNRECOGNIZED_CLASS_FIELD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0004_UNRESOLVED_FIELD_REFERENCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0005_CLASS_VERSION_TOO_NEW;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0006_CLASS_VERSION_TOO_OLD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0007_INPUT_ARCHIVE_USED_FOR_OUT_SERIALIZATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0008_OUTPUT_ARCHIVE_USED_FOR_IN_SERIALIZATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0009_CLASS_NOT_SERIALIZABLE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0010_ITEM_TYPE_NOT_SERIALIZABLE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0011_INPUT_ARCHIVE_NOT_ZORBA_ARCHIVE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0012_INCOMPATIBLE_ARCHIVE_VERSION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0013_UNABLE_TO_LOAD_QUERY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0014_INFINITE_CIRCULAR_DEPENDENCIES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0015_INCOMPATIBLE_BETWEEN_32_AND_64_BITS_OR_LE_AND_BE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0016_CANNOT_LOAD_FROM_RELEASE_TO_DEBUG;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZCSE0017_CANNOT_LOAD_FROM_DEBUG_TO_RELEASE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0001_COLLECTION_NOT_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0002_COLLECTION_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0003_COLLECTION_DOES_NOT_EXIST;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0004_COLLECTION_CONST_UPDATE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0005_COLLECTION_APPEND_BAD_INSERT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0006_COLLECTION_QUEUE_BAD_INSERT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0007_COLLECTION_APPEND_BAD_DELETE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0008_COLLECTION_QUEUE_BAD_DELETE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0009_COLLECTION_QUEUE_BAD_DELETE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0010_COLLECTION_CONST_NODE_UPDATE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0011_COLLECTION_NODE_NOT_FOUND;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0012_COLLECTION_UNORDERED_BAD_OPERATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0013_COLLECTION_BAD_DESTROY_INDEXES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0014_COLLECTION_BAD_DESTROY_ICS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0015_COLLECTION_BAD_DESTROY_NODES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0016_COLLECTION_MULTIPLE_CREATES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0017_NODE_IS_ORPHAN;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0018_NODES_NOT_IN_SAME_COLLECTION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0019_UNDO_NOT_POSSIBLE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0020_INDEX_DOMAIN_NODE_NOT_IN_COLLECTION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0021_INDEX_NOT_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0022_INDEX_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0023_INDEX_DOES_NOT_EXIST;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0024_INDEX_UNIQUE_VIOLATION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0025_INDEX_WRONG_NUMBER_OF_PROBE_ARGS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0026_INDEX_RANGE_PROBE_NOT_ALLOWED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0027_INDEX_MULTIPLE_CREATES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0028_INDEX_DOMAIN_HAS_DUPLICATE_NODES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0029_INDEX_POINT_GENERAL_PROBE_NOT_ALLOWED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0030_INDEX_RANGE_GENERAL_PROBE_NOT_ALLOWED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0034_INDEX_RANGE_VALUE_PROBE_BAD_KEY_TYPES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0035_INDEX_GENERAL_INSERT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0031_IC_NOT_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0032_IC_NOT_ACTIVATED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDDY0033_IC_NOT_MET;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0001_COLLECTION_ALREADY_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0002_COLLECTION_ALREADY_IMPORTED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0003_COLLECTION_DECL_IN_MAIN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0004_COLLECTION_MULTIPLE_PROPERTY_VALUES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0006_COLLECTION_INVALID_PROPERTY_VALUE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0007_COLLECTION_DECL_IN_FOREIGN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0021_INDEX_ALREADY_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0022_INDEX_ALREADY_IMPORTED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0023_INDEX_DECL_IN_MAIN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0024_INDEX_MULTIPLE_PROPERTY_VALUES;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0025_INDEX_BAD_UNIQUE_PROPERTY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0026_INDEX_INVALID_PROPERTY_VALUE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0027_INDEX_BAD_KEY_TYPE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0028_INDEX_NOT_DETERMINISTIC;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0029_INDEX_INVALID_DATA_SOURCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0030_INDEX_NON_CONST_DATA_SOURCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0031_INDEX_HAS_FREE_VARS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0032_INDEX_REFERENCES_CTX_ITEM;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0033_INDEX_NON_SIMPLE_EXPR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0034_INDEX_CANNOT_DO_AUTOMATIC_MAINTENANCE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0035_INDEX_GENERAL_MULTIKEY;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0036_INDEX_DECL_IN_FOREIGN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0041_IC_ALREADY_DECLARED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0044_IC_DECL_IN_MAIN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0048_IC_DECL_IN_FOREIGN_MODULE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDST0060_FEATURE_NOT_SUPPORTED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDTY0001_COLLECTION_INVALID_NODE_TYPE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDTY0010_INDEX_DOMAIN_TYPE_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDTY0011_INDEX_KEY_TYPE_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZDTY0012_INDEX_KEY_TYPE_ERROR;

#if defined(ZORBA_WITH_DEBUGGER)
extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZGDB0001_CANNOT_CONNECT_TO_CLIENT;
#endif

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0001_FILE_NOT_FOUND;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0002_NOT_PLAIN_FILE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0003_STREAM_READ_FAILURE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0004_IO_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0005_DLL_LOAD_FAILED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZOSE0006_TRANSCODING_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0001_INDEX_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0002_INDEX_DOES_NOT_EXIST;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0003_INDEX_PARTIAL_KEY_INSERT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0004_INDEX_PARTIAL_KEY_REMOVE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0007_INDEX_UNSUPPORTED_PROBE_CONDITION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0008_COLLECTION_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0009_COLLECTION_NOT_FOUND;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0010_COLLECTION_NODE_ALREADY_IN_COLLECTION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0011_COLLECTION_NON_ROOT_NODE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0012_COLLECTION_ITEM_MUST_BE_A_NODE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0015_IC_ALREADY_EXISTS;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0016_IC_DOES_NOT_EXIST;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0020_LOADER_IO_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0021_LOADER_PARSING_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0030_NODEID_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0040_TYPE_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0041_NAN_COMPARISON;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0045_DUPLICATE_NODE_ERROR;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0050_FUNCTION_NOT_IMPLEMENTED_FOR_ITEMTYPE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0055_STREAMABLE_STRING_CONSUMED;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0060_RANGE_EXCEPTION;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZSTR0065_STRINGS_IN_POOL;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0001;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0002;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0003;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0004;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0005;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0006;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0007;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0008;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0009;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode XSST0010;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0001_ILLEGAL_CHARACTER;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0002_ILLEGAL_CODEPOINT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0003_ILLEGAL_ESCAPE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0004_ILLEGAL_LITERAL;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0005_ILLEGAL_NUMBER;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0006_UNEXPECTED_TOKEN;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0007_UNTERMINATED_STRING;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0008_ILLEGAL_QNAME;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJPE0009_ILLEGAL_EMPTY_STRING;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0001_NOT_DOCUMENT_OR_ELEMENT_NODE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0002_ELEMENT_MISSING_ATTRIBUTE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0003_BAD_ATTRIBUTE_VALUE;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0004_BAD_ELEMENT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0005_BAD_CHILD_ELEMENT;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0006_NO_ELEMENT_CHILD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0007_NO_TEXT_CHILD;

extern ZORBA_DLL_PUBLIC ZorbaErrorCode ZJSE0008_BAD_VALUE;

} // namespace zerr

namespace zwarn {

extern ZORBA_DLL_PUBLIC ZorbaWarningCode ZWST0002_UNKNOWN_ANNOTATION;

extern ZORBA_DLL_PUBLIC ZorbaWarningCode ZWST0003_FAKE_SEQUENTIAL_FUNCTION;

extern ZORBA_DLL_PUBLIC ZorbaWarningCode ZWST0004_AMBIGUOUS_SEQUENTIAL_FLWOR;

extern ZORBA_DLL_PUBLIC ZorbaWarningCode ZWST0005_CACHING_NOT_POSSIBLE;

extern ZORBA_DLL_PUBLIC ZorbaWarningCode ZWST0006_CACHING_MIGHT_NOT_BE_INTENDED;

} // namespace zwarn
} // namespace zorba
#endif /* ZORBA_DIAGNOSTIC_LIST_API_H */
/*
 * Local variables:
 * mode: c++
 * End:
 */ 
