(:
  Stress-test of the dataguide computation:
  worst-case scenario query for compilation time measurement
:)
jsoniq version "1.0";

import module namespace ddl = "http://www.zorba-xquery.com/modules/store/dynamic/collections/ddl";
import module namespace dml = "http://www.zorba-xquery.com/modules/store/dynamic/collections/dml";

ddl:create(xs:QName("sales"));
dml:insert-last(xs:QName("sales"), ({ "product" :  { "name" : "broiler" }}));

let $col := dml:collection(xs:QName("sales")) 
let $col2 := 
  ($col.cat1,
   $col.cat2,
   $col.cat3,
   $col.cat4,
   $col.cat5,
   $col.cat6,
   $col.cat7,
   $col.cat8,
   $col.cat9,
   $col.cat10)
   
return $col2.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category.
category.category.category.category.category.category.category.category.category.category
,
"done"
