#!/bin/bash
if valgrind --log-file-exactly=valgrind.log $ZORBA x.xq &> /dev/null && grep " 0 errors " valgrind.log >& /dev/null; then
  echo NO_ERRORS
else
  echo ERRORS
fi
test -f valgrind.log && chmod a+r valgrind.log
