#!/bin/sh
# Copyright 2006-2008 The FLWOR Foundation.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if test "$#" != "2"; then
    echo Args: dir1/LastTestsFailed.log[.gz] dir2/LastTestsFailed.log[.gz]
    exit 1
fi

TMP1=`mktemp /tmp/XXXXXX`

mycat()
{
  if test "`basename $1 .gz`" != "`basename $1`"; then zcat $1; else cat $1; fi
}

mycat $2 | cut -f2 -d: | sort >$TMP1

mycat $1 | cut -f2 -d: | sort | diff -U0 $TMP1 - | tail -n +3 | egrep -v '^@'

rm -f $TMP1
