#!/bin/bash

# $1 is the build directory
# $2 is test result file  in the build directory  
# $3 is the file to test
# $4 is the source directory of rbkt
# $5 is the reference result


if [ -f $2 ] # always delete the result file upfront
then
  rm -f $2
fi

if [ -f error.txt ] # always delete the result file upfront
then
  rm -f error.txt
fi


$1/test/apitest -q -r -o "$2" "$3" 2> error.txt # execute the query
RETURNVALUE=$?
if [ $RETURNVALUE -ne 0 ]
then
  if [ -s "error.txt" ] # contains an error message
  then
    mv "error.txt" "$2" # then make this error message to be the result
  else
    exit $RETURNVALUE # no error message but an error code => exit
  fi  
fi  

if [ -f $2 ] # if there was an error or no result file
then
  echo
  echo "Result"
  cat "$2"
  echo
  cat "$2" | "$4/Scripts/tidy_xmlfrag" > "$2.tidy" # tidy the generated result and store it in the build dir
  if [ -f "$4/$5" ]
  then
    cat "$4/$5" | "$4/Scripts/tidy_xmlfrag" > "$1/test/rbkt/$5.tidy"
    diff "$2.tidy" "$1/test/rbkt/$5.tidy" > "$1/test/rbkt/$5.diff"
    RETURNVALUE=$?
    if [ -s "$1/test/rbkt/$5.diff" ]
    then
      echo "Diff against expected result"
      cat "$1/test/rbkt/$5.diff"
    fi
    exit $RETURNVALUE
  else
    echo "reference result does not exist " "$4/$5"
    exit 1
  fi
else
  echo "result file does not exist " "$2"
  exit 2
fi
