#!/bin/bash

if test $# != 1 -o ! -d $1/test/zorbatest; then
 echo 'Arguments: zorba_repository'
 echo 'where zorba_repository is the top-level SVN working copy'
 exit 1
fi

SRC=$1
ZIP=/tmp/XQTS_1_0_2.zip
echo Downloading test suite to zip $ZIP ...
wget -c -O $ZIP http://www.w3.org/XML/Query/test-suite/XQTS_1_0_2.zip

d0=`pwd`

cd `dirname $SRC`
SRC=`pwd`/`basename $SRC`
echo Repository is at $SRC

d="/tmp/rwts.$$"
mkdir "$d"
cd "$d"

echo Unzipping test suite...
unzip $ZIP &>/dev/null

q=`mktemp /tmp/rwts.XXXXXX`
cat >$q <<"EOF"
declare default element namespace "http://www.w3.org/2005/02/query-test-XQTSCatalog";
declare option saxon:output "omit-xml-declaration=yes";
string-join ((
for $src in //source return concat ("%src ", $src/@ID, " ", $src/@FileName),
for $tc in //test-case
let $out := $tc/output-file[1]/text()
return string-join ((
$tc/@name, $tc/@FilePath, $tc/query/@name,
string-join (for $i in $tc/input-file return concat (data ($i/@variable), "=", $i/text ()), ":"),
if ($out) then $out else "",
$tc/expected-error[1]/text()
), " ")),
"
")
EOF

echo Cleaning up previous data...
rm -rf $SRC/test/rbkt/Queries/w3c_testsuite $SRC/test/rbkt/ExpQueryResults/w3c_testsuite $SRC/test/rbkt/TestSources

echo Processing catalog...
$SRC/test/zorbatest/xquery -s XQTSCatalog.xml $q | tee /tmp/xq-res.txt | perl -e '
use strict;
use File::Copy;

my $repo=shift;
my %sources;
while (<>) {
chomp;
if (m/^%src /) {
  my ($info, $id, $path) = split (/ /);
  $sources {$id} = $path;
  next;
}

my ($name, $path, $query, $inlist, $out, $err) = split (/ /);
my $inpath = "Queries/XQuery/$path";
my $dstqpath="$repo/test/rbkt/Queries/w3c_testsuite/$path";
`mkdir -p $dstqpath`;
my $dstrespath = "$repo/test/rbkt/ExpQueryResults/w3c_testsuite/$path";
my $fullout = "$dstrespath/$name.xml.res";
`mkdir -p $dstrespath`;

my @inbnd = split (/:/, $inlist);
if (@inbnd) {
  open (SPEC, ">$dstqpath/$name.spec");
  print SPEC "-x";
  foreach (@inbnd) {
    my ($var, $srcid) = split /=/;
    print SPEC " $var=$repo/test/rbkt/" . $sources {$srcid};
  }
  print SPEC "\n";
  close (SPEC);
}

copy ("$inpath/$query.xq", "$dstqpath/$name.xq");

if ($err) {
  open (RES, ">$fullout");
  print RES "$err\n";
  close (RES);
} else {
  copy ("ExpectedTestResults/$path/$out", $fullout);
}
}
' $SRC
rm -f $q

mv TestSources $SRC/test/rbkt/

echo "Cleaning up work directory..."
cd $d0; rm -rf "$d"

echo Done.
