#!/bin/bash

if test $# != 1; then
    echo Arguments: ZorbaRepo; exit 1
fi

SRC=$1
ZIP=/tmp/XQTS_1_0_2.zip
echo Downloading test suite to zip $ZIP ...
wget -c -O $ZIP http://www.w3.org/XML/Query/test-suite/XQTS_1_0_2.zip

d0=`pwd`

d="/tmp/rwts.$$"
mkdir "$d"
cd "$d"

echo Unzipping test suite...
unzip $ZIP &>/dev/null

echo Moving queries to Zorba repo...
mv Queries/XQuery $SRC/test/rbkt/Queries/w3c_testsuite

cd ExpectedTestResults
echo Cleaning up results...
find . -name '*.log' -exec rm {} \;
find . -type f -print0 | xargs -0 perl -e 'foreach (@ARGV) { my $was = $_; s/(.*)\.([a-zA-Z]+)/$1.xml.res/g; rename $was, $_; }'

echo Moving query results to Zorba repo...
mkdir $SRC/test/rbkt/ExpQueryResults/w3c_testsuite/
mv * $SRC/test/rbkt/ExpQueryResults/w3c_testsuite/

echo Done
cd $d0; rm -rf "$d"
