
SOURCES			= static_context.cpp dynamic_context.cpp 

context_test	= context_test.cpp

EXECUTABLES		= context_test


# Include global Makefile rules
ROOT_PATH		= ..
include $(ROOT_PATH)/Makefile.rules
