
SOURCES			= \
	rwlock.cpp \
	tokenbuf.cpp \
	hashfun_test.cpp \
	hashmap_test.cpp \
	file.cpp \
	tokenbuf_test.cpp \
	file_test.cpp \
	mmfile.cpp \
	fxarray_test.cpp \
	fxvector_test.cpp \
	fxcharheap.cpp \
	fxcharheap_test.cpp \
	fxhashmap_test.cpp \
	list_test.cpp \
	rchandle_test.cpp \
	sorter_test.cpp \
	utf8_encoder.cpp \
	URI.cpp


tokenbuf_test	= \
	../errors/xqp_exception.cpp \
	file.cpp \
	tokenbuf.cpp \
	tokenbuf_test.cpp

rwlock_test		= \
	rwlock.cpp \
	rwlock_test.cpp


hashfun_test	= \
	../errors/xqp_exception.cpp \
	hashfun_test.cpp


hashmap_test	= \
	../errors/xqp_exception.cpp \
	rwlock.cpp \
	tokenbuf.cpp \
	hashmap_test.cpp


list_test		= \
	list_test.cpp


logger_test		= \
	../errors/xqp_exception.cpp \
	logger.cpp \
	logger_test.cpp


rchandle_test	= \
	rchandle_test.cpp


sorter_test		= \
	sorter_test.cpp


URI_test		= \
	URI.cpp \
	URI_test.cpp


utf8_encoder_test	= \
	utf8_encoder.cpp \
	utf8_encoder_test.cpp


file_test 		= \
	../errors/xqp_exception.cpp \
	tokenbuf.cpp \
	file.cpp \
	file_test.cpp


mmfile_test		= \
	../errors/xqp_exception.cpp \
	tokenbuf.cpp \
	mmfile.cpp \
	mmfile_test.cpp


fxarray_test	= \
	../errors/xqp_exception.cpp \
	tokenbuf.cpp \
	mmfile.cpp \
	fxarray_test.cpp


fxvector_test	= \
	../errors/xqp_exception.cpp \
	tokenbuf.cpp \
	mmfile.cpp \
	fxvector_test.cpp


fxcharheap_test	= \
	../errors/xqp_exception.cpp \
	tokenbuf.cpp \
	mmfile.cpp \
	file.cpp \
	fxcharheap.cpp \
	fxcharheap_test.cpp


fxhashmap_test	= \
	../errors/xqp_exception.cpp \
	rwlock.cpp \
	tokenbuf.cpp \
	mmfile.cpp \
	file.cpp \
	fxcharheap.cpp \
	fxhashmap_test.cpp



#BINARIES	= tokenbuf_test rwlock_test hashfun_test hashmap_test \
#	list_test logger_test rchandle_test sorter_test URI_test \
#	utf8_encoder_test file_test mmfile_test fxarray_test \
#	fxvector_test fxcharheap_test fxhashmap_test 

BINARIES 	=

# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
