/*
 * Copyright 2006-2012 The FLWOR Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
 
// ******************************************
// *                                        *
// * THIS IS A GENERATED FILE. DO NOT EDIT! *
// * SEE .xml FILE WITH SAME NAME           *
// *                                        *
// ******************************************
#ifndef ZORBA_RUNTIME_PROFILE_VISITOR_H
#define ZORBA_RUNTIME_PROFILE_VISITOR_H
#include "common/common.h"
#include "runtime/visitors/planiter_visitor.h"
namespace zorba {
class PlanIterator;
class ProfileVisitor : public PlanIterVisitor {
private:
public:
  void do_something() const;

  void beginVisit( NodeNameIterator const& );
  void endVisit  ( NodeNameIterator const& );
  void beginVisit( NilledIterator const& );
  void endVisit  ( NilledIterator const& );
  void beginVisit( FnStringIterator const& );
  void endVisit  ( FnStringIterator const& );
  void beginVisit( FnDataIterator const& );
  void endVisit  ( FnDataIterator const& );
  void beginVisit( BaseUriIterator const& );
  void endVisit  ( BaseUriIterator const& );
  void beginVisit( DocumentUriIterator const& );
  void endVisit  ( DocumentUriIterator const& );
  void beginVisit( RootIterator const& );
  void endVisit  ( RootIterator const& );
  void beginVisit( ResolveUriIterator const& );
  void endVisit  ( ResolveUriIterator const& );
  void beginVisit( Base64DecodeIterator const& );
  void endVisit  ( Base64DecodeIterator const& );
  void beginVisit( Base64EncodeIterator const& );
  void endVisit  ( Base64EncodeIterator const& );
  void beginVisit( IsSameNodeIterator const& );
  void endVisit  ( IsSameNodeIterator const& );
  void beginVisit( NodeBeforeIterator const& );
  void endVisit  ( NodeBeforeIterator const& );
  void beginVisit( NodeAfterIterator const& );
  void endVisit  ( NodeAfterIterator const& );
  void beginVisit( ZorbaCreateCollectionIterator const& );
  void endVisit  ( ZorbaCreateCollectionIterator const& );
  void beginVisit( ZorbaDeleteCollectionIterator const& );
  void endVisit  ( ZorbaDeleteCollectionIterator const& );
  void beginVisit( IsAvailableCollectionIterator const& );
  void endVisit  ( IsAvailableCollectionIterator const& );
  void beginVisit( AvailableCollectionsIterator const& );
  void endVisit  ( AvailableCollectionsIterator const& );
  void beginVisit( FnCollectionIterator const& );
  void endVisit  ( FnCollectionIterator const& );
  void beginVisit( ZorbaCollectionIterator const& );
  void endVisit  ( ZorbaCollectionIterator const& );
  void beginVisit( ZorbaCollectionNameIterator const& );
  void endVisit  ( ZorbaCollectionNameIterator const& );
  void beginVisit( ZorbaIndexOfIterator const& );
  void endVisit  ( ZorbaIndexOfIterator const& );
  void beginVisit( ZorbaDeleteIterator const& );
  void endVisit  ( ZorbaDeleteIterator const& );
  void beginVisit( ZorbaDeleteFirstIterator const& );
  void endVisit  ( ZorbaDeleteFirstIterator const& );
  void beginVisit( ZorbaDeleteLastIterator const& );
  void endVisit  ( ZorbaDeleteLastIterator const& );
  void beginVisit( ZorbaEditIterator const& );
  void endVisit  ( ZorbaEditIterator const& );
  void beginVisit( ZorbaTruncateCollectionIterator const& );
  void endVisit  ( ZorbaTruncateCollectionIterator const& );
  void beginVisit( IsAvailableIndexIterator const& );
  void endVisit  ( IsAvailableIndexIterator const& );
  void beginVisit( AvailableIndexesIterator const& );
  void endVisit  ( AvailableIndexesIterator const& );
  void beginVisit( IsActivatedICIterator const& );
  void endVisit  ( IsActivatedICIterator const& );
  void beginVisit( ActivatedICsIterator const& );
  void endVisit  ( ActivatedICsIterator const& );
  void beginVisit( IsDeclaredCollectionIterator const& );
  void endVisit  ( IsDeclaredCollectionIterator const& );
  void beginVisit( DeclaredCollectionsIterator const& );
  void endVisit  ( DeclaredCollectionsIterator const& );
  void beginVisit( IsDeclaredIndexIterator const& );
  void endVisit  ( IsDeclaredIndexIterator const& );
  void beginVisit( DeclaredIndexesIterator const& );
  void endVisit  ( DeclaredIndexesIterator const& );
  void beginVisit( IsDeclaredICIterator const& );
  void endVisit  ( IsDeclaredICIterator const& );
  void beginVisit( DeclaredICsIterator const& );
  void endVisit  ( DeclaredICsIterator const& );
  void beginVisit( FnURICollectionIterator const& );
  void endVisit  ( FnURICollectionIterator const& );
  void beginVisit( CurrentDateTimeIterator const& );
  void endVisit  ( CurrentDateTimeIterator const& );
  void beginVisit( CurrentDateIterator const& );
  void endVisit  ( CurrentDateIterator const& );
  void beginVisit( CurrentTimeIterator const& );
  void endVisit  ( CurrentTimeIterator const& );
  void beginVisit( ImplicitTimezoneIterator const& );
  void endVisit  ( ImplicitTimezoneIterator const& );
  void beginVisit( DefaultCollationIterator const& );
  void endVisit  ( DefaultCollationIterator const& );
  void beginVisit( CsvParseIterator const& );
  void endVisit  ( CsvParseIterator const& );
  void beginVisit( CsvSerializeIterator const& );
  void endVisit  ( CsvSerializeIterator const& );
  void beginVisit( CurrentDate const& );
  void endVisit  ( CurrentDate const& );
  void beginVisit( CurrentDateTime const& );
  void endVisit  ( CurrentDateTime const& );
  void beginVisit( CurrentTime const& );
  void endVisit  ( CurrentTime const& );
  void beginVisit( MillisToDateTime const& );
  void endVisit  ( MillisToDateTime const& );
  void beginVisit( ParseDate const& );
  void endVisit  ( ParseDate const& );
  void beginVisit( ParseDateTime const& );
  void endVisit  ( ParseDateTime const& );
  void beginVisit( ParseTime const& );
  void endVisit  ( ParseTime const& );
  void beginVisit( Timestamp const& );
  void endVisit  ( Timestamp const& );
  void beginVisit( UTCOffset const& );
  void endVisit  ( UTCOffset const& );
#ifdef ZORBA_WITH_DEBUGGER
  void beginVisit( DebugIterator const& );
  void endVisit  ( DebugIterator const& );
#endif
  void beginVisit( YearsFromDurationIterator const& );
  void endVisit  ( YearsFromDurationIterator const& );
  void beginVisit( MonthsFromDurationIterator const& );
  void endVisit  ( MonthsFromDurationIterator const& );
  void beginVisit( DaysFromDurationIterator const& );
  void endVisit  ( DaysFromDurationIterator const& );
  void beginVisit( HoursFromDurationIterator const& );
  void endVisit  ( HoursFromDurationIterator const& );
  void beginVisit( MinutesFromDurationIterator const& );
  void endVisit  ( MinutesFromDurationIterator const& );
  void beginVisit( SecondsFromDurationIterator const& );
  void endVisit  ( SecondsFromDurationIterator const& );
  void beginVisit( YearFromDatetimeIterator const& );
  void endVisit  ( YearFromDatetimeIterator const& );
  void beginVisit( MonthFromDatetimeIterator const& );
  void endVisit  ( MonthFromDatetimeIterator const& );
  void beginVisit( DayFromDatetimeIterator const& );
  void endVisit  ( DayFromDatetimeIterator const& );
  void beginVisit( HoursFromDatetimeIterator const& );
  void endVisit  ( HoursFromDatetimeIterator const& );
  void beginVisit( MinutesFromDatetimeIterator const& );
  void endVisit  ( MinutesFromDatetimeIterator const& );
  void beginVisit( SecondsFromDatetimeIterator const& );
  void endVisit  ( SecondsFromDatetimeIterator const& );
  void beginVisit( TimezoneFromDatetimeIterator const& );
  void endVisit  ( TimezoneFromDatetimeIterator const& );
  void beginVisit( YearFromDateIterator const& );
  void endVisit  ( YearFromDateIterator const& );
  void beginVisit( MonthFromDateIterator const& );
  void endVisit  ( MonthFromDateIterator const& );
  void beginVisit( DayFromDateIterator const& );
  void endVisit  ( DayFromDateIterator const& );
  void beginVisit( TimezoneFromDateIterator const& );
  void endVisit  ( TimezoneFromDateIterator const& );
  void beginVisit( HoursFromTimeIterator const& );
  void endVisit  ( HoursFromTimeIterator const& );
  void beginVisit( MinutesFromTimeIterator const& );
  void endVisit  ( MinutesFromTimeIterator const& );
  void beginVisit( SecondsFromTimeIterator const& );
  void endVisit  ( SecondsFromTimeIterator const& );
  void beginVisit( TimezoneFromTimeIterator const& );
  void endVisit  ( TimezoneFromTimeIterator const& );
  void beginVisit( ErrorIterator const& );
  void endVisit  ( ErrorIterator const& );
  void beginVisit( TraceIterator const& );
  void endVisit  ( TraceIterator const& );
  void beginVisit( ReadLineIterator const& );
  void endVisit  ( ReadLineIterator const& );
  void beginVisit( PrintIterator const& );
  void endVisit  ( PrintIterator const& );
  void beginVisit( FunctionTraceIterator const& );
  void endVisit  ( FunctionTraceIterator const& );
  void beginVisit( FetchContentIterator const& );
  void endVisit  ( FetchContentIterator const& );
  void beginVisit( FetchContentBinaryIterator const& );
  void endVisit  ( FetchContentBinaryIterator const& );
  void beginVisit( FetchContentTypeIterator const& );
  void endVisit  ( FetchContentTypeIterator const& );
  void beginVisit( FnPutIterator const& );
  void endVisit  ( FnPutIterator const& );
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( CurrentCompareOptionsIterator const& );
  void endVisit  ( CurrentCompareOptionsIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( CurrentLangIterator const& );
  void endVisit  ( CurrentLangIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( HostLangIterator const& );
  void endVisit  ( HostLangIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( IsStemLangSupportedIterator const& );
  void endVisit  ( IsStemLangSupportedIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( IsStopWordIterator const& );
  void endVisit  ( IsStopWordIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( IsStopWordLangSupportedIterator const& );
  void endVisit  ( IsStopWordLangSupportedIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( IsThesaurusLangSupportedIterator const& );
  void endVisit  ( IsThesaurusLangSupportedIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( IsTokenizerLangSupportedIterator const& );
  void endVisit  ( IsTokenizerLangSupportedIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( StemIterator const& );
  void endVisit  ( StemIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( StripDiacriticsIterator const& );
  void endVisit  ( StripDiacriticsIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( ThesaurusLookupIterator const& );
  void endVisit  ( ThesaurusLookupIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( TokenizeNodeIterator const& );
  void endVisit  ( TokenizeNodeIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( TokenizeNodesIterator const& );
  void endVisit  ( TokenizeNodesIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( TokenizerPropertiesIterator const& );
  void endVisit  ( TokenizerPropertiesIterator const& );
#endif
#ifndef ZORBA_NO_FULL_TEXT
  void beginVisit( TokenizeStringIterator const& );
  void endVisit  ( TokenizeStringIterator const& );
#endif
  void beginVisit( FunctionLookupIterator const& );
  void endVisit  ( FunctionLookupIterator const& );
  void beginVisit( FunctionNameIterator const& );
  void endVisit  ( FunctionNameIterator const& );
  void beginVisit( FunctionArityIterator const& );
  void endVisit  ( FunctionArityIterator const& );
  void beginVisit( FnForEachPairIterator const& );
  void endVisit  ( FnForEachPairIterator const& );
  void beginVisit( FnFoldLeftIterator const& );
  void endVisit  ( FnFoldLeftIterator const& );
  void beginVisit( ActivateICIterator const& );
  void endVisit  ( ActivateICIterator const& );
  void beginVisit( DeactivateICIterator const& );
  void endVisit  ( DeactivateICIterator const& );
  void beginVisit( CheckICIterator const& );
  void endVisit  ( CheckICIterator const& );
  void beginVisit( IndexKeysIterator const& );
  void endVisit  ( IndexKeysIterator const& );
  void beginVisit( MemSizeIterator const& );
  void endVisit  ( MemSizeIterator const& );
  void beginVisit( JSONtoXMLInternal const& );
  void endVisit  ( JSONtoXMLInternal const& );
  void beginVisit( XMLtoJSONInternal const& );
  void endVisit  ( XMLtoJSONInternal const& );
  void beginVisit( JSONDecodeFromRoundtripIterator const& );
  void endVisit  ( JSONDecodeFromRoundtripIterator const& );
  void beginVisit( JSONEncodeForRoundtripIterator const& );
  void endVisit  ( JSONEncodeForRoundtripIterator const& );
  void beginVisit( JSONParseIterator const& );
  void endVisit  ( JSONParseIterator const& );
  void beginVisit( MultiObjectKeysIterator const& );
  void endVisit  ( MultiObjectKeysIterator const& );
  void beginVisit( SingleObjectKeysIterator const& );
  void endVisit  ( SingleObjectKeysIterator const& );
  void beginVisit( MultiObjectLookupIterator const& );
  void endVisit  ( MultiObjectLookupIterator const& );
  void beginVisit( SingleObjectLookupIterator const& );
  void endVisit  ( SingleObjectLookupIterator const& );
  void beginVisit( JSONObjectProjectIterator const& );
  void endVisit  ( JSONObjectProjectIterator const& );
  void beginVisit( JSONObjectTrimIterator const& );
  void endVisit  ( JSONObjectTrimIterator const& );
  void beginVisit( MultiArrayMembersIterator const& );
  void endVisit  ( MultiArrayMembersIterator const& );
  void beginVisit( SingleArrayMembersIterator const& );
  void endVisit  ( SingleArrayMembersIterator const& );
  void beginVisit( MultiArrayLookupIterator const& );
  void endVisit  ( MultiArrayLookupIterator const& );
  void beginVisit( SingleArrayLookupIterator const& );
  void endVisit  ( SingleArrayLookupIterator const& );
  void beginVisit( JSONArraySizeIterator const& );
  void endVisit  ( JSONArraySizeIterator const& );
  void beginVisit( JSONArrayFlattenIterator const& );
  void endVisit  ( JSONArrayFlattenIterator const& );
  void beginVisit( JSONNullIterator const& );
  void endVisit  ( JSONNullIterator const& );
  void beginVisit( JSONObjectInsertIterator const& );
  void endVisit  ( JSONObjectInsertIterator const& );
  void beginVisit( JSONArrayInsertIterator const& );
  void endVisit  ( JSONArrayInsertIterator const& );
  void beginVisit( JSONDeleteIterator const& );
  void endVisit  ( JSONDeleteIterator const& );
  void beginVisit( JSONReplaceValueIterator const& );
  void endVisit  ( JSONReplaceValueIterator const& );
  void beginVisit( JSONRenameIterator const& );
  void endVisit  ( JSONRenameIterator const& );
  void beginVisit( JSONArrayAppendIterator const& );
  void endVisit  ( JSONArrayAppendIterator const& );
  void beginVisit( JSONBoxIterator const& );
  void endVisit  ( JSONBoxIterator const& );
  void beginVisit( JSoundAnnotateIterator const& );
  void endVisit  ( JSoundAnnotateIterator const& );
  void beginVisit( JSoundValidateIterator const& );
  void endVisit  ( JSoundValidateIterator const& );
  void beginVisit( SqrtIterator const& );
  void endVisit  ( SqrtIterator const& );
  void beginVisit( ExpIterator const& );
  void endVisit  ( ExpIterator const& );
  void beginVisit( Exp10Iterator const& );
  void endVisit  ( Exp10Iterator const& );
  void beginVisit( LogIterator const& );
  void endVisit  ( LogIterator const& );
  void beginVisit( Log10Iterator const& );
  void endVisit  ( Log10Iterator const& );
  void beginVisit( SinIterator const& );
  void endVisit  ( SinIterator const& );
  void beginVisit( CosIterator const& );
  void endVisit  ( CosIterator const& );
  void beginVisit( TanIterator const& );
  void endVisit  ( TanIterator const& );
  void beginVisit( ArcSinIterator const& );
  void endVisit  ( ArcSinIterator const& );
  void beginVisit( ArcCosIterator const& );
  void endVisit  ( ArcCosIterator const& );
  void beginVisit( ArcTanIterator const& );
  void endVisit  ( ArcTanIterator const& );
  void beginVisit( Atan2Iterator const& );
  void endVisit  ( Atan2Iterator const& );
  void beginVisit( CoshIterator const& );
  void endVisit  ( CoshIterator const& );
  void beginVisit( AcoshIterator const& );
  void endVisit  ( AcoshIterator const& );
  void beginVisit( FmodIterator const& );
  void endVisit  ( FmodIterator const& );
  void beginVisit( LdexpIterator const& );
  void endVisit  ( LdexpIterator const& );
  void beginVisit( PowIterator const& );
  void endVisit  ( PowIterator const& );
  void beginVisit( SinhIterator const& );
  void endVisit  ( SinhIterator const& );
  void beginVisit( AsinhIterator const& );
  void endVisit  ( AsinhIterator const& );
  void beginVisit( TanhIterator const& );
  void endVisit  ( TanhIterator const& );
  void beginVisit( AtanhIterator const& );
  void endVisit  ( AtanhIterator const& );
  void beginVisit( PiNumberIterator const& );
  void endVisit  ( PiNumberIterator const& );
  void beginVisit( IsInfIterator const& );
  void endVisit  ( IsInfIterator const& );
  void beginVisit( IsNaNIterator const& );
  void endVisit  ( IsNaNIterator const& );
  void beginVisit( ModfIterator const& );
  void endVisit  ( ModfIterator const& );
  void beginVisit( FrexpIterator const& );
  void endVisit  ( FrexpIterator const& );
  void beginVisit( NodePositionIterator const& );
  void endVisit  ( NodePositionIterator const& );
  void beginVisit( IsAncestorPositionIterator const& );
  void endVisit  ( IsAncestorPositionIterator const& );
  void beginVisit( IsFollowingSiblingPositionIterator const& );
  void endVisit  ( IsFollowingSiblingPositionIterator const& );
  void beginVisit( IsFollowingPositionIterator const& );
  void endVisit  ( IsFollowingPositionIterator const& );
  void beginVisit( IsInSubtreeOfPositionIterator const& );
  void endVisit  ( IsInSubtreeOfPositionIterator const& );
  void beginVisit( IsDescendantPositionIterator const& );
  void endVisit  ( IsDescendantPositionIterator const& );
  void beginVisit( IsPrecedingSiblingPositionIterator const& );
  void endVisit  ( IsPrecedingSiblingPositionIterator const& );
  void beginVisit( IsPrecedingPositionIterator const& );
  void endVisit  ( IsPrecedingPositionIterator const& );
  void beginVisit( IsChildPositionIterator const& );
  void endVisit  ( IsChildPositionIterator const& );
  void beginVisit( IsAttributeOfPositionIterator const& );
  void endVisit  ( IsAttributeOfPositionIterator const& );
  void beginVisit( IsParentPositionIterator const& );
  void endVisit  ( IsParentPositionIterator const& );
  void beginVisit( IsPrecedingInDocumentOrderPositionIterator const& );
  void endVisit  ( IsPrecedingInDocumentOrderPositionIterator const& );
  void beginVisit( IsFollowingInDocumentOrderPositionIterator const& );
  void endVisit  ( IsFollowingInDocumentOrderPositionIterator const& );
  void beginVisit( LevelPositionIterator const& );
  void endVisit  ( LevelPositionIterator const& );
  void beginVisit( IsAttributePositionIterator const& );
  void endVisit  ( IsAttributePositionIterator const& );
  void beginVisit( IsCommentPositionIterator const& );
  void endVisit  ( IsCommentPositionIterator const& );
  void beginVisit( IsDocumentPositionIterator const& );
  void endVisit  ( IsDocumentPositionIterator const& );
  void beginVisit( IsElementPositionIterator const& );
  void endVisit  ( IsElementPositionIterator const& );
  void beginVisit( IsProcessingInstructionPositionIterator const& );
  void endVisit  ( IsProcessingInstructionPositionIterator const& );
  void beginVisit( IsTextPositionIterator const& );
  void endVisit  ( IsTextPositionIterator const& );
  void beginVisit( IsSiblingPositionIterator const& );
  void endVisit  ( IsSiblingPositionIterator const& );
  void beginVisit( InSameTreePositionIterator const& );
  void endVisit  ( InSameTreePositionIterator const& );
  void beginVisit( InCollectionPositionIterator const& );
  void endVisit  ( InCollectionPositionIterator const& );
  void beginVisit( InSameCollectionPositionIterator const& );
  void endVisit  ( InSameCollectionPositionIterator const& );
  void beginVisit( FnLocalNameIterator const& );
  void endVisit  ( FnLocalNameIterator const& );
  void beginVisit( FnNamespaceUriIterator const& );
  void endVisit  ( FnNamespaceUriIterator const& );
  void beginVisit( FnLangIterator const& );
  void endVisit  ( FnLangIterator const& );
  void beginVisit( FnHasChildrenIterator const& );
  void endVisit  ( FnHasChildrenIterator const& );
  void beginVisit( FnInnermostIterator const& );
  void endVisit  ( FnInnermostIterator const& );
  void beginVisit( FnOutermostIterator const& );
  void endVisit  ( FnOutermostIterator const& );
  void beginVisit( FnGenerateIdIterator const& );
  void endVisit  ( FnGenerateIdIterator const& );
  void beginVisit( IsAncestorIterator const& );
  void endVisit  ( IsAncestorIterator const& );
  void beginVisit( IsDescendantIterator const& );
  void endVisit  ( IsDescendantIterator const& );
  void beginVisit( IsParentIterator const& );
  void endVisit  ( IsParentIterator const& );
  void beginVisit( IsChildIterator const& );
  void endVisit  ( IsChildIterator const& );
  void beginVisit( IsFollowingIterator const& );
  void endVisit  ( IsFollowingIterator const& );
  void beginVisit( IsPrecedingIterator const& );
  void endVisit  ( IsPrecedingIterator const& );
  void beginVisit( IsFollowingSiblingIterator const& );
  void endVisit  ( IsFollowingSiblingIterator const& );
  void beginVisit( IsPrecedingSiblingIterator const& );
  void endVisit  ( IsPrecedingSiblingIterator const& );
  void beginVisit( LevelIterator const& );
  void endVisit  ( LevelIterator const& );
  void beginVisit( LeastCommonAncestor const& );
  void endVisit  ( LeastCommonAncestor const& );
  void beginVisit( FnPathIterator const& );
  void endVisit  ( FnPathIterator const& );
  void beginVisit( NodeCopyIterator const& );
  void endVisit  ( NodeCopyIterator const& );
  void beginVisit( AbsIterator const& );
  void endVisit  ( AbsIterator const& );
  void beginVisit( CeilingIterator const& );
  void endVisit  ( CeilingIterator const& );
  void beginVisit( FloorIterator const& );
  void endVisit  ( FloorIterator const& );
  void beginVisit( RoundIterator const& );
  void endVisit  ( RoundIterator const& );
  void beginVisit( RoundHalfToEvenIterator const& );
  void endVisit  ( RoundHalfToEvenIterator const& );
  void beginVisit( FormatNumberIterator const& );
  void endVisit  ( FormatNumberIterator const& );
  void beginVisit( FormatIntegerIterator const& );
  void endVisit  ( FormatIntegerIterator const& );
  void beginVisit( FnZorbaParseXmlFragmentIterator const& );
  void endVisit  ( FnZorbaParseXmlFragmentIterator const& );
  void beginVisit( FnZorbaCanonicalizeIterator const& );
  void endVisit  ( FnZorbaCanonicalizeIterator const& );
  void beginVisit( FnParseXmlFragmentIterator const& );
  void endVisit  ( FnParseXmlFragmentIterator const& );
  void beginVisit( FnParseXmlIterator const& );
  void endVisit  ( FnParseXmlIterator const& );
  void beginVisit( FnSerializeIterator const& );
  void endVisit  ( FnSerializeIterator const& );
  void beginVisit( ResolveQNameIterator const& );
  void endVisit  ( ResolveQNameIterator const& );
  void beginVisit( QNameIterator const& );
  void endVisit  ( QNameIterator const& );
  void beginVisit( QNameEqualIterator const& );
  void endVisit  ( QNameEqualIterator const& );
  void beginVisit( PrefixFromQNameIterator const& );
  void endVisit  ( PrefixFromQNameIterator const& );
  void beginVisit( LocalNameFromQNameIterator const& );
  void endVisit  ( LocalNameFromQNameIterator const& );
  void beginVisit( NamespaceUriFromQNameIterator const& );
  void endVisit  ( NamespaceUriFromQNameIterator const& );
  void beginVisit( NamespaceUriForPrefixIterator const& );
  void endVisit  ( NamespaceUriForPrefixIterator const& );
  void beginVisit( InScopePrefixesIterator const& );
  void endVisit  ( InScopePrefixesIterator const& );
  void beginVisit( SeededRandomIterator const& );
  void endVisit  ( SeededRandomIterator const& );
  void beginVisit( RandomIterator const& );
  void endVisit  ( RandomIterator const& );
  void beginVisit( UuidIterator const& );
  void endVisit  ( UuidIterator const& );
  void beginVisit( ReferenceIterator const& );
  void endVisit  ( ReferenceIterator const& );
  void beginVisit( HasReferenceIterator const& );
  void endVisit  ( HasReferenceIterator const& );
  void beginVisit( AssignReferenceIterator const& );
  void endVisit  ( AssignReferenceIterator const& );
  void beginVisit( DereferenceIterator const& );
  void endVisit  ( DereferenceIterator const& );
#ifndef ZORBA_NO_XMLSCHEMA
  void beginVisit( ValidateIterator const& );
  void endVisit  ( ValidateIterator const& );
#endif
  void beginVisit( ZorbaValidateInPlaceIterator const& );
  void endVisit  ( ZorbaValidateInPlaceIterator const& );
  void beginVisit( ZorbaSchemaTypeIterator const& );
  void endVisit  ( ZorbaSchemaTypeIterator const& );
  void beginVisit( ZorbaIsValidatedIterator const& );
  void endVisit  ( ZorbaIsValidatedIterator const& );
  void beginVisit( SctxBaseUriIterator const& );
  void endVisit  ( SctxBaseUriIterator const& );
  void beginVisit( SctxBoundarySpacePolicyIterator const& );
  void endVisit  ( SctxBoundarySpacePolicyIterator const& );
  void beginVisit( SctxConstructionModeIterator const& );
  void endVisit  ( SctxConstructionModeIterator const& );
  void beginVisit( SctxCopyNamespacesModeIterator const& );
  void endVisit  ( SctxCopyNamespacesModeIterator const& );
  void beginVisit( SctxDefaultCollationIterator const& );
  void endVisit  ( SctxDefaultCollationIterator const& );
  void beginVisit( SctxDefaultCollectionTypeIterator const& );
  void endVisit  ( SctxDefaultCollectionTypeIterator const& );
  void beginVisit( SctxDefaultFunctionNamespaceIterator const& );
  void endVisit  ( SctxDefaultFunctionNamespaceIterator const& );
  void beginVisit( SctxDefaultOrderIterator const& );
  void endVisit  ( SctxDefaultOrderIterator const& );
  void beginVisit( SctxFunctionAnnotationsIterator const& );
  void endVisit  ( SctxFunctionAnnotationsIterator const& );
  void beginVisit( SctxFunctionArgumentsCountIterator const& );
  void endVisit  ( SctxFunctionArgumentsCountIterator const& );
  void beginVisit( SctxFunctionNamesIterator const& );
  void endVisit  ( SctxFunctionNamesIterator const& );
  void beginVisit( SctxFunctionsIterator const& );
  void endVisit  ( SctxFunctionsIterator const& );
  void beginVisit( SctxInScopeAttributeDeclarationsIterator const& );
  void endVisit  ( SctxInScopeAttributeDeclarationsIterator const& );
  void beginVisit( SctxInScopeAttributeGroupsIterator const& );
  void endVisit  ( SctxInScopeAttributeGroupsIterator const& );
  void beginVisit( SctxInScopeElementDeclarationsIterator const& );
  void endVisit  ( SctxInScopeElementDeclarationsIterator const& );
  void beginVisit( SctxInScopeElementGroupsIterator const& );
  void endVisit  ( SctxInScopeElementGroupsIterator const& );
  void beginVisit( SctxInScopeSchemaTypesIterator const& );
  void endVisit  ( SctxInScopeSchemaTypesIterator const& );
  void beginVisit( SctxInscopeVariablesIterator const& );
  void endVisit  ( SctxInscopeVariablesIterator const& );
  void beginVisit( SctxOptionIterator const& );
  void endVisit  ( SctxOptionIterator const& );
  void beginVisit( SctxOrderingModeIterator const& );
  void endVisit  ( SctxOrderingModeIterator const& );
  void beginVisit( SctxStaticallyKnownCollationsIterator const& );
  void endVisit  ( SctxStaticallyKnownCollationsIterator const& );
  void beginVisit( SctxStaticallyKnownDocumentsIterator const& );
  void endVisit  ( SctxStaticallyKnownDocumentsIterator const& );
  void beginVisit( SctxStaticallyKnownDocumentTypeIterator const& );
  void endVisit  ( SctxStaticallyKnownDocumentTypeIterator const& );
  void beginVisit( SctxStaticallyKnownNamespaceBindingIterator const& );
  void endVisit  ( SctxStaticallyKnownNamespaceBindingIterator const& );
  void beginVisit( SctxStaticallyKnownNamespacesIterator const& );
  void endVisit  ( SctxStaticallyKnownNamespacesIterator const& );
  void beginVisit( SctxXPath10CompatModeIterator const& );
  void endVisit  ( SctxXPath10CompatModeIterator const& );
  void beginVisit( SeqValueIntersectIterator const& );
  void endVisit  ( SeqValueIntersectIterator const& );
  void beginVisit( SeqValueUnionIterator const& );
  void endVisit  ( SeqValueUnionIterator const& );
  void beginVisit( SeqValueExceptIterator const& );
  void endVisit  ( SeqValueExceptIterator const& );
  void beginVisit( FnConcatIterator const& );
  void endVisit  ( FnConcatIterator const& );
  void beginVisit( FnIndexOfIterator const& );
  void endVisit  ( FnIndexOfIterator const& );
  void beginVisit( FnEmptyIterator const& );
  void endVisit  ( FnEmptyIterator const& );
  void beginVisit( FnExistsIterator const& );
  void endVisit  ( FnExistsIterator const& );
  void beginVisit( FnDistinctValuesIterator const& );
  void endVisit  ( FnDistinctValuesIterator const& );
  void beginVisit( FnInsertBeforeIterator const& );
  void endVisit  ( FnInsertBeforeIterator const& );
  void beginVisit( FnRemoveIterator const& );
  void endVisit  ( FnRemoveIterator const& );
  void beginVisit( FnReverseIterator const& );
  void endVisit  ( FnReverseIterator const& );
  void beginVisit( FnSubsequenceIterator const& );
  void endVisit  ( FnSubsequenceIterator const& );
  void beginVisit( SubsequenceIntIterator const& );
  void endVisit  ( SubsequenceIntIterator const& );
  void beginVisit( SequencePointAccessIterator const& );
  void endVisit  ( SequencePointAccessIterator const& );
  void beginVisit( FnZeroOrOneIterator const& );
  void endVisit  ( FnZeroOrOneIterator const& );
  void beginVisit( FnOneOrMoreIterator const& );
  void endVisit  ( FnOneOrMoreIterator const& );
  void beginVisit( FnExactlyOneIterator const& );
  void endVisit  ( FnExactlyOneIterator const& );
  void beginVisit( FnDeepEqualIterator const& );
  void endVisit  ( FnDeepEqualIterator const& );
  void beginVisit( HashSemiJoinIterator const& );
  void endVisit  ( HashSemiJoinIterator const& );
  void beginVisit( SortSemiJoinIterator const& );
  void endVisit  ( SortSemiJoinIterator const& );
  void beginVisit( FnCountIterator const& );
  void endVisit  ( FnCountIterator const& );
  void beginVisit( FnAvgIterator const& );
  void endVisit  ( FnAvgIterator const& );
  void beginVisit( FnSumIterator const& );
  void endVisit  ( FnSumIterator const& );
  void beginVisit( FnSumDoubleIterator const& );
  void endVisit  ( FnSumDoubleIterator const& );
  void beginVisit( FnSumFloatIterator const& );
  void endVisit  ( FnSumFloatIterator const& );
  void beginVisit( FnSumDecimalIterator const& );
  void endVisit  ( FnSumDecimalIterator const& );
  void beginVisit( FnSumIntegerIterator const& );
  void endVisit  ( FnSumIntegerIterator const& );
  void beginVisit( OpToIterator const& );
  void endVisit  ( OpToIterator const& );
  void beginVisit( FnIdIterator const& );
  void endVisit  ( FnIdIterator const& );
  void beginVisit( FnElementWithIdIterator const& );
  void endVisit  ( FnElementWithIdIterator const& );
  void beginVisit( FnIdRefIterator const& );
  void endVisit  ( FnIdRefIterator const& );
  void beginVisit( FnDocIterator const& );
  void endVisit  ( FnDocIterator const& );
  void beginVisit( FnDocAvailableIterator const& );
  void endVisit  ( FnDocAvailableIterator const& );
  void beginVisit( FnAvailableEnvironmentVariablesIterator const& );
  void endVisit  ( FnAvailableEnvironmentVariablesIterator const& );
  void beginVisit( FnEnvironmentVariableIterator const& );
  void endVisit  ( FnEnvironmentVariableIterator const& );
  void beginVisit( FnUnparsedTextIterator const& );
  void endVisit  ( FnUnparsedTextIterator const& );
  void beginVisit( FnUnparsedTextAvailableIterator const& );
  void endVisit  ( FnUnparsedTextAvailableIterator const& );
  void beginVisit( FnUnparsedTextLinesIterator const& );
  void endVisit  ( FnUnparsedTextLinesIterator const& );
  void beginVisit( AvailableDocumentsIterator const& );
  void endVisit  ( AvailableDocumentsIterator const& );
  void beginVisit( IsAvailableDocumentIterator const& );
  void endVisit  ( IsAvailableDocumentIterator const& );
  void beginVisit( PutDocumentIterator const& );
  void endVisit  ( PutDocumentIterator const& );
  void beginVisit( RemoveDocumentIterator const& );
  void endVisit  ( RemoveDocumentIterator const& );
  void beginVisit( RetrieveDocumentIterator const& );
  void endVisit  ( RetrieveDocumentIterator const& );
  void beginVisit( MapCreateIterator const& );
  void endVisit  ( MapCreateIterator const& );
  void beginVisit( MapDropIterator const& );
  void endVisit  ( MapDropIterator const& );
  void beginVisit( MapGetIterator const& );
  void endVisit  ( MapGetIterator const& );
  void beginVisit( MapInsertIterator const& );
  void endVisit  ( MapInsertIterator const& );
  void beginVisit( MapDeleteIterator const& );
  void endVisit  ( MapDeleteIterator const& );
  void beginVisit( MapKeysIterator const& );
  void endVisit  ( MapKeysIterator const& );
  void beginVisit( MapSizeIterator const& );
  void endVisit  ( MapSizeIterator const& );
  void beginVisit( AvailableMapsIterator const& );
  void endVisit  ( AvailableMapsIterator const& );
  void beginVisit( MapOptionsIterator const& );
  void endVisit  ( MapOptionsIterator const& );
  void beginVisit( CodepointsToStringIterator const& );
  void endVisit  ( CodepointsToStringIterator const& );
  void beginVisit( StringToCodepointsIterator const& );
  void endVisit  ( StringToCodepointsIterator const& );
  void beginVisit( CompareStrIterator const& );
  void endVisit  ( CompareStrIterator const& );
  void beginVisit( CodepointEqualIterator const& );
  void endVisit  ( CodepointEqualIterator const& );
  void beginVisit( ConcatStrIterator const& );
  void endVisit  ( ConcatStrIterator const& );
  void beginVisit( StringJoinIterator const& );
  void endVisit  ( StringJoinIterator const& );
  void beginVisit( SubstringIterator const& );
  void endVisit  ( SubstringIterator const& );
  void beginVisit( SubstringIntOptIterator const& );
  void endVisit  ( SubstringIntOptIterator const& );
  void beginVisit( StringLengthIterator const& );
  void endVisit  ( StringLengthIterator const& );
  void beginVisit( NormalizeSpaceIterator const& );
  void endVisit  ( NormalizeSpaceIterator const& );
  void beginVisit( NormalizeUnicodeIterator const& );
  void endVisit  ( NormalizeUnicodeIterator const& );
  void beginVisit( UpperCaseIterator const& );
  void endVisit  ( UpperCaseIterator const& );
  void beginVisit( LowerCaseIterator const& );
  void endVisit  ( LowerCaseIterator const& );
  void beginVisit( TranslateIterator const& );
  void endVisit  ( TranslateIterator const& );
  void beginVisit( EncodeForUriIterator const& );
  void endVisit  ( EncodeForUriIterator const& );
  void beginVisit( IriToUriIterator const& );
  void endVisit  ( IriToUriIterator const& );
  void beginVisit( EscapeHtmlUriIterator const& );
  void endVisit  ( EscapeHtmlUriIterator const& );
  void beginVisit( ContainsIterator const& );
  void endVisit  ( ContainsIterator const& );
  void beginVisit( StartsWithIterator const& );
  void endVisit  ( StartsWithIterator const& );
  void beginVisit( EndsWithIterator const& );
  void endVisit  ( EndsWithIterator const& );
  void beginVisit( SubstringBeforeIterator const& );
  void endVisit  ( SubstringBeforeIterator const& );
  void beginVisit( SubstringAfterIterator const& );
  void endVisit  ( SubstringAfterIterator const& );
  void beginVisit( FnMatchesIterator const& );
  void endVisit  ( FnMatchesIterator const& );
  void beginVisit( FnReplaceIterator const& );
  void endVisit  ( FnReplaceIterator const& );
  void beginVisit( FnTokenizeIterator const& );
  void endVisit  ( FnTokenizeIterator const& );
  void beginVisit( FnAnalyzeStringIterator const& );
  void endVisit  ( FnAnalyzeStringIterator const& );
  void beginVisit( StringAnalyzeStringIterator const& );
  void endVisit  ( StringAnalyzeStringIterator const& );
  void beginVisit( StringMaterializeIterator const& );
  void endVisit  ( StringMaterializeIterator const& );
  void beginVisit( StringIsStreamableIterator const& );
  void endVisit  ( StringIsStreamableIterator const& );
  void beginVisit( StringIsSeekableIterator const& );
  void endVisit  ( StringIsSeekableIterator const& );
  void beginVisit( StringSplitIterator const& );
  void endVisit  ( StringSplitIterator const& );
  void beginVisit( DecodeURIIterator const& );
  void endVisit  ( DecodeURIIterator const& );
  void beginVisit( ParseURIIterator const& );
  void endVisit  ( ParseURIIterator const& );
  void beginVisit( SerializeURIIterator const& );
  void endVisit  ( SerializeURIIterator const& );
  void beginVisit( XQDocContentIterator const& );
  void endVisit  ( XQDocContentIterator const& );
};
} // namespace zorba
#endif
