<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res><cc1/></res><res><cc1/></res><res><cc1/></res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res><cc1/></res><res><cc1/></res><res><cc1/></res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
<res><cc1/></res><res><cc1/></res><res><cc1/></res>
<res>myCollection</res><res>myCollection</res><res>myCollection</res>
