/*
 * Copyright 2006-2008 The FLWOR Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

namespace zorba {

extern char const *const stop_words_es[] = {
  "a",
  "al",
  "algo",
  "algunas",
  "algunos",
  "ante",
  "antes",
  "como",
  "con",
  "contra",
  "cual",
  "cuando",
  "de",
  "del",
  "desde",
  "donde",
  "durante",
  "e",
  "el",
  "\xC3\xA9" "l",
  "ella",
  "ellas",
  "ellos",
  "en",
  "entre",
  "era",
  "erais",
  "\xC3\xA9" "ramos",
  "eran",
  "eras",
  "eres",
  "es",
  "esa",
  "esas",
  "ese",
  "eso",
  "esos",
  "esta",
  "est\xC3\xA1",
  "estaba",
  "estabais",
  "est\xC3\xA1" "bamos",
  "estaban",
  "estabas",
  "estad",
  "estada",
  "estadas",
  "estado",
  "estados",
  "est\xC3\xA1" "is",
  "estamos",
  "est\xC3\xA1" "n",
  "estando",
  "estar",
  "estar\xC3\xA1" "",
  "estar\xC3\xA1" "n",
  "estar\xC3\xA1" "s",
  "estar\xC3\xA9" "",
  "estar\xC3\xA9" "is",
  "estaremos",
  "estar\xC3\xAD" "a",
  "estar\xC3\xAD" "ais",
  "estar\xC3\xAD" "amos",
  "estar\xC3\xAD" "an",
  "estar\xC3\xAD" "as",
  "estas",
  "est\xC3\xA1" "s",
  "este",
  "est\xC3\xA9" "",
  "est\xC3\xA9" "is",
  "estemos",
  "est\xC3\xA9" "n",
  "est\xC3\xA9" "s",
  "esto",
  "estos",
  "estoy",
  "estuve",
  "estuviera",
  "estuvierais",
  "estuvi\xC3\xA9" "ramos",
  "estuvieran",
  "estuvieras",
  "estuvieron",
  "estuviese",
  "estuvieseis",
  "estuvi\xC3\xA9" "semos",
  "estuviesen",
  "estuvieses",
  "estuvimos",
  "estuviste",
  "estuvisteis",
  "estuvo",
  "fue",
  "fuera",
  "fuerais",
  "fu\xC3\xA9" "ramos",
  "fueran",
  "fueras",
  "fueron",
  "fuese",
  "fueseis",
  "fu\xC3\xA9" "semos",
  "fuesen",
  "fueses",
  "fui",
  "fuimos",
  "fuiste",
  "fuisteis",
  "ha",
  "hab\xC3\xA9" "is",
  "haber",
  "hab\xC3\xAD" "a",
  "hab\xC3\xAD" "ais",
  "hab\xC3\xAD" "amos",
  "hab\xC3\xAD" "an",
  "hab\xC3\xAD" "as",
  "habida",
  "habidas",
  "habido",
  "habidos",
  "habiendo",
  "habr\xC3\xA1" "",
  "habr\xC3\xA1" "n",
  "habr\xC3\xA1" "s",
  "habr\xC3\xA9" "",
  "habr\xC3\xA9" "is",
  "habremos",
  "habr\xC3\xAD" "a",
  "habr\xC3\xAD" "ais",
  "habr\xC3\xAD" "amos",
  "habr\xC3\xAD" "an",
  "habr\xC3\xAD" "as",
  "han",
  "has",
  "hasta",
  "hay",
  "haya",
  "hay\xC3\xA1" "is",
  "hayamos",
  "hayan",
  "hayas",
  "he",
  "hemos",
  "hube",
  "hubiera",
  "hubierais",
  "hubi\xC3\xA9" "ramos",
  "hubieran",
  "hubieras",
  "hubieron",
  "hubiese",
  "hubieseis",
  "hubi\xC3\xA9" "semos",
  "hubiesen",
  "hubieses",
  "hubimos",
  "hubiste",
  "hubisteis",
  "hubo",
  "la",
  "las",
  "le",
  "les",
  "lo",
  "los",
  "m\xC3\xA1" "s",
  "me",
  "mi",
  "m\xC3\xAD" "",
  "m\xC3\xAD" "a",
  "m\xC3\xAD" "as",
  "m\xC3\xAD" "o",
  "m\xC3\xAD" "os",
  "mis",
  "mucho",
  "muchos",
  "muy",
  "nada",
  "ni",
  "no",
  "nos",
  "nosotras",
  "nosotros",
  "nuestra",
  "nuestras",
  "nuestro",
  "nuestros",
  "o",
  "os",
  "otra",
  "otras",
  "otro",
  "otros",
  "para",
  "pero",
  "poco",
  "por",
  "porque",
  "que",
  "qu\xC3\xA9" "",
  "quien",
  "quienes",
  "se",
  "sea",
  "se\xC3\xA1" "is",
  "seamos",
  "sean",
  "seas",
  "ser",
  "ser\xC3\xA1" "",
  "ser\xC3\xA1" "n",
  "ser\xC3\xA1" "s",
  "ser\xC3\xA9" "",
  "ser\xC3\xA9" "is",
  "seremos",
  "ser\xC3\xAD" "a",
  "ser\xC3\xAD" "ais",
  "ser\xC3\xAD" "amos",
  "ser\xC3\xAD" "an",
  "ser\xC3\xAD" "as",
  "s\xC3\xAD" "",
  "sido",
  "siendo",
  "sin",
  "sobre",
  "sois",
  "somos",
  "son",
  "soy",
  "su",
  "sus",
  "suya",
  "suyas",
  "suyo",
  "suyos",
  "tambi\xC3\xA9" "n",
  "tanto",
  "te",
  "tendr\xC3\xA1" "",
  "tendr\xC3\xA1" "n",
  "tendr\xC3\xA1" "s",
  "tendr\xC3\xA9" "",
  "tendr\xC3\xA9" "is",
  "tendremos",
  "tendr\xC3\xAD" "a",
  "tendr\xC3\xAD" "ais",
  "tendr\xC3\xAD" "amos",
  "tendr\xC3\xAD" "an",
  "tendr\xC3\xAD" "as",
  "tened",
  "ten\xC3\xA9" "is",
  "tenemos",
  "tenga",
  "teng\xC3\xA1" "is",
  "tengamos",
  "tengan",
  "tengas",
  "tengo",
  "ten\xC3\xAD" "a",
  "ten\xC3\xAD" "ais",
  "ten\xC3\xAD" "amos",
  "ten\xC3\xAD" "an",
  "ten\xC3\xAD" "as",
  "tenida",
  "tenidas",
  "tenido",
  "tenidos",
  "teniendo",
  "ti",
  "tiene",
  "tienen",
  "tienes",
  "todo",
  "todos",
  "tu",
  "tú",
  "tus",
  "tuve",
  "tuviera",
  "tuvierais",
  "tuvi\xC3\xA9" "ramos",
  "tuvieran",
  "tuvieras",
  "tuvieron",
  "tuviese",
  "tuvieseis",
  "tuvi\xC3\xA9" "semos",
  "tuviesen",
  "tuvieses",
  "tuvimos",
  "tuviste",
  "tuvisteis",
  "tuvo",
  "tuya",
  "tuyas",
  "tuyo",
  "tuyos",
  "un",
  "una",
  "uno",
  "unos",
  "vosotras",
  "vosotros",
  "vuestra",
  "vuestras",
  "vuestro",
  "vuestros",
  "y",
  "ya",
  "yo",

  0
};

} // namespace zorba
/* vim:set et sw=2 ts=2: */
