xs:QName("fn:something"),
xs:anyURI("http://www.addr.ch"),
xs:untypedAtomic("atomic"),
xs:string("string"),
xs:decimal("2.3"), xs:decimal(2.3),
xs:int("3"), xs:int(3),
xs:integer("3"), xs:integer(3),
xs:double("3.23"), xs:double(3.23),
xs:float("3.23"), xs:float(3.23),
xs:boolean("true"), xs:boolean(true())
