#!/usr/bin/perl
# Copyright 2006-2008 The FLWOR Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Checks for common parser and lexer keyword/qname - related problems
# Usage: chk_kwqnames path/to/xquery_parser.y

use strict;
use warnings;

use File::Basename;

my $yfname = shift;
my $lfname = dirname ($yfname) . "/xquery_scanner.l";

my %ykwmap;
my %lkwmap;

print ("Parser: $yfname\nScanner: $lfname\n\n");

open YF, $yfname or die;
open LF, $lfname or die;

while (<YF>) {
    if (m@ *(\|)? *([A-Z0-9_]+) \{ *\$\$ *= *SYMTAB_PUT \(("[^"]+")\); *\} *$@) {
        # print "KW: $2 $3\n";
        my $tok = $2; my $kw = $3;
        $ykwmap {$tok} = $kw;
    }
}

while (<LF>) {
    if (m@^ *("[^"]+") *\{ *return token::([A-Z0-9_]+); *} *$@) {
        my $tok = $2; my $kw = $1;
        $lkwmap {$tok} = $kw;
        my $ykw = $ykwmap {$tok};
        if ($ykw && ! ($ykw eq $kw)) { print "$tok should be $kw as qname, is $ykw\n"; }
        if ($kw =~ m@"[a-zA-Z0-9_][a-zA-Z0-9_-]*"@ && ! $ykw) {
            print "Token $tok ($kw in lexer) not listed as qname in parser\n";
        }
    }
}

foreach my $tok (keys %ykwmap) {
    my $ykw = $ykwmap {$tok};
    if ($ykw =~ m@"[a-zA-Z0-9_][a-zA-Z0-9_-]*"@ && ! $lkwmap {$tok}) {
        print "Token $tok ($ykw in parser) not recognized in lexer\n";
    }
}
