#!/usr/bin/perl
# Copyright 2006-2008 The FLWOR Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;
use warnings;

my %hdr;

my $inc_path = "/usr/include";

sub process_file {
    my $fname = shift;
    if ($hdr {$fname}) {
        return;
    }
    $hdr {$fname} = 1;
    print ("$fname\n");
    my $result = open (my $fh, "$inc_path/$fname");
    if (! $result) {
        warn ("Could not find $fname");
        return;
    }
    while (<$fh>) {
        if (m@^[#]include [<"](boost/[^">]*)[>"]@) {
            process_file ($1);
        }
    }
    close $fh;
}

while (my $fname = shift) {
    process_file ($fname);
}
