#!/bin/sh

# Copyright 2006-2008 The FLWOR Foundation.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Creates emacs and vi TAGS / tags files
# Call with no arguments

files=`for dir in src include test/commons; do find $dir -name '*.cpp'; find $dir -name '*.h'; done; for dir in test test/rbkt test/update; do echo $dir/*.cpp $dir/*.h; done `

for prog in ctags etags; do
  $prog $files
done
