/*
 * Copyright 2006-2008 The FLWOR Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <zorba/error_list.h>

namespace zorba {
namespace err {

#define XQUERY_DEF_ERROR(ERR) XQueryError ERR( #ERR )

////////// XQuery Errors //////////////////////////////////////////////////////

XQUERY_DEF_ERROR( XPST0001 );
XQUERY_DEF_ERROR( XPDY0002 );
XQUERY_DEF_ERROR( XPST0003 );
XQUERY_DEF_ERROR( XPTY0004 );
XQUERY_DEF_ERROR( XPST0005 );
XQUERY_DEF_ERROR( XPST0008 );
XQUERY_DEF_ERROR( XQST0009 );
XQUERY_DEF_ERROR( XPST0010 );
XQUERY_DEF_ERROR( XQST0012 );
XQUERY_DEF_ERROR( XQST0013 );
XQUERY_DEF_ERROR( XQST0016 );
XQUERY_DEF_ERROR( XPST0017 );
XQUERY_DEF_ERROR( XPTY0018 );
XQUERY_DEF_ERROR( XPTY0019 );
XQUERY_DEF_ERROR( XPTY0020 );
XQUERY_DEF_ERROR( XQST0022 );
XQUERY_DEF_ERROR( XQTY0024 );
XQUERY_DEF_ERROR( XQDY0025 );
XQUERY_DEF_ERROR( XQDY0026 );
XQUERY_DEF_ERROR( XQDY0027 );
XQUERY_DEF_ERROR( XQTY0030 );
XQUERY_DEF_ERROR( XQST0031 );
XQUERY_DEF_ERROR( XQST0032 );
XQUERY_DEF_ERROR( XQST0033 );
XQUERY_DEF_ERROR( XQST0034 );
XQUERY_DEF_ERROR( XQST0035 );
XQUERY_DEF_ERROR( XQST0036 );
XQUERY_DEF_ERROR( XQST0038 );
XQUERY_DEF_ERROR( XQST0039 );
XQUERY_DEF_ERROR( XQST0040 );
XQUERY_DEF_ERROR( XQDY0041 );
XQUERY_DEF_ERROR( XQDY0044 );
XQUERY_DEF_ERROR( XQST0045 );
XQUERY_DEF_ERROR( XQST0046 );
XQUERY_DEF_ERROR( XQST0047 );
XQUERY_DEF_ERROR( XQST0048 );
XQUERY_DEF_ERROR( XQST0049 );
XQUERY_DEF_ERROR( XPDY0050 );
XQUERY_DEF_ERROR( XPST0051 );
XQUERY_DEF_ERROR( XQST0054 );
XQUERY_DEF_ERROR( XQST0055 );
XQUERY_DEF_ERROR( XQST0057 );
XQUERY_DEF_ERROR( XQST0058 );
XQUERY_DEF_ERROR( XQST0059 );
XQUERY_DEF_ERROR( XQST0060 );
XQUERY_DEF_ERROR( XQDY0061 );
XQUERY_DEF_ERROR( XQDY0064 );
XQUERY_DEF_ERROR( XQST0065 );
XQUERY_DEF_ERROR( XQST0066 );
XQUERY_DEF_ERROR( XQST0067 );
XQUERY_DEF_ERROR( XQST0068 );
XQUERY_DEF_ERROR( XQST0069 );
XQUERY_DEF_ERROR( XQST0070 );
XQUERY_DEF_ERROR( XQST0071 );
XQUERY_DEF_ERROR( XQDY0072 );
XQUERY_DEF_ERROR( XQDY0074 );
XQUERY_DEF_ERROR( XQST0075 );
XQUERY_DEF_ERROR( XQST0076 );
XQUERY_DEF_ERROR( XQST0079 );
XQUERY_DEF_ERROR( XPST0080 );
XQUERY_DEF_ERROR( XPST0081 );
XQUERY_DEF_ERROR( XPST0083 );
XQUERY_DEF_ERROR( XQDY0084 );
XQUERY_DEF_ERROR( XQST0085 );
XQUERY_DEF_ERROR( XQTY0086 );
XQUERY_DEF_ERROR( XQST0087 );
XQUERY_DEF_ERROR( XQST0088 );
XQUERY_DEF_ERROR( XQST0089 );
XQUERY_DEF_ERROR( XQST0090 );
XQUERY_DEF_ERROR( XQDY0091 );
XQUERY_DEF_ERROR( XQDY0092 );
XQUERY_DEF_ERROR( XQST0093 );
XQUERY_DEF_ERROR( XQDY0096 );
XQUERY_DEF_ERROR( XQST0097 );
XQUERY_DEF_ERROR( XQST0098 );
XQUERY_DEF_ERROR( XQST0106 );
XQUERY_DEF_ERROR( XQST0111 );

////////// XQuery Functions & Operators Errors ////////////////////////////////

XQUERY_DEF_ERROR( FOER0000 );
XQUERY_DEF_ERROR( FOAR0001 );
XQUERY_DEF_ERROR( FOAR0002 );
XQUERY_DEF_ERROR( FOCA0001 );
XQUERY_DEF_ERROR( FOCA0002 );
XQUERY_DEF_ERROR( FOCA0003 );
XQUERY_DEF_ERROR( FOCA0005 );
XQUERY_DEF_ERROR( FOCA0006 );
XQUERY_DEF_ERROR( FOCH0001 );
XQUERY_DEF_ERROR( FOCH0002 );
XQUERY_DEF_ERROR( FOCH0003 );
XQUERY_DEF_ERROR( FOCH0004 );
XQUERY_DEF_ERROR( FODC0001 );
XQUERY_DEF_ERROR( FODC0002 );
XQUERY_DEF_ERROR( FODC0003 );
XQUERY_DEF_ERROR( FODC0004 );
XQUERY_DEF_ERROR( FODC0005 );
XQUERY_DEF_ERROR( FODC0006 );
XQUERY_DEF_ERROR( FODC0007 );
XQUERY_DEF_ERROR( FODF1280 );
XQUERY_DEF_ERROR( FODF1310 );
XQUERY_DEF_ERROR( FODT0001 );
XQUERY_DEF_ERROR( FODT0002 );
XQUERY_DEF_ERROR( FODT0003 );
XQUERY_DEF_ERROR( FOFI0001 );
XQUERY_DEF_ERROR( FOFI0002 );
XQUERY_DEF_ERROR( FONS0004 );
XQUERY_DEF_ERROR( FONS0005 );
XQUERY_DEF_ERROR( FORG0001 );
XQUERY_DEF_ERROR( FORG0002 );
XQUERY_DEF_ERROR( FORG0003 );
XQUERY_DEF_ERROR( FORG0004 );
XQUERY_DEF_ERROR( FORG0005 );
XQUERY_DEF_ERROR( FORG0006 );
XQUERY_DEF_ERROR( FORG0008 );
XQUERY_DEF_ERROR( FORG0009 );
XQUERY_DEF_ERROR( FORX0001 );
XQUERY_DEF_ERROR( FORX0002 );
XQUERY_DEF_ERROR( FORX0003 );
XQUERY_DEF_ERROR( FORX0004 );
XQUERY_DEF_ERROR( FOTY0012 );
XQUERY_DEF_ERROR( FOTY0013 );
XQUERY_DEF_ERROR( FOTY0014 );
XQUERY_DEF_ERROR( FOTY0015 );

////////// XQuery Full-Text Errors ////////////////////////////////////////////

#ifndef ZORBA_NO_FULL_TEXT
XQUERY_DEF_ERROR( FTST0008 );
XQUERY_DEF_ERROR( FTST0009 );
XQUERY_DEF_ERROR( FTDY0016 );
XQUERY_DEF_ERROR( FTDY0017 );
XQUERY_DEF_ERROR( FTST0018 );
XQUERY_DEF_ERROR( FTST0019 );
XQUERY_DEF_ERROR( FTDY0020 );
#endif /* ZORBA_NO_FULL_TEXT */

////////// XQuery Update Facility /////////////////////////////////////////////

XQUERY_DEF_ERROR( XUST0001 );
XQUERY_DEF_ERROR( XUST0002 );
XQUERY_DEF_ERROR( XUST0003 );
XQUERY_DEF_ERROR( XUTY0004 );
XQUERY_DEF_ERROR( XUTY0005 );
XQUERY_DEF_ERROR( XUTY0006 );
XQUERY_DEF_ERROR( XUTY0007 );
XQUERY_DEF_ERROR( XUTY0008 );
XQUERY_DEF_ERROR( XUDY0009 );
XQUERY_DEF_ERROR( XUTY0010 );
XQUERY_DEF_ERROR( XUTY0011 );
XQUERY_DEF_ERROR( XUTY0012 );
XQUERY_DEF_ERROR( XUTY0013 );
XQUERY_DEF_ERROR( XUDY0014 );
XQUERY_DEF_ERROR( XUDY0015 );
XQUERY_DEF_ERROR( XUDY0016 );
XQUERY_DEF_ERROR( XUDY0017 );
XQUERY_DEF_ERROR( XUDY0018 );
XQUERY_DEF_ERROR( XUDY0019 );
XQUERY_DEF_ERROR( XUDY0020 );
XQUERY_DEF_ERROR( XUDY0021 );
XQUERY_DEF_ERROR( XUTY0022 );
XQUERY_DEF_ERROR( XUDY0023 );
XQUERY_DEF_ERROR( XUDY0024 );
XQUERY_DEF_ERROR( XUDY0025 );
XQUERY_DEF_ERROR( XUST0026 );
XQUERY_DEF_ERROR( XUDY0027 );
XQUERY_DEF_ERROR( XUST0028 );
XQUERY_DEF_ERROR( XUDY0029 );
XQUERY_DEF_ERROR( XUDY0030 );
XQUERY_DEF_ERROR( XUDY0031 );
XQUERY_DEF_ERROR( FOUP0001 );
XQUERY_DEF_ERROR( FOUP0002 );

////////// Serialization //////////////////////////////////////////////////////

XQUERY_DEF_ERROR( SENR0001 );
XQUERY_DEF_ERROR( SERE0003 );
XQUERY_DEF_ERROR( SEPM0004 );
XQUERY_DEF_ERROR( SERE0005 );
XQUERY_DEF_ERROR( SERE0006 );
XQUERY_DEF_ERROR( SESU0007 );
XQUERY_DEF_ERROR( SERE0008 );
XQUERY_DEF_ERROR( SEPM0009 );
XQUERY_DEF_ERROR( SEPM0010 );
XQUERY_DEF_ERROR( SESU0011 );
XQUERY_DEF_ERROR( SERE0012 );
XQUERY_DEF_ERROR( SESU0013 );
XQUERY_DEF_ERROR( SERE0014 );
XQUERY_DEF_ERROR( SERE0015 );
XQUERY_DEF_ERROR( SEPM0016 );
XQUERY_DEF_ERROR( XTDE1310 );
XQUERY_DEF_ERROR( XTDE1340 );
XQUERY_DEF_ERROR( XTDE1350 );

////////// Zorba Errors ///////////////////////////////////////////////////////

#define ZORBA_DEF_ERROR(QNAME,ERR) ZorbaError QNAME##_##ERR( #QNAME )

ZORBA_DEF_ERROR( XQP0000,NO_ERROR );
ZORBA_DEF_ERROR( XQP0001,DYNAMIC_RUNTIME_ERROR );
ZORBA_DEF_ERROR( XQP0002,DYNAMIC_ITERATOR_OVERRUN );
ZORBA_DEF_ERROR( XQP0003,DYNAMIC_ILLEGAL_NODE_CHILD );
ZORBA_DEF_ERROR( XQP0004,DYNAMIC_TARGET_NAMESPACE_NOT_FOUND );
ZORBA_DEF_ERROR( XQP0005,SYSTEM_NOT_SUPPORTED );
ZORBA_DEF_ERROR( XQP0006,SYSTEM_ASSERT_FAILED );
ZORBA_DEF_ERROR( XQP0007,SYSTEM_HASH_ERROR_KEYLEN_EXCEEDS_MAXKEYLEN );
ZORBA_DEF_ERROR( XQP0008,SYSTEM_VECTOR_OUT_OF_RANGE );
ZORBA_DEF_ERROR( XQP0009,SYSTEM_READ_LOCK_FAILED );
ZORBA_DEF_ERROR( XQP0010,SYSTEM_WRITE_LOCK_FAILED );
ZORBA_DEF_ERROR( XQP0011,SYSTEM_POP_FROM_EMPTY_LIST );
ZORBA_DEF_ERROR( XQP0012,SYSTEM_FILE_ERROR_IN_FUNCTION );
ZORBA_DEF_ERROR( XQP0013,SYSTEM_FXCHARHEAP_IOEXCEPTION );
ZORBA_DEF_ERROR( XQP0014,SYSTEM_MMFILE_IOEXCEPTION );
ZORBA_DEF_ERROR( XQP0015,SYSTEM_NOT_YET_IMPLEMENTED );
ZORBA_DEF_ERROR( XQP0016,RESERVED_MODULE_TARGET_NAMESPACE );
ZORBA_DEF_ERROR( XQP0017,FILE_ACCESS_DISABLED );
ZORBA_DEF_ERROR( XQP0019,INTERNAL_ERROR );
ZORBA_DEF_ERROR( XQP0020,INVALID_URI );
ZORBA_DEF_ERROR( XQP0021,USER_ERROR );
ZORBA_DEF_ERROR( XQP0022,GET_RESULTS_AS_DOM_FAILED );
ZORBA_DEF_ERROR( XQP0023,GET_RESULTS_AS_SAX_FAILED );
ZORBA_DEF_ERROR( XQP0024,XML_DOES_NOT_MATCH_SCHEMA );
ZORBA_DEF_ERROR( XQP0025,COULD_NOT_CREATE_ITEM );
ZORBA_DEF_ERROR( XQP0026,COULD_NOT_CREATE_THREAD );
ZORBA_DEF_ERROR( XQP0026,CANNOT_INIT_STORE );
ZORBA_DEF_ERROR( XQP0027,MS_DOM_ERROR );
ZORBA_DEF_ERROR( XQP0028,FUNCTION_IMPL_NOT_FOUND );
ZORBA_DEF_ERROR( XQP0029,MODULE_IMPORT_NOT_ALLOWED );
ZORBA_DEF_ERROR( XQP0030,DEADLOCK );
ZORBA_DEF_ERROR( XQP0031,MALFORMED_XQUERYX_INPUT );
ZORBA_DEF_ERROR( XQP0032,ERROR_TRANSFORMING_XQUERYX_TO_XQUERY );
ZORBA_DEF_ERROR( XQP0034,ILLEGAL_UTF8_BYTE );
ZORBA_DEF_ERROR( XQP0035,ILLEGAL_UTF16_BYTE );
ZORBA_DEF_ERROR( XQP0036,BREAKITERATOR_CREATION_FAILED );

#ifndef ZORBA_NO_FULL_TEXT
ZORBA_DEF_ERROR( XQP8401,THESAURUS_VERSION_MISMATCH );
ZORBA_DEF_ERROR( XQP8402,THESAURUS_DATA_ERROR );
#endif /* ZORBA_NO_FULL_TEXT */

ZORBA_DEF_ERROR( XQD0000,PREFIX_NOT_DECLARED );
ZORBA_DEF_ERROR( XQD0001,DOCUMENT_NOT_VALID );

////////// Zorba API Errors ///////////////////////////////////////////////////

ZORBA_DEF_ERROR( API0001,XQUERY_STRING_IS_EMPTY );
ZORBA_DEF_ERROR( API0002,XQUERY_COMPILATION_FAILED );
ZORBA_DEF_ERROR( API0003,XQUERY_NOT_COMPILED );
ZORBA_DEF_ERROR( API0004,XQUERY_ALREADY_COMPILED );
ZORBA_DEF_ERROR( API0005,XQUERY_ALREADY_EXECUTING );
ZORBA_DEF_ERROR( API0006,XQUERY_ALREADY_CLOSED );
ZORBA_DEF_ERROR( API0007,CANNOT_SERIALIZE_PUL );
ZORBA_DEF_ERROR( API0008,NOT_AN_UPDATE_XQUERY );
ZORBA_DEF_ERROR( API0009,XQUERY_NOT_COMPILED_IN_DEBUG_MODE );
ZORBA_DEF_ERROR( API0010,XQUERY_HAS_ITERATOR_ALREADY );
ZORBA_DEF_ERROR( API0040,ITERATOR_IS_NOT_OPEN );
ZORBA_DEF_ERROR( API0041,ITERATOR_IS_OPEN_ALREADY );
ZORBA_DEF_ERROR( API0042,ITERATOR_QUERY_IS_CLOSED );
ZORBA_DEF_ERROR( API0010,THREAD_NOT_INITIALIZED );
ZORBA_DEF_ERROR( API0011,INVALID_VARIABLE_QNAME );
ZORBA_DEF_ERROR( API0012,INVALID_INDEX );
ZORBA_DEF_ERROR( API0013,INAPPROPRIATE_VARIABLE_VALUE );
ZORBA_DEF_ERROR( API0014,INVALID_ARGUMENT );
ZORBA_DEF_ERROR( API0015,CANNOT_OPEN_FILE );
ZORBA_DEF_ERROR( API0016,CANNOT_CREATE_COLLECTION );
ZORBA_DEF_ERROR( API0017,CANNOT_LOAD_DOCUMENT );
ZORBA_DEF_ERROR( API0018,CANNOT_ACCESS_FILE );
ZORBA_DEF_ERROR( API0019,FUNCTION_ALREADY_REGISTERED );
ZORBA_DEF_ERROR( API0020,DOCUMENT_ALREADY_EXISTS );
ZORBA_DEF_ERROR( API0021,ITEM_TO_LOAD_IS_NOT_NODE );
ZORBA_DEF_ERROR( API0022,NOT_PLAIN_FILE );
ZORBA_DEF_ERROR( API0025,END_OF_SEQUENCE );
ZORBA_DEF_ERROR( API0027,CANNOT_UPDATE_DCTX_WITH_ITERATORS );
ZORBA_DEF_ERROR( API0028,INVALID_NODE_URI );
ZORBA_DEF_ERROR( API0030,NO_NODE_AT_GIVEN_POSITION );
ZORBA_DEF_ERROR( API0033,FILE_OR_FOLDER_DOES_NOT_EXIST );
ZORBA_DEF_ERROR( API0034,FILE_OR_FOLDER_CANNOT_BE_OPENED );
ZORBA_DEF_ERROR( API0035,COLLECTION_CANNOT_BE_SERIALIZED );
ZORBA_DEF_ERROR( API0050,REST_ERROR_HEADER );
ZORBA_DEF_ERROR( API0051,REST_ERROR_PAYLOAD );
ZORBA_DEF_ERROR( API0060,CONV_JSON_PARSE );
ZORBA_DEF_ERROR( API0061,CONV_JSON_SERIALIZE );
ZORBA_DEF_ERROR( API0062,CONV_JSON_PARAM );
ZORBA_DEF_ERROR( API0063,CONV_JSON_ML_PARSE );
ZORBA_DEF_ERROR( API0064,CONV_JSON_ML_SERIALIZE );
ZORBA_DEF_ERROR( API0065,CONV_JSON_ML_PARAM );
ZORBA_DEF_ERROR( API0066,JSON_SEQUENCE_CANNOT_BE_SERIALIZED );
ZORBA_DEF_ERROR( API0070,INVALID_SERIALIZATION_METHOD_FOR_SAX );

////////// Zorba Class Serialization Errors ///////////////////////////////////

ZORBA_DEF_ERROR( SRL0001,INEXISTENT_INPUT_FIELD );
ZORBA_DEF_ERROR( SRL0002,INCOMPATIBLE_INPUT_FIELD );
ZORBA_DEF_ERROR( SRL0003,UNRECOGNIZED_CLASS_FIELD );
ZORBA_DEF_ERROR( SRL0004,UNRESOLVED_FIELD_REFERENCE );
ZORBA_DEF_ERROR( SRL0005,CLASS_VERSION_IS_TOO_NEW );
ZORBA_DEF_ERROR( SRL0006,CLASS_VERSION_IS_TOO_OLD );
ZORBA_DEF_ERROR( SRL0007,INPUT_ARCHIVE_USED_FOR_OUT_SERIALIZATION );
ZORBA_DEF_ERROR( SRL0008,OUTPUT_ARCHIVE_USED_FOR_IN_SERIALIZATION );
ZORBA_DEF_ERROR( SRL0009,CLASS_NOT_SERIALIZABLE );
ZORBA_DEF_ERROR( SRL0010,ITEM_TYPE_NOT_SERIALIZABLE );
ZORBA_DEF_ERROR( SRL0011,INPUT_ARCHIVE_NOT_ZORBA_ARCHIVE );
ZORBA_DEF_ERROR( SRL0012,INCOMPATIBLE_ARCHIVE_VERSION );
ZORBA_DEF_ERROR( SRL0013,UNABLE_TO_LOAD_QUERY );
ZORBA_DEF_ERROR( SRL0014,INFINITE_CIRCULAR_DEPENDENCIES );
ZORBA_DEF_ERROR( SRL0015,INCOMPATIBLE_BETWEEN_32_AND_64_BITS_OR_LE_AND_BE );

////////// Store Errors ///////////////////////////////////////////////////////

ZORBA_DEF_ERROR( STR0001,INDEX_ALREADY_EXISTS );
ZORBA_DEF_ERROR( STR0002,INDEX_DOES_NOT_EXIST );
ZORBA_DEF_ERROR( STR0003,INDEX_PARTIAL_KEY_INSERT );
ZORBA_DEF_ERROR( STR0004,INDEX_PARTIAL_KEY_REMOVE );
ZORBA_DEF_ERROR( STR0005,INDEX_PARTIAL_KEY_PROBE );
ZORBA_DEF_ERROR( STR0006,INDEX_INVALID_BOX_PROBE );
ZORBA_DEF_ERROR( STR0007,INDEX_UNSUPPORTED_PROBE_CONDITION );
ZORBA_DEF_ERROR( STR0008,COLLECTION_ALREADY_EXISTS );
ZORBA_DEF_ERROR( STR0009,COLLECTION_NOT_FOUND );
ZORBA_DEF_ERROR( STR0010,COLLECTION_NODE_ALREADY_IN_COLLECTION );
ZORBA_DEF_ERROR( STR0011,COLLECTION_NON_ROOT_NODE );
ZORBA_DEF_ERROR( STR0012,COLLECTION_ITEM_MUST_BE_A_NODE );
ZORBA_DEF_ERROR( STR0015,IC_ALREADY_EXISTS );
ZORBA_DEF_ERROR( STR0016,IC_DOES_NOT_EXIST );
ZORBA_DEF_ERROR( STR0020,LOADER_IO_ERROR );
ZORBA_DEF_ERROR( STR0021,LOADER_PARSING_ERROR );
ZORBA_DEF_ERROR( STR0030,NODEID_ERROR );
ZORBA_DEF_ERROR( STR0040,TYPE_ERROR );
ZORBA_DEF_ERROR( STR0041,NAN_COMPARISON );
ZORBA_DEF_ERROR( STR0045,DUPLICATE_NODE_ERROR );
ZORBA_DEF_ERROR( STR0050,FUNCTION_NOT_IMPLEMENTED_FOR_ITEMTYPE );

////////// Data Definition Facility Errors ////////////////////////////////////

ZORBA_DEF_ERROR( XDST0001,COLLECTION_ALREADY_DECLARED );
ZORBA_DEF_ERROR( XDST0002,COLLECTION_ALREADY_IMPORTED );
ZORBA_DEF_ERROR( XDST0003,COLLECTION_DECL_IN_MAIN_MODULE );
ZORBA_DEF_ERROR( XDST0004,COLLECTION_MULTIPLE_PROPERTY_VALUES );
ZORBA_DEF_ERROR( XDST0005,COLLECTION_PROPERTIES_CONFLICT );
ZORBA_DEF_ERROR( XDST0006,COLLECTION_INVALID_PROPERTY_VALUE );
ZORBA_DEF_ERROR( XDST0007,COLLECTION_DECL_IN_FOREIGN_MODULE );
ZORBA_DEF_ERROR( XDST0021,INDEX_ALREADY_DECLARED );
ZORBA_DEF_ERROR( XDST0022,INDEX_ALREADY_IMPORTED );
ZORBA_DEF_ERROR( XDST0023,INDEX_DECL_IN_MAIN_MODULE );
ZORBA_DEF_ERROR( XDST0024,INDEX_MULTIPLE_PROPERTY_VALUES );
ZORBA_DEF_ERROR( XDST0025,INDEX_PROPERTIES_CONFLICT );
ZORBA_DEF_ERROR( XDST0026,INDEX_INVALID_PROPERTY_VALUE );
ZORBA_DEF_ERROR( XDST0027,INDEX_BAD_KEY_TYPE );
ZORBA_DEF_ERROR( XDST0028,INDEX_NOT_DETERMINISTIC );
ZORBA_DEF_ERROR( XDST0029,INDEX_INVALID_DATA_SOURCE );
ZORBA_DEF_ERROR( XDST0030,INDEX_NON_CONST_DATA_SOURCE );
ZORBA_DEF_ERROR( XDST0031,INDEX_HAS_FREE_VARS );
ZORBA_DEF_ERROR( XDST0032,INDEX_REFERENCES_CTX_ITEM );
ZORBA_DEF_ERROR( XDST0033,INDEX_NON_SIMPLE_EXPR );
ZORBA_DEF_ERROR( XDST0034,INDEX_CANNOT_DO_AUTOMATIC_MAINTENANCE );
ZORBA_DEF_ERROR( XDST0035,INDEX_GENERAL_MULTIKEY );
ZORBA_DEF_ERROR( XDST0036,INDEX_DECL_IN_FOREIGN_MODULE );
ZORBA_DEF_ERROR( XDST0041,IC_IS_ALREADY_DECLARED );
ZORBA_DEF_ERROR( XDST0042,MULTI_VALUED_IC_KEY );
ZORBA_DEF_ERROR( XDST0043,NON_ATOMIC_IC_KEY );
ZORBA_DEF_ERROR( XDST0044,IC_DECL_IN_MAIN_MODULE );
ZORBA_DEF_ERROR( XDST0045,IC_HAS_FREE_VARS );
ZORBA_DEF_ERROR( XDST0046,IC_HAS_INVALID_DATA_SOURCE );
ZORBA_DEF_ERROR( XDST0047,IC_NOT_DETERMINISTIC );
ZORBA_DEF_ERROR( XDST0048,IC_DECL_IN_FOREIGN_MODULE );

ZORBA_DEF_ERROR( XDTY0001,COLLECTION_INVALID_NODE_TYPE );
ZORBA_DEF_ERROR( XDTY0010,INDEX_DOMAIN_TYPE_ERROR );
ZORBA_DEF_ERROR( XDTY0011,INDEX_KEY_TYPE_ERROR );
ZORBA_DEF_ERROR( XDTY0012,INDEX_KEY_TYPE_ERROR );

ZORBA_DEF_ERROR( XDDY0001,COLLECTION_NOT_DECLARED );
ZORBA_DEF_ERROR( XDDY0002,COLLECTION_EXISTS_ALREADY );
ZORBA_DEF_ERROR( XDDY0003,COLLECTION_DOES_NOT_EXIST );
ZORBA_DEF_ERROR( XDDY0004,COLLECTION_CONST_UPDATE );
ZORBA_DEF_ERROR( XDDY0005,COLLECTION_APPEND_BAD_INSERT );
ZORBA_DEF_ERROR( XDDY0006,COLLECTION_QUEUE_BAD_INSERT );
ZORBA_DEF_ERROR( XDDY0007,COLLECTION_APPEND_BAD_DELETE );
ZORBA_DEF_ERROR( XDDY0008,COLLECTION_QUEUE_BAD_DELETE );
ZORBA_DEF_ERROR( XDDY0009,COLLECTION_QUEUE_BAD_DELETE );
ZORBA_DEF_ERROR( XDDY0010,COLLECTION_CONST_NODE_UPDATE );
ZORBA_DEF_ERROR( XDDY0011,COLLECTION_NODE_NOT_FOUND );
ZORBA_DEF_ERROR( XDDY0012,COLLECTION_UNORDERED_BAD_INSERT );
ZORBA_DEF_ERROR( XDDY0013,COLLECTION_BAD_DESTROY_INDEXES );
ZORBA_DEF_ERROR( XDDY0014,COLLECTION_BAD_DESTROY_ICS );
ZORBA_DEF_ERROR( XDDY0015,COLLECTION_BAD_DESTROY_NODES );
ZORBA_DEF_ERROR( XDDY0016,COLLECTION_MULTIPLE_CREATES );
ZORBA_DEF_ERROR( XDDY0020,INDEX_DOMAIN_NODE_NOT_IN_COLLECTION );
ZORBA_DEF_ERROR( XDDY0021,INDEX_IS_NOT_DECLARED );
ZORBA_DEF_ERROR( XDDY0022,INDEX_EXISTS_ALREADY );
ZORBA_DEF_ERROR( XDDY0023,INDEX_DOES_NOT_EXIST );
ZORBA_DEF_ERROR( XDDY0024,INDEX_UNIQUE_VIOLATION );
ZORBA_DEF_ERROR( XDDY0025,INDEX_WRONG_NUMBER_OF_PROBE_ARGS );
ZORBA_DEF_ERROR( XDDY0026,INDEX_RANGE_PROBE_NOT_ALLOWED );
ZORBA_DEF_ERROR( XDDY0027,INDEX_MULTIPLE_CREATES );
ZORBA_DEF_ERROR( XDDY0028,INDEX_DOMAIN_HAS_DUPLICATE_NODES );
ZORBA_DEF_ERROR( XDDY0029,INDEX_GENERAL_PROBE_NOT_ALLOWED );
ZORBA_DEF_ERROR( XDDY0031,IC_IS_NOT_DECLARED );
ZORBA_DEF_ERROR( XDDY0032,IC_IS_NOT_ACTIVATED );
ZORBA_DEF_ERROR( XDDY0033,IC_NOT_MET );

///////////////////////////////////////////////////////////////////////////////

} // namespace err
} // namespace zorba
/* vim:set et sw=2 ts=2: */
