// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_AttributesHolder__
#define __com_bluecast_xml_AttributesHolder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class AttributesHolder;
      }
    }
  }
  namespace org
  {
    namespace xml
    {
      namespace sax
      {
        class Attributes;
      }
    }
  }
}

class com::bluecast::xml::AttributesHolder : public ::java::lang::Object
{
public:
  void addAndCheckAttribute (::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *);
  AttributesHolder ();
  AttributesHolder (::org::xml::sax::Attributes *);
  jint getLength () { return length; }
  ::java::lang::String *getURI (jint);
  ::java::lang::String *getLocalName (jint);
  ::java::lang::String *getName (jint);
  ::java::lang::String *getQName (jint);
  ::java::lang::String *getType (jint);
  ::java::lang::String *getValue (jint);
  jint getIndex (::java::lang::String *, ::java::lang::String *);
  jint getIndex (::java::lang::String *);
  ::java::lang::String *getType (::java::lang::String *, ::java::lang::String *);
  ::java::lang::String *getType (::java::lang::String *);
  ::java::lang::String *getValue (::java::lang::String *, ::java::lang::String *);
  ::java::lang::String *getValue (::java::lang::String *);
  void clear ();
  void setAttributes (::org::xml::sax::Attributes *);
  void addAttribute (::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *);
  void setAttribute (jint, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *);
  void removeAttribute (jint);
  void setURI (jint, ::java::lang::String *);
  void setLocalName (jint, ::java::lang::String *);
  void setQName (jint, ::java::lang::String *);
  void setType (jint, ::java::lang::String *);
  void setValue (jint, ::java::lang::String *);
private:
  void ensureCapacity (jint);
  void badIndex (jint);
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  length;
  JArray< ::java::lang::String *> *data;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_AttributesHolder__ */
