// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_AttributeDefinition__
#define __com_bluecast_xml_AttributeDefinition__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class AttributeDefinition;
      }
    }
  }
}

class com::bluecast::xml::AttributeDefinition : public ::java::lang::Object
{
public:
  AttributeDefinition (::java::lang::String *, ::java::lang::String *, ::java::lang::String *, jint, JArray< ::java::lang::String *> *, jint, ::java::lang::String *);
  ::java::lang::String *getPrefix () { return prefix; }
  ::java::lang::String *getLocalName () { return localName; }
  ::java::lang::String *getQName () { return qName; }
  jint getValueType () { return valueType; }
  ::java::lang::String *getValueTypeString ();
  static ::java::lang::String *getValueTypeString (jint);
  jint getDefaultType () { return defaultType; }
  ::java::lang::String *getDefaultTypeString ();
  static ::java::lang::String *getDefaultTypeString (jint);
  ::java::lang::String *getDefaultValue () { return defaultValue; }
  JArray< ::java::lang::String *> *getPossibleValues () { return possibleValues; }
  static const jint IMPLIED = 1L;
  static const jint REQUIRED = 2L;
  static const jint FIXED = 3L;
  static const jint ENUMERATION = 1L;
  static const jint NOTATION = 2L;
  static const jint CDATA = 3L;
  static const jint ID = 4L;
  static const jint IDREF = 5L;
  static const jint IDREFS = 6L;
  static const jint ENTITY = 7L;
  static const jint ENTITIES = 8L;
  static const jint NMTOKEN = 9L;
  static const jint NMTOKENS = 10L;
private:
  static JArray< ::java::lang::String *> *valueTypeStrings;
  static JArray< ::java::lang::String *> *defaultTypeStrings;
public: // actually package-private
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object )))) prefix;
  ::java::lang::String *localName;
  ::java::lang::String *qName;
  jint valueType;
  jint defaultType;
  ::java::lang::String *defaultValue;
  JArray< ::java::lang::String *> *possibleValues;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_AttributeDefinition__ */
