// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_CharStringConverter__
#define __com_bluecast_util_CharStringConverter__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class CharStringConverter;
      }
    }
  }
}

class com::bluecast::util::CharStringConverter : public ::java::lang::Object
{
public:
  CharStringConverter (jint, jfloat);
  CharStringConverter ();
  CharStringConverter (jint);
  jint getCacheSize () { return numEntries; }
  ::java::lang::String *convert (jcharArray);
  ::java::lang::String *convert (jcharArray, jint, jint);
private:
  void rehash ();
public:
  void clearCache ();
private:
  static jboolean keysAreEqual (jcharArray, jint, jint, jcharArray, jint, jint);
  static jint hashKey (jcharArray, jint, jint);
  static const jfloat DEFAULT_LOAD = 0x1.666666p-1f;
  jfloat __attribute__((aligned(__alignof__( ::java::lang::Object ))))  loadFactor;
  jint numEntries;
  jint maxEntries;
  jint hashmask;
  JArray<jcharArray> * keys;
  JArray< ::java::lang::String *> *values;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_CharStringConverter__ */
