// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_DocumentBuilderFactory__
#define __javax_xml_parsers_DocumentBuilderFactory__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class DocumentBuilder;
        class DocumentBuilderFactory;
      }
    }
  }
}

class javax::xml::parsers::DocumentBuilderFactory : public ::java::lang::Object
{
public:  // actually protected
  DocumentBuilderFactory ();
public:
  static ::javax::xml::parsers::DocumentBuilderFactory *newInstance ();
  virtual ::javax::xml::parsers::DocumentBuilder *newDocumentBuilder () = 0;
  virtual void setNamespaceAware (jboolean);
  virtual void setValidating (jboolean);
  virtual void setIgnoringElementContentWhitespace (jboolean);
  virtual void setExpandEntityReferences (jboolean);
  virtual void setIgnoringComments (jboolean);
  virtual void setCoalescing (jboolean);
  virtual jboolean isNamespaceAware () { return namespaceAware; }
  virtual jboolean isValidating () { return validating; }
  virtual jboolean isIgnoringElementContentWhitespace () { return whitespace; }
  virtual jboolean isExpandEntityReferences () { return expandEntityRef; }
  virtual jboolean isIgnoringComments () { return ignoreComments; }
  virtual jboolean isCoalescing () { return coalescing; }
  virtual void setAttribute (::java::lang::String *, ::java::lang::Object *) = 0;
  virtual ::java::lang::Object *getAttribute (::java::lang::String *) = 0;
private:
  jboolean __attribute__((aligned(__alignof__( ::java::lang::Object ))))  validating;
  jboolean namespaceAware;
  jboolean whitespace;
  jboolean expandEntityRef;
  jboolean ignoreComments;
  jboolean coalescing;

  friend class javax_xml_parsers_FactoryFinder$ConfigurationError;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_DocumentBuilderFactory__ */
