// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_DocumentEntity__
#define __com_bluecast_xml_DocumentEntity__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class DocumentEntity;
        class XMLInputReader;
        class XMLReaderReader;
        class XMLStreamReader;
      }
    }
  }
  namespace org
  {
    namespace xml
    {
      namespace sax
      {
        class InputSource;
      }
    }
  }
  namespace java
  {
    namespace net
    {
      class URL;
    }
  }
}

class com::bluecast::xml::DocumentEntity : public ::java::lang::Object
{
public:
  DocumentEntity ();
  DocumentEntity (::java::lang::String *);
  DocumentEntity (::org::xml::sax::InputSource *);
  virtual jboolean isOpen () { return isOpen__; }
  virtual void open ();
  virtual ::java::lang::String *getDeclaredEncoding ();
  virtual jboolean isStandaloneDeclared ();
  virtual ::java::lang::String *getXMLVersion ();
  virtual void reset (::java::lang::String *);
  virtual void reset (::org::xml::sax::InputSource *);
  virtual void close ();
  virtual ::java::lang::String *getPublicID () { return 0; }
  virtual ::java::lang::String *getSystemID () { return sysID; }
  virtual jboolean isStandalone () { return isStandalone__; }
  virtual void setStandalone (jboolean);
  virtual jboolean isInternal ();
  virtual jboolean isParsed ();
  virtual ::java::io::Reader *getReader () { return reinterpret_cast< ::java::io::Reader *> (activeReader); }
  virtual ::java::lang::String *stringValue ();
  virtual jcharArray charArrayValue ();
private:
  jboolean __attribute__((aligned(__alignof__( ::java::lang::Object ))))  isOpen__;
  ::java::net::URL *url;
  ::java::lang::String *sysID;
  ::org::xml::sax::InputSource *source;
  static ::java::net::URL *defaultContext;
  jboolean isStandalone__;
  ::com::bluecast::xml::XMLStreamReader *streamReader;
  ::com::bluecast::xml::XMLReaderReader *readerReader;
  ::com::bluecast::xml::XMLInputReader *activeReader;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_DocumentEntity__ */
