// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_DuplicateKeyException__
#define __com_bluecast_util_DuplicateKeyException__

#pragma interface

#include <java/lang/Exception.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class DuplicateKeyException;
      }
    }
  }
}

class com::bluecast::util::DuplicateKeyException : public ::java::lang::Exception
{
public:
  DuplicateKeyException ();
  DuplicateKeyException (::java::lang::String *);

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_DuplicateKeyException__ */
