// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_ElementDefinition__
#define __com_bluecast_xml_ElementDefinition__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class IndexedObject;
      }
      namespace xml
      {
        class ElementDefinition;
        class AttributeDefinition;
      }
    }
  }
}

class com::bluecast::xml::ElementDefinition : public ::java::lang::Object
{
public:
  ElementDefinition ();
  ElementDefinition (::java::lang::String *);
  ::java::lang::String *getName () { return name; }
  void setName (::java::lang::String *);
  JArray< ::com::bluecast::xml::AttributeDefinition *> *getAttributes () { return attributes; }
  jint getAttributeCount () { return size; }
  ::com::bluecast::util::IndexedObject *getIndexedAttribute (::java::lang::String *);
  ::com::bluecast::xml::AttributeDefinition *getAttribute (jint);
  void addAttribute (::com::bluecast::xml::AttributeDefinition *);
public: // actually package-private
  ::java::lang::String * __attribute__((aligned(__alignof__( ::java::lang::Object )))) name;
  JArray< ::com::bluecast::xml::AttributeDefinition *> *attributes;
  ::java::util::Map *attributeMap;
  jint size;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_ElementDefinition__ */
