// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_Entity__
#define __com_bluecast_xml_Entity__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class Entity;
      }
    }
  }
}

class com::bluecast::xml::Entity : public ::java::lang::Object
{
public:
  virtual jboolean isOpen () = 0;
  virtual void open () = 0;
  virtual void close () = 0;
  virtual ::java::lang::String *getPublicID () = 0;
  virtual ::java::lang::String *getSystemID () = 0;
  virtual jboolean isStandalone () = 0;
  virtual void setStandalone (jboolean) = 0;
  virtual jboolean isInternal () = 0;
  virtual jboolean isParsed () = 0;
  virtual ::java::lang::String *getDeclaredEncoding () = 0;
  virtual jboolean isStandaloneDeclared () = 0;
  virtual ::java::lang::String *getXMLVersion () = 0;
  virtual ::java::io::Reader *getReader () = 0;
  virtual ::java::lang::String *stringValue () = 0;
  virtual jcharArray charArrayValue () = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __com_bluecast_xml_Entity__ */
