// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_EntityManager$Entry__
#define __com_bluecast_xml_EntityManager$Entry__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class EntityManager$Entry;
        class EntityManager;
        class XMLInputReader;
      }
    }
  }
}

class com::bluecast::xml::EntityManager$Entry : public ::java::lang::Object
{
public: // actually package-private
  EntityManager$Entry (::com::bluecast::xml::EntityManager *, ::java::lang::String *);
  EntityManager$Entry (::com::bluecast::xml::EntityManager *, ::java::lang::String *, ::java::lang::String *);
  EntityManager$Entry (::com::bluecast::xml::EntityManager *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *);
public:
  void open ();
  jboolean isOpen () { return isOpen__; }
  void close ();
  ::java::lang::String *getSystemID () { return sysID; }
  ::java::lang::String *getPublicID () { return pubID; }
  jboolean isStandalone () { return isStandalone__; }
  void setStandalone (jboolean);
  jboolean isInternal ();
  jboolean isParsed ();
  ::java::lang::String *getDeclaredEncoding ();
  jboolean isStandaloneDeclared ();
  ::java::lang::String *getXMLVersion ();
  ::java::io::Reader *getReader ();
  ::java::lang::String *stringValue ();
  jcharArray charArrayValue () { return value; }
public: // actually package-private
  jboolean __attribute__((aligned(__alignof__( ::java::lang::Object ))))  isOpen__;
  jcharArray value;
  ::java::lang::String *pubID;
  ::java::lang::String *sysID;
  ::java::lang::String *ndata;
  ::com::bluecast::xml::XMLInputReader *reader;
  jboolean isStandalone__;
  ::com::bluecast::xml::EntityManager *this$0;

  friend class com_bluecast_xml_EntityManager$Entry;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_EntityManager$Entry__ */
