// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_EntityManager__
#define __com_bluecast_xml_EntityManager__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class EntityManager;
        class Entity;
      }
    }
  }
  namespace org
  {
    namespace xml
    {
      namespace sax
      {
        class EntityResolver;
      }
    }
  }
}

class com::bluecast::xml::EntityManager : public ::java::lang::Object
{
public:
  EntityManager ();
  EntityManager (::org::xml::sax::EntityResolver *);
  virtual void setResolver (::org::xml::sax::EntityResolver *);
  virtual ::org::xml::sax::EntityResolver *getResolver () { return resolver; }
  virtual jboolean putInternal (::java::lang::String *, ::java::lang::String *, jint);
  virtual jboolean putExternal (::com::bluecast::xml::Entity *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, jint);
  virtual jboolean putUnparsed (::com::bluecast::xml::Entity *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, ::java::lang::String *, jint);
  virtual void clear ();
  virtual ::com::bluecast::xml::Entity *getByName (::java::lang::String *, jint);
  virtual ::com::bluecast::xml::Entity *getByID (::com::bluecast::xml::Entity *, ::java::lang::String *, ::java::lang::String *);
  static ::java::lang::String *resolveSystemID (::java::lang::String *, ::java::lang::String *);
public: // actually package-private
  static ::org::xml::sax::EntityResolver *access$000 (::com::bluecast::xml::EntityManager *) { return resolver; }
public:
  static const jint GENERAL = 0L;
  static const jint PARAMETER = 1L;
private:
  ::org::xml::sax::EntityResolver * __attribute__((aligned(__alignof__( ::java::lang::Object )))) resolver;
  JArray< ::java::util::Map *> *entityMaps;
  ::java::util::Map *entitiesByURI;

  friend class com_bluecast_xml_EntityManager$Entry;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_EntityManager__ */
