// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_FactoryFinder__
#define __javax_xml_parsers_FactoryFinder__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class FactoryFinder;
      }
    }
  }
}

class javax::xml::parsers::FactoryFinder : public ::java::lang::Object
{
public: // actually package-private
  FactoryFinder ();
private:
  static void debugPrintln (::java::lang::String *);
  static ::java::lang::ClassLoader *findClassLoader ();
  static ::java::lang::Object *newInstance (::java::lang::String *, ::java::lang::ClassLoader *);
public: // actually package-private
  static ::java::lang::Object *find (::java::lang::String *, ::java::lang::String *);
private:
  static jboolean debug;

  friend class javax_xml_parsers_FactoryFinder$1;
  friend class javax_xml_parsers_FactoryFinder$ClassLoaderFinderConcrete;
  friend class javax_xml_parsers_FactoryFinder$ClassLoaderFinder;
  friend class javax_xml_parsers_FactoryFinder$ConfigurationError;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_FactoryFinder__ */
