// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_FactoryFinder$ConfigurationError__
#define __javax_xml_parsers_FactoryFinder$ConfigurationError__

#pragma interface

#include <java/lang/Error.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class FactoryFinder$ConfigurationError;
      }
    }
  }
}

class javax::xml::parsers::FactoryFinder$ConfigurationError : public ::java::lang::Error
{
public: // actually package-private
  FactoryFinder$ConfigurationError (::java::lang::String *, ::java::lang::Exception *);
  virtual ::java::lang::Exception *getException () { return exception; }
private:
  ::java::lang::Exception * __attribute__((aligned(__alignof__( ::java::lang::Error )))) exception;

  friend class javax_xml_parsers_FactoryFinder$ConfigurationError;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_FactoryFinder$ConfigurationError__ */
