// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_FactoryFinder$1__
#define __javax_xml_parsers_FactoryFinder$1__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class FactoryFinder$1;
      }
    }
  }
}

class javax::xml::parsers::FactoryFinder$1 : public ::java::lang::Object
{

  friend class javax_xml_parsers_FactoryFinder$1;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_FactoryFinder$1__ */
