// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_FactoryFinder$ClassLoaderFinder__
#define __javax_xml_parsers_FactoryFinder$ClassLoaderFinder__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class FactoryFinder$ClassLoaderFinder;
        class FactoryFinder$1;
      }
    }
  }
}

class javax::xml::parsers::FactoryFinder$ClassLoaderFinder : public ::java::lang::Object
{
private:
  FactoryFinder$ClassLoaderFinder ();
public: // actually package-private
  virtual ::java::lang::ClassLoader *getContextClassLoader () = 0;
  FactoryFinder$ClassLoaderFinder (::javax::xml::parsers::FactoryFinder$1 *);

  friend class javax_xml_parsers_FactoryFinder$1;
  friend class javax_xml_parsers_FactoryFinder$ClassLoaderFinder;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_FactoryFinder$ClassLoaderFinder__ */
