// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_FactoryServiceFinder$FactoryEnumeration__
#define __com_bluecast_util_FactoryServiceFinder$FactoryEnumeration__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class FactoryServiceFinder$FactoryEnumeration;
      }
    }
  }
}

class com::bluecast::util::FactoryServiceFinder$FactoryEnumeration : public ::java::lang::Object
{
public: // actually package-private
  FactoryServiceFinder$FactoryEnumeration (::java::util::Enumeration *);
public:
  virtual jboolean hasMoreElements ();
  virtual ::java::lang::Object *nextElement ();
public: // actually package-private
  ::java::util::Enumeration * __attribute__((aligned(__alignof__( ::java::lang::Object )))) enumValue;
  ::java::lang::Object *next;

  friend class com_bluecast_util_FactoryServiceFinder$FactoryEnumeration;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_FactoryServiceFinder$FactoryEnumeration__ */
