// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_FactoryServiceFinder__
#define __com_bluecast_util_FactoryServiceFinder__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class FactoryServiceFinder;
      }
    }
  }
}

class com::bluecast::util::FactoryServiceFinder : public ::java::lang::Object
{
public:
  FactoryServiceFinder ();
  static ::java::lang::String *findService (::java::lang::String *);
  static ::java::util::Enumeration *findServices (::java::lang::String *);
public: // actually package-private
  static ::java::lang::String *SERVICE;

  friend class com_bluecast_util_FactoryServiceFinder$FactoryEnumeration;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_FactoryServiceFinder__ */
