// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __javax_xml_parsers_FactoryFinder$ClassLoaderFinderConcrete__
#define __javax_xml_parsers_FactoryFinder$ClassLoaderFinderConcrete__

#pragma interface

#include <javax/xml/parsers/FactoryFinder$ClassLoaderFinder.h>

extern "Java"
{
  namespace javax
  {
    namespace xml
    {
      namespace parsers
      {
        class FactoryFinder$ClassLoaderFinderConcrete;
      }
    }
  }
}

class javax::xml::parsers::FactoryFinder$ClassLoaderFinderConcrete : public ::javax::xml::parsers::FactoryFinder$ClassLoaderFinder
{
public: // actually package-private
  FactoryFinder$ClassLoaderFinderConcrete ();
  virtual ::java::lang::ClassLoader *getContextClassLoader ();

  friend class javax_xml_parsers_FactoryFinder$ClassLoaderFinderConcrete;
  friend class javax_xml_parsers_FactoryFinder$ClassLoaderFinder;
  friend class javax_xml_parsers_FactoryFinder$1;
public:

  static ::java::lang::Class class$;
};

#endif /* __javax_xml_parsers_FactoryFinder$ClassLoaderFinderConcrete__ */
