// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_FatalParsingException__
#define __com_bluecast_xml_FatalParsingException__

#pragma interface

#include <org/xml/sax/SAXException.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class FatalParsingException;
      }
    }
  }
}

class com::bluecast::xml::FatalParsingException : public ::org::xml::sax::SAXException
{
public: // actually package-private
  FatalParsingException (::java::lang::String *);
  FatalParsingException (::java::lang::String *, ::java::lang::Exception *);
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_FatalParsingException__ */
