// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_io_FileFormatException__
#define __com_bluecast_io_FileFormatException__

#pragma interface

#include <java/io/IOException.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace io
      {
        class FileFormatException;
      }
    }
  }
}

class com::bluecast::io::FileFormatException : public ::java::io::IOException
{
public:
  FileFormatException ();
  FileFormatException (::java::lang::String *);
  FileFormatException (::java::lang::String *, jint, jint);
  virtual jint getLine () { return line; }
  virtual jint getColumn () { return column; }
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::java::io::IOException ))))  line;
  jint column;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_io_FileFormatException__ */
