// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_io_IllegalCharException__
#define __com_bluecast_io_IllegalCharException__

#pragma interface

#include <java/io/CharConversionException.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace io
      {
        class IllegalCharException;
      }
    }
  }
}

class com::bluecast::io::IllegalCharException : public ::java::io::CharConversionException
{
public:
  IllegalCharException (::java::lang::String *);
public:  // actually protected
  jint __attribute__((aligned(__alignof__( ::java::io::CharConversionException ))))  line;
  jint column;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_io_IllegalCharException__ */
