// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_IndexedObjectImpl__
#define __com_bluecast_util_IndexedObjectImpl__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class IndexedObjectImpl;
      }
    }
  }
}

class com::bluecast::util::IndexedObjectImpl : public ::java::lang::Object
{
public:
  IndexedObjectImpl (jint, ::java::lang::Object *);
  jint getIndex () { return index; }
  void setIndex (jint);
  ::java::lang::Object *getObject () { return object; }
  void setObject (::java::lang::Object *);
  ::java::lang::Object *clone ();
  jboolean equals (::java::lang::Object *);
private:
  jint __attribute__((aligned(__alignof__( ::java::lang::Object ))))  index;
  ::java::lang::Object *object;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_IndexedObjectImpl__ */
