// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_IndexedObject__
#define __com_bluecast_util_IndexedObject__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class IndexedObject;
      }
    }
  }
}

class com::bluecast::util::IndexedObject : public ::java::lang::Object
{
public:
  virtual jint getIndex () = 0;
  virtual void setIndex (jint) = 0;
  virtual ::java::lang::Object *getObject () = 0;
  virtual void setObject (::java::lang::Object *) = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __com_bluecast_util_IndexedObject__ */
