// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_IntStack__
#define __com_bluecast_util_IntStack__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class IntStack;
      }
    }
  }
}

class com::bluecast::util::IntStack : public ::java::lang::Object
{
public:
  IntStack (jint);
  jint pop ();
  void push (jint);
  void setSize (jint);
  void clear ();
  jint size ();
private:
  jintArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  stack;
  jint pos;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_IntStack__ */
