// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_JAXPSAXParserFactory$JAXPSAXParser__
#define __com_bluecast_xml_JAXPSAXParserFactory$JAXPSAXParser__

#pragma interface

#include <javax/xml/parsers/SAXParser.h>

extern "Java"
{
  namespace org
  {
    namespace xml
    {
      namespace sax
      {
        class XMLReader;
        class Parser;
      }
    }
  }
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class JAXPSAXParserFactory$JAXPSAXParser;
        class Piccolo;
      }
    }
  }
}

class com::bluecast::xml::JAXPSAXParserFactory$JAXPSAXParser : public ::javax::xml::parsers::SAXParser
{
public: // actually package-private
  JAXPSAXParserFactory$JAXPSAXParser (::com::bluecast::xml::Piccolo *);
public:
  virtual ::org::xml::sax::Parser *getParser () { return reinterpret_cast< ::org::xml::sax::Parser *> (parser); }
  virtual ::java::lang::Object *getProperty (::java::lang::String *);
  virtual ::org::xml::sax::XMLReader *getXMLReader () { return reinterpret_cast< ::org::xml::sax::XMLReader *> (parser); }
  virtual jboolean isNamespaceAware ();
  virtual jboolean isValidating ();
  virtual void setProperty (::java::lang::String *, ::java::lang::Object *);
public: // actually package-private
  ::com::bluecast::xml::Piccolo * __attribute__((aligned(__alignof__( ::javax::xml::parsers::SAXParser )))) parser;

  friend class com_bluecast_xml_JAXPSAXParserFactory$JAXPSAXParser;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_JAXPSAXParserFactory$JAXPSAXParser__ */
