// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_LongStack__
#define __com_bluecast_util_LongStack__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class LongStack;
      }
    }
  }
}

class com::bluecast::util::LongStack : public ::java::lang::Object
{
public:
  LongStack (jint);
  jlong pop ();
  void push (jlong);
  void setSize (jint);
  void clear ();
  jint size ();
private:
  jlongArray __attribute__((aligned(__alignof__( ::java::lang::Object ))))  stack;
  jint pos;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_LongStack__ */
