// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_Piccolo$1__
#define __com_bluecast_xml_Piccolo$1__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class Piccolo$1;
      }
    }
  }
}

class com::bluecast::xml::Piccolo$1 : public ::java::lang::Object
{

  friend class com_bluecast_xml_Piccolo$1;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_Piccolo$1__ */
