// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_PiccoloLexer$YY_StreamInfo__
#define __com_bluecast_xml_PiccoloLexer$YY_StreamInfo__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class PiccoloLexer$YY_StreamInfo;
      }
    }
  }
}

class com::bluecast::xml::PiccoloLexer$YY_StreamInfo : public ::java::lang::Object
{
public: // actually package-private
  PiccoloLexer$YY_StreamInfo (::java::io::Reader *, jint, jint, jint, jint, jint, jint, jcharArray, jboolean, jint, jint);
  ::java::io::Reader * __attribute__((aligned(__alignof__( ::java::lang::Object )))) yy_reader;
  jint yy_endRead;
  jint yy_startRead;
  jint yy_savePos;
  jint yy_currentPos;
  jint yy_markedPos;
  jint yy_pushbackPos;
  jint yyline;
  jint yycolumn;
  jcharArray yy_buffer;
  jboolean yy_atEOF;

  friend class com_bluecast_xml_PiccoloLexer$YY_StreamInfo;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_PiccoloLexer$YY_StreamInfo__ */
