// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_Piccolo$StartLocator__
#define __com_bluecast_xml_Piccolo$StartLocator__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class Piccolo$StartLocator;
        class Piccolo$1;
        class Piccolo;
      }
    }
  }
}

class com::bluecast::xml::Piccolo$StartLocator : public ::java::lang::Object
{
private:
  Piccolo$StartLocator (::com::bluecast::xml::Piccolo *);
public:
  virtual jint getLineNumber ();
  virtual jint getColumnNumber ();
  virtual ::java::lang::String *getPublicId () { return 0; }
  virtual ::java::lang::String *getSystemId () { return 0; }
public: // actually package-private
  Piccolo$StartLocator (::com::bluecast::xml::Piccolo *, ::com::bluecast::xml::Piccolo$1 *);
  ::com::bluecast::xml::Piccolo * __attribute__((aligned(__alignof__( ::java::lang::Object )))) this$0;

  friend class com_bluecast_xml_Piccolo$1;
  friend class com_bluecast_xml_Piccolo$StartLocator;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_Piccolo$StartLocator__ */
