// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_RecursionException__
#define __com_bluecast_util_RecursionException__

#pragma interface

#include <java/lang/Exception.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class RecursionException;
      }
    }
  }
}

class com::bluecast::util::RecursionException : public ::java::lang::Exception
{
public:
  RecursionException (::java::lang::String *);
  RecursionException ();

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_RecursionException__ */
