// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_util_StringStack__
#define __com_bluecast_util_StringStack__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace util
      {
        class StringStack;
      }
    }
  }
}

class com::bluecast::util::StringStack : public ::java::lang::Object
{
public:
  StringStack (jint);
  virtual ::java::lang::String *pop ();
  virtual void push (::java::lang::String *);
  virtual void setSize (jint);
  virtual void clear ();
  virtual jint size ();
private:
  JArray< ::java::lang::String *> * __attribute__((aligned(__alignof__( ::java::lang::Object )))) stack;
  jint pos;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_util_StringStack__ */
