// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_UTF8XMLDecoder__
#define __com_bluecast_xml_UTF8XMLDecoder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class UTF8XMLDecoder;
        class XMLDecoder;
      }
      namespace io
      {
        class CharsetDecoder;
      }
    }
  }
}

class com::bluecast::xml::UTF8XMLDecoder : public ::java::lang::Object
{
public:
  UTF8XMLDecoder ();
  ::com::bluecast::io::CharsetDecoder *newCharsetDecoder ();
  ::com::bluecast::xml::XMLDecoder *newXMLDecoder ();
  jint minBytesPerChar ();
  jint maxBytesPerChar ();
  void reset ();
  void decode (jbyteArray, jint, jint, jcharArray, jint, jint, jintArray);
  void decodeXMLDecl (jbyteArray, jint, jint, jcharArray, jint, jint, jintArray);
private:
  jboolean __attribute__((aligned(__alignof__( ::java::lang::Object ))))  sawCR;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_UTF8XMLDecoder__ */
