// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_XMLDecoderFactory__
#define __com_bluecast_xml_XMLDecoderFactory__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class XMLDecoderFactory;
        class XMLDecoder;
      }
    }
  }
}

class com::bluecast::xml::XMLDecoderFactory : public ::java::lang::Object
{
public:
  XMLDecoderFactory ();
  static ::com::bluecast::xml::XMLDecoder *createDecoder (::java::lang::String *);
private:
  static ::java::util::HashMap *decoders;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_XMLDecoderFactory__ */
