// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_XMLDecoder__
#define __com_bluecast_xml_XMLDecoder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class XMLDecoder;
      }
    }
  }
}

class com::bluecast::xml::XMLDecoder : public ::java::lang::Object
{
public:
  virtual void decodeXMLDecl (jbyteArray, jint, jint, jcharArray, jint, jint, jintArray) = 0;
  virtual ::com::bluecast::xml::XMLDecoder *newXMLDecoder () = 0;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __com_bluecast_xml_XMLDecoder__ */
