// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __org_xml_sax_helpers_XMLReaderAdapter$AttributesAdapter__
#define __org_xml_sax_helpers_XMLReaderAdapter$AttributesAdapter__

#pragma interface

#include <java/lang/Object.h>

extern "Java"
{
  namespace org
  {
    namespace xml
    {
      namespace sax
      {
        namespace helpers
        {
          class XMLReaderAdapter$AttributesAdapter;
          class XMLReaderAdapter;
        }
        class Attributes;
      }
    }
  }
}

class org::xml::sax::helpers::XMLReaderAdapter$AttributesAdapter : public ::java::lang::Object
{
public: // actually package-private
  XMLReaderAdapter$AttributesAdapter (::org::xml::sax::helpers::XMLReaderAdapter *);
  void setAttributes (::org::xml::sax::Attributes *);
public:
  jint getLength ();
  ::java::lang::String *getName (jint);
  ::java::lang::String *getType (jint);
  ::java::lang::String *getValue (jint);
  ::java::lang::String *getType (::java::lang::String *);
  ::java::lang::String *getValue (::java::lang::String *);
private:
  ::org::xml::sax::Attributes * __attribute__((aligned(__alignof__( ::java::lang::Object )))) attributes;
public: // actually package-private
  ::org::xml::sax::helpers::XMLReaderAdapter *this$0;

  friend class org_xml_sax_helpers_XMLReaderAdapter$AttributesAdapter;
public:

  static ::java::lang::Class class$;
};

#endif /* __org_xml_sax_helpers_XMLReaderAdapter$AttributesAdapter__ */
