// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_XMLReaderReader__
#define __com_bluecast_xml_XMLReaderReader__

#pragma interface

#include <com/bluecast/xml/XMLInputReader.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class XMLReaderReader;
      }
    }
  }
}

class com::bluecast::xml::XMLReaderReader : public ::com::bluecast::xml::XMLInputReader
{
public:
  XMLReaderReader ();
  XMLReaderReader (::java::io::Reader *);
  XMLReaderReader (::java::io::Reader *, jboolean);
  void reset (::java::io::Reader *, jboolean);
  void close ();
  void mark (jint);
  jboolean markSupported ();
  jint read ();
  jint read (jcharArray);
  jint read (jcharArray, jint, jint);
  jboolean ready ();
  void reset ();
  jlong skip (jlong);
private:
  void fillCharBuffer ();
  void processXMLDecl ();
  static const jint BUFFER_SIZE = 8192L;
  ::java::io::Reader * __attribute__((aligned(__alignof__( ::com::bluecast::xml::XMLInputReader )))) in;
  jboolean rewindDeclaration;
  jcharArray cbuf;
  jint cbufPos;
  jint cbufEnd;
  jboolean eofReached;
  jboolean sawCR;
  jcharArray oneCharBuf;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_XMLReaderReader__ */
