// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_XMLStreamReader$XMLStreamDecoder__
#define __com_bluecast_xml_XMLStreamReader$XMLStreamDecoder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class XMLStreamReader$XMLStreamDecoder;
      }
    }
  }
}

class com::bluecast::xml::XMLStreamReader$XMLStreamDecoder : public ::java::lang::Object
{
public:
  virtual jint read () = 0;
  virtual jint read (jcharArray, jint, jint) = 0;
  virtual jboolean ready () = 0;
  virtual jlong skip (jlong) = 0;
  virtual void reset () = 0;

  friend class com_bluecast_xml_XMLStreamReader$XMLStreamDecoder;

  static ::java::lang::Class class$;
} __attribute__ ((java_interface));

#endif /* __com_bluecast_xml_XMLStreamReader$XMLStreamDecoder__ */
