// DO NOT EDIT THIS FILE - it is machine generated -*- c++ -*-

#ifndef __com_bluecast_xml_XMLStreamReader$FastStreamDecoder__
#define __com_bluecast_xml_XMLStreamReader$FastStreamDecoder__

#pragma interface

#include <java/lang/Object.h>
#include <gcj/array.h>

extern "Java"
{
  namespace com
  {
    namespace bluecast
    {
      namespace xml
      {
        class XMLStreamReader$FastStreamDecoder;
        class XMLStreamReader;
      }
    }
  }
}

class com::bluecast::xml::XMLStreamReader$FastStreamDecoder : public ::java::lang::Object
{
public:
  XMLStreamReader$FastStreamDecoder (::com::bluecast::xml::XMLStreamReader *);
  virtual void reset () { }
  virtual jint read ();
  virtual jint read (jcharArray, jint, jint);
  virtual jboolean ready ();
  virtual jlong skip (jlong);
public: // actually package-private
  ::com::bluecast::xml::XMLStreamReader * __attribute__((aligned(__alignof__( ::java::lang::Object )))) this$0;

  friend class com_bluecast_xml_XMLStreamReader$FastStreamDecoder;
  friend class com_bluecast_xml_XMLStreamReader$XMLStreamDecoder;
public:

  static ::java::lang::Class class$;
};

#endif /* __com_bluecast_xml_XMLStreamReader$FastStreamDecoder__ */
