SOURCES 	= \
	basic_item_factory.cpp \
	atomic_items.cpp \
	node_items.cpp \
	simple_store.cpp \
	simple_collection.cpp \
	simple_temp_seq.cpp \

# Include global Makefile rules
ROOT_PATH		= ../..
include $(ROOT_PATH)/Makefile.rules