#!/bin/bash

if [ ! ${zorbaRepos} ]; then

  if [ ! ${SRC} ]; then
    echo "ERROR: SRC variable is not set"
    exit 1
  fi

  export zorbaRepos=$SRC
fi


if [ ! ${zorbaExce} ]; then

  if [ ! ${ZORBA} ]; then
    echo "ERROR: ZORBA variable is not set"
    exit 1
  fi

  export zorbaExec=$ZORBA
fi


$zorbaRepos/test/rbkt/Scripts/rbkt.sh > /dev/null

echo
cat rbkt_summary.txt
echo

rm -f rbkt_summary.txt > /dev/null
rm -f query.xml > /dev/null
rm -f query.dot > /dev/null
