#!/bin/bash

if [ ! ${zorbaRepos} ]; then

  if [ ! ${SRC} ]; then
    echo "ERROR: SRC variable is not set"
    exit 1
  fi

  export zorbaRepos=$SRC
fi


if [ ! ${zorbaExecDir} ]; then

  if [ ! ${ZORBA_EXEC_DIR} ]; then
    echo "ERROR: ZORBA_EXEC_DIR variable is not set"
    exit 1
  fi

  export zorbaExecDir=$ZORBA_EXEC_DIR
fi


$zorbaRepos/test/rbkt/Scripts/rbkt.sh > /dev/null

echo
cat rbkt_summary.txt
echo

rm -f rbkt_summary.txt
rm -f query.xml query.dot
