
SOURCES 	= \
	expr.cpp \
	update_expr.cpp \
	ft_expr.cpp \
	normalize_visitor.cpp \
	parsenode_print_xml_visitor.cpp \
	parsenode_print_dot_visitor.cpp

expr_test	= \
		../context/context.cpp \
		../functions/signature.cpp \
		../parser/symbol_table.cpp \
		../runtime/errors.cpp \
		../runtime/iterator.cpp \
		../store/qname_cache.cpp \
		../store/itemstore.cpp \
		../types/sequence_type.cpp \
		../util/file.cpp \
		../util/fxcharheap.cpp \
		../util/mmfile.cpp \
		../util/xqp_exception.cpp \
		../values/values.cpp \
		../values/nodes.cpp \
		../values/xs_primitive_values.cpp \
		expr.cpp \
		expr_test.cpp


normalize_visitor_test = \
		../context/static_context.cpp \
		../context/dynamic_context.cpp \
		../dom/dom_namepool.cpp \
		../dom/dom_nodes.cpp \
		../dom/dom_qname.cpp \
		../dom/dom_xml_handler.cpp \
		../functions/library.cpp \
		../functions/Numerics.cpp \
		../functions/NumericsImpl.cpp \
		../functions/Sequences.cpp \
		../functions/SequencesImpl.cpp \
		../functions/signature.cpp \
		../parser/parsenodes.cpp \
		../parser/xquery_scanner.cpp \
		../parser/xquery_parser.cpp \
		../parser/symbol_table.cpp \
		../parser/xquery_driver.cpp \
		../runtime/errors.cpp \
		../runtime/item_iterator.cpp \
		../runtime/zorba.cpp \
		../store/scan_handler.cpp \
		../store/uri_resolver.cpp \
		../store/xml_scanner.cpp \
		../store/zorba_uri_resolver.cpp \
		../types/sequence_type.cpp \
		../util/file.cpp \
		../util/fxcharheap.cpp \
		../util/tokenbuf.cpp \
		../util/mmfile.cpp \
		../util/URI.cpp \
		../util/xqp_exception.cpp \
		../values/primitive_values.cpp \
		../zorba/zorba_qname.cpp \
		../zorba/qnamerep.cpp \
		expr.cpp \
		normalize_visitor.cpp \
		normalize_visitor_test.cpp


#BINARIES	= expr_test normalize_visitor_test
BINARIES	= 


# Include global Makefile rules
ROOT_PATH	= ..
include $(ROOT_PATH)/Makefile.rules
