"fn:something" cast as xs:QName,
"http://www.addr.ch" cast as xs:anyURI,
"atomic" cast as xs:untypedAtomic,
"string" cast as xs:string,
"2.3" cast as xs:decimal, 2.3 cast as xs:decimal,
"3" cast as xs:int, 3 cast as xs:int,
"3" cast as xs:integer, 3 cast as xs:integer,
"3.23" cast as xs:double, 3.23 cast as xs:double,
"3.23" cast as xs:float, 3.23 cast as xs:float,
"true" cast as  xs:boolean, true() cast as xs:boolean
