<?xml version="1.0" encoding="UTF-8"?>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:path>/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.zorba-xquery.com</uri:host><uri:path>/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.zorba-xquery.com</uri:host><uri:path>/</uri:path><uri:query>abc=true</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.zorba-xquery.com</uri:host><uri:port>8080</uri:port><uri:path>/</uri:path><uri:query>abc=true</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:user-info>user</uri:user-info><uri:host>www.zorba-xquery.com</uri:host><uri:port>8080</uri:port><uri:path>/</uri:path><uri:query>abc=true</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:user-info>user</uri:user-info><uri:host>www.zorba-xquery.com</uri:host><uri:port>8080</uri:port><uri:path>/path1/path2</uri:path><uri:query>abc=true</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:user-info>user</uri:user-info><uri:host>www.zorba-xquery.com</uri:host><uri:port>8080</uri:port><uri:path>/path1/path2</uri:path><uri:query>abc=true&amp;bcd=false</uri:query><uri:fragment>fragment</uri:fragment></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>ftp</uri:scheme><uri:host>ftp.is.co.za</uri:host><uri:path>/rfc/rfc1808.txt</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:user-info>thomas</uri:user-info><uri:host>[2001:6f8:9000:876:cccc:bbbb::]</uri:host><uri:port>123</uri:port><uri:path>/test</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/g</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/</uri:path><uri:query>y</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path><uri:query>y</uri:query></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path><uri:fragment>s</uri:fragment></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path><uri:query>y</uri:query><uri:fragment>s</uri:fragment></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/;x</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g;x</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g;x</uri:path><uri:query>y</uri:query><uri:fragment>s</uri:fragment></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/g</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/g</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g;x=1/y</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/y</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>a</uri:host><uri:path>/b/c/g</uri:path><uri:fragment>s/../x</uri:fragment></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.example.com</uri:host><uri:path>/</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.example.com</uri:host><uri:path>/dir/file</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.msb.de</uri:host></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>http</uri:scheme><uri:host>www.msb.de</uri:host><uri:path>/lib/helpers</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>file</uri:scheme><uri:path>/d:/a/b/c</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>file</uri:scheme><uri:host>localhost</uri:host><uri:path>/d:/a/b/c</uri:path></uri:uri>
<uri:uri xmlns:uri="http://www.zorba-xquery.com/modules/uri"><uri:scheme>file</uri:scheme><uri:host>localhost</uri:host><uri:path>/Ãƒâ€¦ngstrÃƒÂ¶m/b/c</uri:path></uri:uri>
