<?xml version="1.0" encoding="UTF-8"?>
http:/ 
 http://www.zorba-xquery.com/ 
 http://www.zorba-xquery.com/?abc=true 
 http://www.zorba-xquery.com:8080/?abc=true 
 http://user@www.zorba-xquery.com:8080/?abc=true 
 http://user@www.zorba-xquery.com:8080/path1/path2?abc=true 
 http://user@www.zorba-xquery.com:8080/path1/path2?abc=true&amp;bcd=false 
 ftp://ftp.is.co.za/rfc/rfc1808.txt 
 http://thomas@[2001:6f8:9000:876:cccc:bbbb::]:123/test 
 http://a/b/c/g 
 http://a/b/c/g/ 
 http://a/g 
 http://a/b/c/?y 
 http://a/b/c/g?y 
 http://a/b/c/g#s 
 http://a/b/c/g?y#s 
 http://a/b/c/;x 
 http://a/b/c/g;x 
 http://a/b/c/g;x?y#s 
 http://a/b/c 
 http://a/b/c/ 
 http://a/b 
 http://a/b/ 
 http://a/b/g 
 http://a/ 
 http://a/g 
 http://a/b/c/g;x=1/y 
 http://a/b/c/y 
 http://a/b/c/g#s/../x 
 http://www.example.com/ 
 http://www.example.com/dir/file 
 http://www.msb.de 
 http://www.msb.de/lib/helpers 
 file://localhost/Ãƒâ€¦ngstrÃƒÂ¶m/b/c 
 file:opaque-uri-part#frag 
 file:text-file.txt 
